{"metadata":{"externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCConsentKeys(cpy)ccpaOptIn","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ccpaOptIn","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","kind":"typeIdentifier","text":"ConsentKey"}],"navigatorTitle":[{"text":"ccpaOptIn","kind":"identifier"}],"title":"ccpaOptIn","symbolKind":"property","roleHeading":"Type Property","role":"symbol","modules":[{"name":"ChartboostCoreSDK"}]},"variants":[{"paths":["\/documentation\/chartboostcoresdk\/consentkeys\/ccpaoptin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostcoresdk\/consentkeys\/ccpaoptin"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"text":"CCPA opt-in key.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Possible values are: "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/denied"},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/granted","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/doesNotApply","isActive":true,"type":"reference"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"ccpaOptIn","kind":"identifier"},{"kind":"text","text":": "},{"text":"ConsentKey","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","kind":"typeIdentifier"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/ccpaOptIn","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKey":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A key in a Core consents dictionary."}],"title":"ConsentKey","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsentKey"}],"role":"symbol","url":"\/documentation\/chartboostcoresdk\/consentkey","navigatorTitle":[{"text":"ConsentKey","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentValues/granted":{"url":"\/documentation\/chartboostcoresdk\/consentvalues\/granted","abstract":[{"text":"Indicates the user granted consent.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/granted","kind":"symbol","role":"symbol","title":"granted","navigatorTitle":[{"kind":"identifier","text":"granted"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"granted"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea","kind":"typeIdentifier","text":"ConsentValue"}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKeys":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys","navigatorTitle":[{"text":"ConsentKeys","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/consentkeys","kind":"symbol","title":"ConsentKeys","abstract":[{"type":"text","text":"A namespace for Core’s predefined "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","type":"reference"},{"text":" constants.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConsentKeys","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKeys/ccpaOptIn":{"title":"ccpaOptIn","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ccpaOptIn","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","text":"ConsentKey","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"ccpaOptIn","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/ccpaOptIn","kind":"symbol","abstract":[{"type":"text","text":"CCPA opt-in key."},{"text":" ","type":"text"},{"type":"text","text":"Possible values are: "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/denied"},{"type":"text","text":", "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/granted","isActive":true},{"type":"text","text":", "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/doesNotApply","type":"reference"},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/chartboostcoresdk\/consentkeys\/ccpaoptin","type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentValues/denied":{"url":"\/documentation\/chartboostcoresdk\/consentvalues\/denied","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/denied","type":"topic","title":"denied","navigatorTitle":[{"kind":"identifier","text":"denied"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"denied","kind":"identifier"},{"kind":"text","text":": "},{"text":"ConsentValue","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea"}],"role":"symbol","abstract":[{"text":"Indicates the user denied consent.","type":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentValues/doesNotApply":{"title":"doesNotApply","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/doesNotApply","url":"\/documentation\/chartboostcoresdk\/consentvalues\/doesnotapply","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"doesNotApply","kind":"identifier"},{"kind":"text","text":": "},{"text":"ConsentValue","preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"doesNotApply"}],"abstract":[{"text":"Indicates the standard does not apply.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"ccpaOptIn","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ccpaOptIn"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"ccpaOptIn"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"granted","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues~1granted\/title","op":"replace"},{"value":[{"kind":"identifier","text":"granted"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues~1granted\/fragments","op":"replace"},{"value":"CBCConsentKeys","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys\/fragments","value":[{"kind":"identifier","text":"CBCConsentKeys"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys\/navigatorTitle","value":[{"kind":"identifier","text":"CBCConsentKeys"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1ccpaOptIn\/title","value":"ccpaOptIn","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1ccpaOptIn\/fragments","value":[{"kind":"identifier","text":"ccpaOptIn"}]},{"value":"denied","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues~1denied\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues~1denied\/fragments","value":[{"text":"denied","kind":"identifier"}]},{"value":"doesNotApply","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues~1doesNotApply\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues~1doesNotApply\/fragments","value":[{"text":"doesNotApply","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}