{"abstract":[{"text":"GPP key.","type":"text"},{"type":"text","text":" "},{"text":"Possible values are IAB’s GPP strings, as defined in https:\/\/github.com\/InteractiveAdvertisingBureau\/Global-Privacy-Platform\/blob\/main\/Core\/Consent%20String%20Specification.md","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/chartboostcoresdk\/consentkeys\/gpp"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostcoresdk\/consentkeys\/gpp"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys"]]},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"gpp","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","text":"ConsentKey"}],"roleHeading":"Type Property","title":"gpp","externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCConsentKeys(cpy)gpp","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"gpp","kind":"identifier"}],"modules":[{"name":"ChartboostCoreSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gpp","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ConsentKey","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/gpp"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKeys/gpp":{"title":"gpp","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/gpp","type":"topic","url":"\/documentation\/chartboostcoresdk\/consentkeys\/gpp","abstract":[{"type":"text","text":"GPP key."},{"text":" ","type":"text"},{"type":"text","text":"Possible values are IAB’s GPP strings, as defined in https:\/\/github.com\/InteractiveAdvertisingBureau\/Global-Privacy-Platform\/blob\/main\/Core\/Consent%20String%20Specification.md"}],"role":"symbol","navigatorTitle":[{"text":"gpp","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gpp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","text":"ConsentKey","kind":"typeIdentifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKeys":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentKeys"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentkeys","title":"ConsentKeys","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys","abstract":[{"text":"A namespace for Core’s predefined ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","isActive":true,"type":"reference"},{"text":" constants.","type":"text"}],"navigatorTitle":[{"text":"ConsentKeys","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKey":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsentKey","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentkey","title":"ConsentKey","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","abstract":[{"text":"A key in a Core consents dictionary.","type":"text"}],"navigatorTitle":[{"text":"ConsentKey","kind":"identifier"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"gpp"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"gpp","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"gpp","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1gpp\/title","op":"replace","value":"gpp"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1gpp\/fragments","op":"replace","value":[{"text":"gpp","kind":"identifier"}]},{"value":"CBCConsentKeys","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys\/fragments","op":"replace","value":[{"text":"CBCConsentKeys","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}