{"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"tcf","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","text":"ConsentKey","kind":"typeIdentifier"}],"modules":[{"name":"ChartboostCoreSDK"}],"title":"tcf","externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCConsentKeys(cpy)tcf","roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"tcf"}],"symbolKind":"property","role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"tcf","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConsentKey","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/tcf"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/consentkeys\/tcf"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/consentkeys\/tcf"]}],"abstract":[{"text":"TCF key.","type":"text"},{"type":"text","text":" "},{"text":"Possible values are IAB’s TCF strings, as defined in https:\/\/github.com\/InteractiveAdvertisingBureau\/GDPR-Transparency-and-Consent-Framework\/blob\/master\/TCFv2\/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKeys/tcf":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"tcf","kind":"identifier"},{"kind":"text","text":": "},{"text":"ConsentKey","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentkeys\/tcf","title":"tcf","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/tcf","abstract":[{"text":"TCF key.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Possible values are IAB’s TCF strings, as defined in https:\/\/github.com\/InteractiveAdvertisingBureau\/GDPR-Transparency-and-Consent-Framework\/blob\/master\/TCFv2\/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md"}],"navigatorTitle":[{"text":"tcf","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKey":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsentKey","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentkey","title":"ConsentKey","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","abstract":[{"text":"A key in a Core consents dictionary.","type":"text"}],"navigatorTitle":[{"text":"ConsentKey","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKeys":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentKeys"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentkeys","title":"ConsentKeys","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys","abstract":[{"text":"A namespace for Core’s predefined ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","isActive":true,"type":"reference"},{"text":" constants.","type":"text"}],"navigatorTitle":[{"text":"ConsentKeys","kind":"identifier"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"path":"\/metadata\/title","value":"tcf","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"tcf","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"tcf"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1tcf\/title","value":"tcf"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1tcf\/fragments","op":"replace","value":[{"kind":"identifier","text":"tcf"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys\/title","op":"replace","value":"CBCConsentKeys"},{"value":[{"text":"CBCConsentKeys","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}