{"abstract":[{"type":"text","text":"USP key."},{"type":"text","text":" "},{"type":"text","text":"Possible values are IAB’s USP strings, as defined in https:\/\/github.com\/InteractiveAdvertisingBureau\/USPrivacy\/blob\/master\/CCPA\/US%20Privacy%20String.md"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"usp","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","text":"ConsentKey","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"usp","kind":"identifier"}],"roleHeading":"Type Property","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"usp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","kind":"typeIdentifier","text":"ConsentKey"}],"title":"usp","symbolKind":"property","modules":[{"name":"ChartboostCoreSDK"}],"externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCConsentKeys(cpy)usp"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/consentkeys\/usp"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/consentkeys\/usp"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/usp","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKey":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsentKey","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentkey","title":"ConsentKey","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","abstract":[{"text":"A key in a Core consents dictionary.","type":"text"}],"navigatorTitle":[{"text":"ConsentKey","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKeys":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentKeys"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentkeys","title":"ConsentKeys","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys","abstract":[{"text":"A namespace for Core’s predefined ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","isActive":true,"type":"reference"},{"text":" constants.","type":"text"}],"navigatorTitle":[{"text":"ConsentKeys","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKeys/usp":{"url":"\/documentation\/chartboostcoresdk\/consentkeys\/usp","kind":"symbol","type":"topic","title":"usp","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/usp","navigatorTitle":[{"text":"usp","kind":"identifier"}],"abstract":[{"text":"USP key.","type":"text"},{"text":" ","type":"text"},{"text":"Possible values are IAB’s USP strings, as defined in https:\/\/github.com\/InteractiveAdvertisingBureau\/USPrivacy\/blob\/master\/CCPA\/US%20Privacy%20String.md","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"usp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConsentKey","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"usp"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"usp","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"usp"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys\/title","op":"replace","value":"CBCConsentKeys"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys\/fragments","value":[{"kind":"identifier","text":"CBCConsentKeys"}]},{"value":"usp","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1usp\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1usp\/fragments","value":[{"text":"usp","kind":"identifier"}]}]}]}