{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chartboostAppID","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/chartboostcoresdk\/moduleconfiguration\/chartboostappid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostcoresdk\/moduleconfiguration\/chartboostappid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleConfiguration\/chartboostAppID","interfaceLanguage":"swift"},"abstract":[{"text":"The Chartboost App ID which should match the value on the Chartboost dashboard.","type":"text"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleConfiguration"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"chartboostAppID"}],"title":"chartboostAppID","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"chartboostAppID","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"ChartboostCoreSDK"}],"externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCModuleConfiguration(py)chartboostAppID"},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleConfiguration":{"navigatorTitle":[{"text":"ModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/moduleconfiguration","type":"topic","role":"symbol","title":"ModuleConfiguration","abstract":[{"text":"Configuration with parameters needed by ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module"},{"type":"text","text":" on initialization."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleConfiguration","kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Module":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Module","kind":"identifier"}],"kind":"symbol","title":"Module","url":"\/documentation\/chartboostcoresdk\/module","type":"topic","abstract":[{"type":"text","text":"The protocol to which all Chartboost Core modules must conform to."}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module","role":"symbol","navigatorTitle":[{"text":"Module","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleConfiguration/chartboostAppID":{"navigatorTitle":[{"text":"chartboostAppID","kind":"identifier"}],"abstract":[{"type":"text","text":"The Chartboost App ID which should match the value on the Chartboost dashboard."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chartboostAppID","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","type":"topic","url":"\/documentation\/chartboostcoresdk\/moduleconfiguration\/chartboostappid","title":"chartboostAppID","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleConfiguration\/chartboostAppID"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"chartboostAppID","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"chartboostAppID"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"chartboostAppID","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleConfiguration\/title","value":"CBCModuleConfiguration"},{"value":[{"kind":"identifier","text":"CBCModuleConfiguration"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/title","value":"CBCModule"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/fragments","value":[{"text":"CBCModule","kind":"identifier"}]},{"op":"replace","value":"chartboostAppID","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleConfiguration~1chartboostAppID\/title"},{"value":[{"kind":"identifier","text":"chartboostAppID"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleConfiguration~1chartboostAppID\/fragments"}]}]}