{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/chartboostcoresdk\/consentobserver\/onconsentmoduleready(initialconsents:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostcoresdk\/consentobserver\/onconsentmoduleready(initialconsents:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"onConsentModuleReady(initialConsents:)","modules":[{"name":"ChartboostCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"onConsentModuleReadyWithInitialConsents:"}],"symbolKind":"method","externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentObserver(im)onConsentModuleReadyWithInitialConsents:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConsentModuleReady"},{"text":"(","kind":"text"},{"text":"initialConsents","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"ConsentKey","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"ConsentValue","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea"},{"kind":"text","text":"])"}],"roleHeading":"Instance Method","required":true},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver\/onConsentModuleReady(initialConsents:)"},"kind":"symbol","abstract":[{"text":"Called when the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","type":"reference"},{"text":" module is initialized and the ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform","isActive":true,"type":"reference"},{"text":" object","type":"text"},{"type":"text","text":" "},{"type":"text","text":"is ready to be used."},{"type":"text","text":" "},{"type":"text","text":"At this moment "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents"},{"type":"text","text":" will have proper values and methods like"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:)","isActive":true,"type":"reference"},{"type":"text","text":" will no longer be no-ops."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConsentModuleReady"},{"kind":"text","text":"("},{"kind":"externalParam","text":"initialConsents"},{"kind":"text","text":": ["},{"text":"ConsentKey","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValue","text":"ConsentValue","preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea"},{"kind":"text","text":"])"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The initial value for "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents","isActive":true,"type":"reference"},{"type":"text","text":" right after the"},{"type":"text","text":" "},{"text":"CMP became ready. Here the CMP may have restored consent info from a previous session.","type":"text"}]}],"name":"initialConsents"}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"It’s important to note that a consent adapter module may take some time to initialize and"},{"type":"text","text":" "},{"text":"restore the consent information from a previous session. Until then, ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform"},{"type":"text","text":" "},{"text":"provides default values for its properties. Once the information becomes first available,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"this method is invoked, but not "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver\/onConsentChange(fullConsents:modifiedKeys:)","type":"reference"},{"text":".","type":"text"}]}]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentValue":{"title":"ConsentValue","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsentValue"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentvalue","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValue","role":"symbol","type":"topic","navigatorTitle":[{"text":"ConsentValue","kind":"identifier"}],"abstract":[{"text":"A value in a Core consents dictionary.","type":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentObserver/onConsentChange(fullConsents:modifiedKeys:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConsentChange","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fullConsents"},{"text":": [","kind":"text"},{"text":"ConsentKey","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"},{"kind":"text","text":" : "},{"text":"ConsentValue","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"modifiedKeys"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","text":"ConsentKey"},{"text":">)","kind":"text"}],"title":"onConsentChange(fullConsents:modifiedKeys:)","url":"\/documentation\/chartboostcoresdk\/consentobserver\/onconsentchange(fullconsents:modifiedkeys:)","kind":"symbol","abstract":[{"text":"Called whenever the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents","type":"reference"},{"type":"text","text":" value changed."}],"required":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver\/onConsentChange(fullConsents:modifiedKeys:)","navigatorTitle":[{"kind":"identifier","text":"onConsentChangeWithFullConsents:modifiedKeys:"}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsentAdapter"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","abstract":[{"type":"text","text":"The protocol to which a CMP adapter module must conform to."}],"url":"\/documentation\/chartboostcoresdk\/consentadapter","title":"ConsentAdapter","navigatorTitle":[{"text":"ConsentAdapter","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentObserver/onConsentModuleReady(initialConsents:)":{"title":"onConsentModuleReady(initialConsents:)","required":true,"type":"topic","url":"\/documentation\/chartboostcoresdk\/consentobserver\/onconsentmoduleready(initialconsents:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onConsentModuleReadyWithInitialConsents:"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver\/onConsentModuleReady(initialConsents:)","abstract":[{"type":"text","text":"Called when the "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","type":"reference"},{"text":" module is initialized and the ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform","isActive":true},{"type":"text","text":" object"},{"text":" ","type":"text"},{"text":"is ready to be used.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"At this moment "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents","type":"reference","isActive":true},{"text":" will have proper values and methods like","type":"text"},{"text":" ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:)","isActive":true},{"text":" will no longer be no-ops.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onConsentModuleReady","kind":"identifier"},{"text":"(","kind":"text"},{"text":"initialConsents","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"ConsentKey","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"},{"text":" : ","kind":"text"},{"text":"ConsentValue","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea"},{"kind":"text","text":"])"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/consents":{"kind":"symbol","title":"consents","abstract":[{"type":"text","text":"Current user consent info as determined by the CMP."}],"type":"topic","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/consents","required":true,"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents","navigatorTitle":[{"kind":"identifier","text":"consents"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"consents"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","text":"ConsentKey"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea","text":"ConsentValue","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentObserver":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsentObserver"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver","abstract":[{"type":"text","text":"An observer that gets notified whenever any change happens in the CMP consent info."}],"url":"\/documentation\/chartboostcoresdk\/consentobserver","title":"ConsentObserver","navigatorTitle":[{"text":"ConsentObserver","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentManagementPlatform"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform","role":"symbol","abstract":[{"type":"text","text":"Chartboost Core’s CMP in charge of handling user consent management."},{"type":"text","text":" "},{"type":"text","text":"Chartboost Core defines a unified API for publishers to request and query user consent,"},{"type":"text","text":" "},{"type":"text","text":"and relies on a 3rd-party CMP SDK to provide the CMP functionality."}],"title":"ConsentManagementPlatform","kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform","navigatorTitle":[{"kind":"identifier","text":"ConsentManagementPlatform"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/showConsentDialog(_:from:)":{"kind":"symbol","title":"showConsentDialog(_:from:)","abstract":[{"type":"text","text":"Instructs the CMP to present a consent dialog to the user for the purpose of collecting consent."}],"type":"topic","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/showconsentdialog(_:from:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showConsentDialog","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ConsentDialogType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentDialogType"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKey":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A key in a Core consents dictionary."}],"title":"ConsentKey","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsentKey"}],"role":"symbol","url":"\/documentation\/chartboostcoresdk\/consentkey","navigatorTitle":[{"text":"ConsentKey","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"onConsentModuleReadyWithInitialConsents:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onConsentModuleReadyWithInitialConsents:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"onConsentModuleReadyWithInitialConsents:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"text":"initialConsents","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"initialConsents","content":[{"type":"paragraph","inlineContent":[{"text":"The initial value for ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents"},{"text":" right after the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"CMP became ready. Here the CMP may have restored consent info from a previous session."}]}]}]}},{"value":"onConsentChangeWithFullConsents:modifiedKeys:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver~1onConsentChange(fullConsents:modifiedKeys:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver~1onConsentChange(fullConsents:modifiedKeys:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onConsentChangeWithFullConsents:modifiedKeys:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/title","value":"CBCConsentAdapter"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/fragments","value":[{"kind":"identifier","text":"CBCConsentAdapter"}]},{"op":"replace","value":[{"text":"CBCConsentAdapter","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/navigatorTitle"},{"op":"replace","value":"onConsentModuleReadyWithInitialConsents:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver~1onConsentModuleReady(initialConsents:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver~1onConsentModuleReady(initialConsents:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onConsentModuleReadyWithInitialConsents:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1consents\/title","value":"consents","op":"replace"},{"value":[{"text":"consents","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1consents\/fragments","op":"replace"},{"value":"CBCConsentObserver","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver\/fragments","value":[{"kind":"identifier","text":"CBCConsentObserver"}]},{"value":[{"kind":"identifier","text":"CBCConsentObserver"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/title","value":"CBCConsentManagementPlatform"},{"op":"replace","value":[{"kind":"identifier","text":"CBCConsentManagementPlatform"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/navigatorTitle","op":"replace","value":[{"text":"CBCConsentManagementPlatform","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}