{"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver\/onConsentChange(fullConsents:modifiedKeys:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver"]]},"abstract":[{"type":"text","text":"Called whenever the "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents","isActive":true,"type":"reference"},{"text":" value changed.","type":"text"}],"metadata":{"required":true,"externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentObserver(im)onConsentChangeWithFullConsents:modifiedKeys:","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onConsentChange","kind":"identifier"},{"kind":"text","text":"("},{"text":"fullConsents","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"ConsentKey","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"ConsentValue","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"modifiedKeys"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"text":"<","kind":"text"},{"text":"ConsentKey","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","kind":"typeIdentifier"},{"kind":"text","text":">)"}],"roleHeading":"Instance Method","symbolKind":"method","title":"onConsentChange(fullConsents:modifiedKeys:)","navigatorTitle":[{"kind":"identifier","text":"onConsentChangeWithFullConsents:modifiedKeys:"}],"modules":[{"name":"ChartboostCoreSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConsentChange","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fullConsents"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","text":"ConsentKey"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"ConsentValue","preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValue"},{"text":"], ","kind":"text"},{"text":"modifiedKeys","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","kind":"typeIdentifier","text":"ConsentKey","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"},{"text":">)","kind":"text"}]}]},{"parameters":[{"name":"fullConsents","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The new value for "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents","type":"reference","isActive":true},{"text":" after the update,","type":"text"},{"type":"text","text":" "},{"text":"including both modified and unmodified consents.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A set containing all the keys that changed."}]}],"name":"modifiedKeys"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/chartboostcoresdk\/consentobserver\/onconsentchange(fullconsents:modifiedkeys:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostcoresdk\/consentobserver\/onconsentchange(fullconsents:modifiedkeys:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentValue":{"title":"ConsentValue","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsentValue"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentvalue","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValue","role":"symbol","type":"topic","navigatorTitle":[{"text":"ConsentValue","kind":"identifier"}],"abstract":[{"text":"A value in a Core consents dictionary.","type":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/consents":{"kind":"symbol","title":"consents","abstract":[{"type":"text","text":"Current user consent info as determined by the CMP."}],"type":"topic","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/consents","required":true,"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents","navigatorTitle":[{"kind":"identifier","text":"consents"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"consents"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","text":"ConsentKey"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea","text":"ConsentValue","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentObserver":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsentObserver"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver","abstract":[{"type":"text","text":"An observer that gets notified whenever any change happens in the CMP consent info."}],"url":"\/documentation\/chartboostcoresdk\/consentobserver","title":"ConsentObserver","navigatorTitle":[{"text":"ConsentObserver","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentObserver/onConsentChange(fullConsents:modifiedKeys:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConsentChange","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fullConsents"},{"text":": [","kind":"text"},{"text":"ConsentKey","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"},{"kind":"text","text":" : "},{"text":"ConsentValue","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"modifiedKeys"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","text":"ConsentKey"},{"text":">)","kind":"text"}],"title":"onConsentChange(fullConsents:modifiedKeys:)","url":"\/documentation\/chartboostcoresdk\/consentobserver\/onconsentchange(fullconsents:modifiedkeys:)","kind":"symbol","abstract":[{"text":"Called whenever the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents","type":"reference"},{"type":"text","text":" value changed."}],"required":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver\/onConsentChange(fullConsents:modifiedKeys:)","navigatorTitle":[{"kind":"identifier","text":"onConsentChangeWithFullConsents:modifiedKeys:"}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKey":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A key in a Core consents dictionary."}],"title":"ConsentKey","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsentKey"}],"role":"symbol","url":"\/documentation\/chartboostcoresdk\/consentkey","navigatorTitle":[{"text":"ConsentKey","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onConsentChangeWithFullConsents:modifiedKeys:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"onConsentChangeWithFullConsents:modifiedKeys:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onConsentChangeWithFullConsents:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"text":"fullConsents","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"modifiedKeys:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSSet","text":"NSSet<NSString *>"},{"text":" *) ","kind":"text"},{"text":"modifiedKeys","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"fullConsents","content":[{"inlineContent":[{"type":"text","text":"The new value for "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents","isActive":true,"type":"reference"},{"type":"text","text":" after the update,"},{"type":"text","text":" "},{"type":"text","text":"including both modified and unmodified consents."}],"type":"paragraph"}]},{"name":"modifiedKeys","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A set containing all the keys that changed."}]}]}]},"path":"\/primaryContentSections\/1"},{"value":"consents","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1consents\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"consents"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1consents\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver\/title","value":"CBCConsentObserver"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver\/fragments","value":[{"text":"CBCConsentObserver","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"CBCConsentObserver"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver~1onConsentChange(fullConsents:modifiedKeys:)\/title","op":"replace","value":"onConsentChangeWithFullConsents:modifiedKeys:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConsentChangeWithFullConsents:modifiedKeys:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver~1onConsentChange(fullConsents:modifiedKeys:)\/fragments"}]}]}