{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"denyConsent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource","text":"ConsentSource","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentSource","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"succeeded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The source of the new consent. See the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource"},{"text":" documentation for more info.","type":"text"}],"type":"paragraph"}],"name":"source"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Handler called to indicate if the operation went through successfully or not.","type":"text"}]}],"name":"completion"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/denyConsent(source:completion:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter"]]},"variants":[{"paths":["\/documentation\/chartboostcoresdk\/consentadapter\/denyconsent(source:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/consentadapter\/denyconsent(source:completion:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"required":true,"title":"denyConsent(source:completion:)","symbolKind":"method","modules":[{"name":"ChartboostCoreSDK"}],"navigatorTitle":[{"text":"denyConsentWithSource:completion:","kind":"identifier"}],"externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentAdapter(im)denyConsentWithSource:completion:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"denyConsent"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConsentSource","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentSource"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"succeeded"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol"},"abstract":[{"text":"Informs the CMP that the user has denied consent.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This method should be used only when a custom consent dialog is presented to the user, thereby making the publisher"},{"text":" ","type":"text"},{"text":"responsible for the UI-side of collecting consent. In most cases ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/showConsentDialog(_:from:completion:)"},{"type":"text","text":" should"},{"text":" ","type":"text"},{"text":"be used instead.","type":"text"},{"text":" ","type":"text"},{"text":"If the CMP does not support custom consent dialogs or the operation fails for any other reason, the completion","type":"text"},{"type":"text","text":" "},{"type":"text","text":"handler is executed with a "},{"code":"false","type":"codeVoice"},{"type":"text","text":" parameter."}],"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentSource":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource","navigatorTitle":[{"text":"ConsentSource","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsentSource","kind":"identifier"}],"title":"ConsentSource","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/chartboostcoresdk\/consentsource","abstract":[{"text":"The source of a consent change.","type":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter/showConsentDialog(_:from:completion:)":{"role":"symbol","required":true,"type":"topic","abstract":[{"type":"text","text":"Instructs the CMP to present a consent dialog to the user for the purpose of collecting consent."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showConsentDialog"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"ConsentDialogType","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentDialogType"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"succeeded"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/showConsentDialog(_:from:completion:)","navigatorTitle":[{"text":"showConsentDialog:from:completion:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentadapter\/showconsentdialog(_:from:completion:)","title":"showConsentDialog(_:from:completion:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter/denyConsent(source:completion:)":{"title":"denyConsent(source:completion:)","url":"\/documentation\/chartboostcoresdk\/consentadapter\/denyconsent(source:completion:)","required":true,"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/denyConsent(source:completion:)","navigatorTitle":[{"kind":"identifier","text":"denyConsentWithSource:completion:"}],"type":"topic","abstract":[{"type":"text","text":"Informs the CMP that the user has denied consent."},{"type":"text","text":" "},{"type":"text","text":"This method should be used only when a custom consent dialog is presented to the user, thereby making the publisher"},{"type":"text","text":" "},{"text":"responsible for the UI-side of collecting consent. In most cases ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/showConsentDialog(_:from:completion:)"},{"type":"text","text":" should"},{"text":" ","type":"text"},{"type":"text","text":"be used instead."},{"type":"text","text":" "},{"text":"If the CMP does not support custom consent dialogs or the operation fails for any other reason, the completion","type":"text"},{"type":"text","text":" "},{"text":"handler is executed with a ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" parameter."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"denyConsent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ConsentSource","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentSource"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"succeeded","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ConsentAdapter","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","abstract":[{"text":"The protocol to which a CMP adapter module must conform to.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ConsentAdapter","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/consentadapter","title":"ConsentAdapter"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"denyConsentWithSource:completion:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"denyConsentWithSource:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"denyConsentWithSource:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource","text":"CBCConsentSource","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentSource","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"source"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"text":"void (^)(_Bool)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#b)"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource\/title","op":"replace","value":"CBCConsentSource"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource\/fragments","value":[{"text":"CBCConsentSource","kind":"identifier"}]},{"value":"showConsentDialog:from:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1showConsentDialog(_:from:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1showConsentDialog(_:from:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"showConsentDialog:from:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1denyConsent(source:completion:)\/title","value":"denyConsentWithSource:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1denyConsent(source:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"denyConsentWithSource:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/title","value":"CBCConsentAdapter","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/fragments","op":"replace","value":[{"text":"CBCConsentAdapter","kind":"identifier"}]}]}]}