{"metadata":{"navigatorTitle":[{"text":"grantConsentWithSource:completion:","kind":"identifier"}],"externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentAdapter(im)grantConsentWithSource:completion:","symbolKind":"method","role":"symbol","title":"grantConsent(source:completion:)","required":true,"roleHeading":"Instance Method","modules":[{"name":"ChartboostCoreSDK"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"grantConsent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"source","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConsentSource","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentSource"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"succeeded"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"abstract":[{"type":"text","text":"Informs the CMP that the user has granted consent."},{"text":" ","type":"text"},{"type":"text","text":"This method should be used only when a custom consent dialog is presented to the user, thereby making the publisher"},{"text":" ","type":"text"},{"type":"text","text":"responsible for the UI-side of collecting consent. In most cases "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/showConsentDialog(_:from:completion:)"},{"type":"text","text":" should"},{"text":" ","type":"text"},{"text":"be used instead.","type":"text"},{"type":"text","text":" "},{"text":"If the CMP does not support custom consent dialogs or the operation fails for any other reason, the completion","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"handler is executed with a "},{"code":"false","type":"codeVoice"},{"text":" parameter.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"grantConsent"},{"kind":"text","text":"("},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource","text":"ConsentSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentSource"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"succeeded","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"source","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The source of the new consent. See the "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource","isActive":true,"type":"reference"},{"text":" documentation for more info.","type":"text"}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Handler called to indicate if the operation went through successfully or not."}],"type":"paragraph"}]}]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/grantConsent(source:completion:)"},"variants":[{"paths":["\/documentation\/chartboostcoresdk\/consentadapter\/grantconsent(source:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/consentadapter\/grantconsent(source:completion:)"]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentSource":{"title":"ConsentSource","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsentSource"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentsource","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource","role":"symbol","type":"topic","navigatorTitle":[{"text":"ConsentSource","kind":"identifier"}],"abstract":[{"type":"text","text":"The source of a consent change."}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter/showConsentDialog(_:from:completion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"showConsentDialog","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"ConsentDialogType","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentDialogType"},{"kind":"text","text":", "},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"succeeded","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"showConsentDialog:from:completion:","kind":"identifier"}],"type":"topic","title":"showConsentDialog(_:from:completion:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/showConsentDialog(_:from:completion:)","required":true,"abstract":[{"type":"text","text":"Instructs the CMP to present a consent dialog to the user for the purpose of collecting consent."}],"url":"\/documentation\/chartboostcoresdk\/consentadapter\/showconsentdialog(_:from:completion:)","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter/grantConsent(source:completion:)":{"title":"grantConsent(source:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"grantConsent"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"text":"ConsentSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentSource"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"succeeded","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/grantConsent(source:completion:)","required":true,"url":"\/documentation\/chartboostcoresdk\/consentadapter\/grantconsent(source:completion:)","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"grantConsentWithSource:completion:","kind":"identifier"}],"abstract":[{"text":"Informs the CMP that the user has granted consent.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This method should be used only when a custom consent dialog is presented to the user, thereby making the publisher"},{"text":" ","type":"text"},{"text":"responsible for the UI-side of collecting consent. In most cases ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/showConsentDialog(_:from:completion:)"},{"type":"text","text":" should"},{"type":"text","text":" "},{"type":"text","text":"be used instead."},{"type":"text","text":" "},{"type":"text","text":"If the CMP does not support custom consent dialogs or the operation fails for any other reason, the completion"},{"text":" ","type":"text"},{"type":"text","text":"handler is executed with a "},{"type":"codeVoice","code":"false"},{"type":"text","text":" parameter."}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsentAdapter"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","abstract":[{"type":"text","text":"The protocol to which a CMP adapter module must conform to."}],"url":"\/documentation\/chartboostcoresdk\/consentadapter","title":"ConsentAdapter","navigatorTitle":[{"text":"ConsentAdapter","kind":"identifier"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"grantConsentWithSource:completion:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"grantConsentWithSource:completion:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"grantConsentWithSource:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentSource","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource","kind":"typeIdentifier","text":"CBCConsentSource"},{"text":") ","kind":"text"},{"text":"source","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":{"parameters":[{"name":"source","content":[{"type":"paragraph","inlineContent":[{"text":"The source of the new consent. See the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource"},{"text":" documentation for more info.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Handler called to indicate if the operation went through successfully or not."}]}],"name":"completion"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource\/title","value":"CBCConsentSource","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource\/fragments","value":[{"text":"CBCConsentSource","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource\/navigatorTitle","op":"replace","value":[{"text":"CBCConsentSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1showConsentDialog(_:from:completion:)\/title","value":"showConsentDialog:from:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1showConsentDialog(_:from:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"showConsentDialog:from:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1grantConsent(source:completion:)\/title","op":"replace","value":"grantConsentWithSource:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"grantConsentWithSource:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1grantConsent(source:completion:)\/fragments"},{"value":"CBCConsentAdapter","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/fragments","value":[{"kind":"identifier","text":"CBCConsentAdapter"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/navigatorTitle","op":"replace","value":[{"text":"CBCConsentAdapter","kind":"identifier"}]}]}]}