{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"log","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"level"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCLogLevel","kind":"typeIdentifier","text":"LogLevel","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The string to log."},{"text":" ","type":"text"},{"type":"text","text":"A prefix is added to identify the adapter when printing out the message to the console."}]}]},{"name":"level","content":[{"inlineContent":[{"text":"The log severity level.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Method","externalID":"s:17ChartboostCoreSDK14ConsentAdapterPAAE3log_5levelySS_AA8LogLevelOtF","symbolKind":"method","extendedModule":"ChartboostCoreSDK","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"log","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCLogLevel","text":"LogLevel"},{"kind":"text","text":")"}],"title":"log(_:level:)","modules":[{"name":"ChartboostCoreSDK"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/log(_:level:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter"]]},"sections":[],"abstract":[{"type":"text","text":"Logs a message using the Core SDK’s internal logging system."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/consentadapter\/log(_:level:)"]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter/log(_:level:)":{"title":"log(_:level:)","url":"\/documentation\/chartboostcoresdk\/consentadapter\/log(_:level:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/log(_:level:)","abstract":[{"text":"Logs a message using the Core SDK’s internal logging system.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"log","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"level"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"LogLevel","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCLogLevel"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ConsentAdapter","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","abstract":[{"text":"The protocol to which a CMP adapter module must conform to.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ConsentAdapter","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/consentadapter","title":"ConsentAdapter"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel":{"navigatorTitle":[{"text":"LogLevel","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"kind":"symbol","abstract":[{"text":"Log severity levels for the unified logging subsystem.","type":"text"}],"url":"\/documentation\/chartboostcoresdk\/loglevel","title":"LogLevel","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"CBCConsentAdapter","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/fragments","value":[{"kind":"identifier","text":"CBCConsentAdapter"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel\/title","op":"replace","value":"CBCLogLevel"},{"op":"replace","value":[{"kind":"identifier","text":"CBCLogLevel"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}