{"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/startObservingUserDefaultsIABStrings()","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter"]]},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"ChartboostCoreSDK"}],"title":"startObservingUserDefaultsIABStrings()","externalID":"s:17ChartboostCoreSDK14ConsentAdapterPAAE36startObservingUserDefaultsIABStringsypyF","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startObservingUserDefaultsIABStrings"},{"text":"() -> ","kind":"text"},{"text":"Any","kind":"keyword"}],"role":"symbol","extendedModule":"ChartboostCoreSDK"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"startObservingUserDefaultsIABStrings","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Any","kind":"keyword"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"An observer object that must be kept alive in the adapter."}],"type":"paragraph"}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Just make sure to call this method on a successful initialization and keep the returned observer object","type":"text"},{"type":"text","text":" "},{"text":"alive in your adapter instance.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/consentadapter\/startobservinguserdefaultsiabstrings()"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Adds an observer to get notified whenever IAB strings stored in UserDefaults change."},{"text":" ","type":"text"},{"text":"If the CMP follows the IAB standard this can be used to start observing consent changes","type":"text"},{"text":" ","type":"text"},{"text":"on initialization and have chages automatically trigger the appropriate ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapterDelegate","type":"reference","isActive":true},{"type":"text","text":" "},{"text":"methods.","type":"text"}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsentAdapter"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","abstract":[{"type":"text","text":"The protocol to which a CMP adapter module must conform to."}],"url":"\/documentation\/chartboostcoresdk\/consentadapter","title":"ConsentAdapter","navigatorTitle":[{"text":"ConsentAdapter","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapterDelegate":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapterDelegate","navigatorTitle":[{"kind":"identifier","text":"ConsentAdapterDelegate"}],"url":"\/documentation\/chartboostcoresdk\/consentadapterdelegate","kind":"symbol","title":"ConsentAdapterDelegate","abstract":[{"text":"The delegate of a ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","type":"reference","isActive":true},{"text":" module.","type":"text"},{"type":"text","text":" "},{"text":"It should get notified whenever any change happens in the CMP consent.","type":"text"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentAdapterDelegate"}],"role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter/startObservingUserDefaultsIABStrings()":{"url":"\/documentation\/chartboostcoresdk\/consentadapter\/startobservinguserdefaultsiabstrings()","role":"symbol","abstract":[{"text":"Adds an observer to get notified whenever IAB strings stored in UserDefaults change.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the CMP follows the IAB standard this can be used to start observing consent changes"},{"text":" ","type":"text"},{"text":"on initialization and have chages automatically trigger the appropriate ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapterDelegate"},{"text":" ","type":"text"},{"text":"methods.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"startObservingUserDefaultsIABStrings","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"keyword","text":"Any"}],"title":"startObservingUserDefaultsIABStrings()","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/startObservingUserDefaultsIABStrings()","type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CBCConsentAdapter","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/fragments","value":[{"text":"CBCConsentAdapter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/navigatorTitle","value":[{"text":"CBCConsentAdapter","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapterDelegate\/title","value":"CBCConsentAdapterDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapterDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBCConsentAdapterDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapterDelegate\/navigatorTitle","value":[{"text":"CBCConsentAdapterDelegate","kind":"identifier"}]}]}]}