{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleInitializationResult"]]},"sections":[],"abstract":[{"type":"text","text":"The identifier of the module that was attempted to be initialized."}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCModuleInitializationResult(py)moduleID","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moduleID","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"modules":[{"name":"ChartboostCoreSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"moduleID"}],"symbolKind":"property","title":"moduleID"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"moduleID","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"The initialization operation may have failed. Use the ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCoreResult\/error","isActive":true},{"type":"text","text":" property to determine this."}]}],"type":"aside"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleInitializationResult\/moduleID"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/moduleinitializationresult\/moduleid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/moduleinitializationresult\/moduleid"]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleInitializationResult":{"navigatorTitle":[{"kind":"identifier","text":"ModuleInitializationResult"}],"abstract":[{"type":"text","text":"A result object with the information regarding a module initialization operation."}],"url":"\/documentation\/chartboostcoresdk\/moduleinitializationresult","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModuleInitializationResult"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleInitializationResult","title":"ModuleInitializationResult","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCoreResult/error":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCoreResult\/error","type":"topic","title":"error","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"error","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/chartboostcoresdk\/chartboostcoreresult\/error","abstract":[{"text":"The error in case the operation failed, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the operation succeeded."}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleInitializationResult/moduleID":{"navigatorTitle":[{"kind":"identifier","text":"moduleID"}],"abstract":[{"type":"text","text":"The identifier of the module that was attempted to be initialized."}],"url":"\/documentation\/chartboostcoresdk\/moduleinitializationresult\/moduleid","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"moduleID","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleInitializationResult\/moduleID","title":"moduleID","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"moduleID","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"moduleID"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"moduleID","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"CBCModuleInitializationResult","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleInitializationResult\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleInitializationResult\/fragments","value":[{"kind":"identifier","text":"CBCModuleInitializationResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleInitializationResult\/navigatorTitle","value":[{"text":"CBCModuleInitializationResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCoreResult~1error\/title","value":"error","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCoreResult~1error\/fragments","op":"replace","value":[{"kind":"identifier","text":"error"}]},{"value":"moduleID","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleInitializationResult~1moduleID\/title"},{"op":"replace","value":[{"text":"moduleID","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleInitializationResult~1moduleID\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}