{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/!=(_:_:)"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"modules":[{"relatedModules":["Swift"],"name":"ChartboostCoreSDK"}],"roleHeading":"Operator","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@ChartboostCoreSDK@E@CBCObservableEnvironmentProperty","role":"symbol","symbolKind":"op","extendedModule":"Swift","title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/!=(_:_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/Equatable-Implementations"]]},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/EnvironmentObserver":{"url":"\/documentation\/chartboostcoresdk\/environmentobserver","navigatorTitle":[{"text":"EnvironmentObserver","kind":"identifier"}],"title":"EnvironmentObserver","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"EnvironmentObserver","kind":"identifier"}],"type":"topic","abstract":[{"text":"An observer that gets notified when the value of some observable environment field changes.","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty/!=(_:_:)":{"role":"symbol","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/!=(_:_:)","title":"!=(_:_:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty/Equatable-Implementations":{"kind":"article","url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/equatable-implementations","role":"collectionGroup","title":"Equatable Implementations","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/Equatable-Implementations"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty","navigatorTitle":[{"text":"ObservableEnvironmentProperty","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty","kind":"symbol","title":"ObservableEnvironmentProperty","abstract":[{"text":"A constant that identifies an environment property that can be observed via a ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ObservableEnvironmentProperty","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/title","value":"CBCEnvironmentObserver"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/fragments","value":[{"text":"CBCEnvironmentObserver","kind":"identifier"}],"op":"replace"},{"value":[{"text":"CBCEnvironmentObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/navigatorTitle"},{"value":"CBCObservableEnvironmentProperty","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty\/fragments","value":[{"kind":"identifier","text":"CBCObservableEnvironmentProperty"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty\/navigatorTitle","value":[{"text":"CBCObservableEnvironmentProperty","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}