{"metadata":{"symbolKind":"property","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@ChartboostCoreSDK@E@CBCObservableEnvironmentProperty","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"title":"hashValue","extendedModule":"Swift","modules":[{"relatedModules":["Swift"],"name":"ChartboostCoreSDK"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/hashvalue"]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/hashValue","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/RawRepresentable-Implementations"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/EnvironmentObserver":{"url":"\/documentation\/chartboostcoresdk\/environmentobserver","kind":"symbol","title":"EnvironmentObserver","abstract":[{"type":"text","text":"An observer that gets notified when the value of some observable environment field changes."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvironmentObserver"}],"navigatorTitle":[{"text":"EnvironmentObserver","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty":{"url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty","kind":"symbol","abstract":[{"type":"text","text":"A constant that identifies an environment property that can be observed via a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver"},{"text":".","type":"text"}],"title":"ObservableEnvironmentProperty","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObservableEnvironmentProperty"}],"navigatorTitle":[{"kind":"identifier","text":"ObservableEnvironmentProperty"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/rawrepresentable-implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/RawRepresentable-Implementations","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty/hashValue":{"kind":"symbol","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"title":"hashValue","abstract":[],"url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/hashvalue","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/hashValue","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/title","op":"replace","value":"CBCEnvironmentObserver"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBCEnvironmentObserver"}]},{"value":"CBCObservableEnvironmentProperty","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CBCObservableEnvironmentProperty"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty\/fragments"}]}]}