{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/isUserUnderage"},"abstract":[{"type":"text","text":"Property identifier associated to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/isUserUnderage"},{"text":".","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isUserUnderage"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty"]]},"metadata":{"roleHeading":"Case","symbolKind":"case","modules":[{"name":"ChartboostCoreSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"isUserUnderage","kind":"identifier"}],"navigatorTitle":[{"text":"CBCObservableEnvironmentPropertyIsUserUnderage","kind":"identifier"}],"externalID":"c:@M@ChartboostCoreSDK@E@CBCObservableEnvironmentProperty@CBCObservableEnvironmentPropertyIsUserUnderage","role":"symbol","title":"ObservableEnvironmentProperty.isUserUnderage"},"variants":[{"paths":["\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/isuserunderage"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/isuserunderage"]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty/isUserUnderage":{"abstract":[{"type":"text","text":"Property identifier associated to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/isUserUnderage"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/isUserUnderage","type":"topic","title":"ObservableEnvironmentProperty.isUserUnderage","url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/isuserunderage","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBCObservableEnvironmentPropertyIsUserUnderage"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isUserUnderage"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/PublisherMetadata/setIsUserUnderage(_:)":{"type":"topic","url":"\/documentation\/chartboostcoresdk\/publishermetadata\/setisuserunderage(_:)","kind":"symbol","title":"setIsUserUnderage(_:)","navigatorTitle":[{"kind":"identifier","text":"setIsUserUnderage:"}],"role":"symbol","abstract":[{"text":"Indicates if the user is underage as determined by the publisher.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setIsUserUnderage"},{"kind":"text","text":"("},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/PublisherMetadata\/setIsUserUnderage(_:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment/isUserUnderage":{"type":"topic","url":"\/documentation\/chartboostcoresdk\/analyticsenvironment\/isuserunderage","kind":"symbol","title":"isUserUnderage","navigatorTitle":[{"kind":"identifier","text":"isUserUnderage"}],"role":"symbol","abstract":[{"text":"Indicates whether the user is underage. This is determined by the latest value set by the publisher through","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"a call to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/PublisherMetadata\/setIsUserUnderage(_:)"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isUserUnderage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/isUserUnderage","required":true},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/EnvironmentObserver":{"url":"\/documentation\/chartboostcoresdk\/environmentobserver","kind":"symbol","title":"EnvironmentObserver","abstract":[{"type":"text","text":"An observer that gets notified when the value of some observable environment field changes."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvironmentObserver"}],"navigatorTitle":[{"text":"EnvironmentObserver","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty":{"url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty","kind":"symbol","abstract":[{"type":"text","text":"A constant that identifies an environment property that can be observed via a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver"},{"text":".","type":"text"}],"title":"ObservableEnvironmentProperty","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObservableEnvironmentProperty"}],"navigatorTitle":[{"kind":"identifier","text":"ObservableEnvironmentProperty"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"CBCObservableEnvironmentPropertyIsUserUnderage"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CBCObservableEnvironmentPropertyIsUserUnderage"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"CBCObservableEnvironmentPropertyIsUserUnderage","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty~1isUserUnderage\/title","value":"CBCObservableEnvironmentPropertyIsUserUnderage","op":"replace"},{"value":[{"kind":"identifier","text":"CBCObservableEnvironmentPropertyIsUserUnderage"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty~1isUserUnderage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1PublisherMetadata~1setIsUserUnderage(_:)\/title","value":"setIsUserUnderage:"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1PublisherMetadata~1setIsUserUnderage(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setIsUserUnderage:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1isUserUnderage\/title","value":"isUserUnderage"},{"value":[{"text":"isUserUnderage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1isUserUnderage\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/title","op":"replace","value":"CBCEnvironmentObserver"},{"value":[{"kind":"identifier","text":"CBCEnvironmentObserver"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/fragments","op":"replace"},{"op":"replace","value":"CBCObservableEnvironmentProperty","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty\/title"},{"value":[{"kind":"identifier","text":"CBCObservableEnvironmentProperty"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty\/fragments","op":"replace"}]}]}