{"metadata":{"modules":[{"name":"ChartboostCoreSDK"}],"title":"ObservableEnvironmentProperty.playerID","navigatorTitle":[{"kind":"identifier","text":"CBCObservableEnvironmentPropertyPlayerID"}],"externalID":"c:@M@ChartboostCoreSDK@E@CBCObservableEnvironmentProperty@CBCObservableEnvironmentPropertyPlayerID","symbolKind":"case","roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playerID","kind":"identifier"}]},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/playerID","interfaceLanguage":"swift"},"abstract":[{"text":"Property identifier associated to ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/playerID","isActive":true},{"text":".","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"playerID","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/playerid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/playerid"]}],"kind":"symbol","references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty","navigatorTitle":[{"text":"ObservableEnvironmentProperty","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty","kind":"symbol","title":"ObservableEnvironmentProperty","abstract":[{"text":"A constant that identifies an environment property that can be observed via a ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ObservableEnvironmentProperty","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment/playerID":{"required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"playerID","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"playerID","kind":"symbol","url":"\/documentation\/chartboostcoresdk\/analyticsenvironment\/playerid","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/playerID","abstract":[{"text":"The player identifier set by the publisher through a call to ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/PublisherMetadata\/setPlayerID(_:)","isActive":true},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"text":"playerID","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/PublisherMetadata/setPlayerID(_:)":{"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/publishermetadata\/setplayerid(_:)","abstract":[{"text":"Sets a publisher-defined player ID.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setPlayerID","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"setPlayerID:","kind":"identifier"}],"title":"setPlayerID(_:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/PublisherMetadata\/setPlayerID(_:)","type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/EnvironmentObserver":{"url":"\/documentation\/chartboostcoresdk\/environmentobserver","navigatorTitle":[{"text":"EnvironmentObserver","kind":"identifier"}],"title":"EnvironmentObserver","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"EnvironmentObserver","kind":"identifier"}],"type":"topic","abstract":[{"text":"An observer that gets notified when the value of some observable environment field changes.","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty/playerID":{"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/playerid","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"playerID","kind":"identifier"}],"role":"symbol","title":"ObservableEnvironmentProperty.playerID","abstract":[{"text":"Property identifier associated to ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/playerID"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/playerID","navigatorTitle":[{"text":"CBCObservableEnvironmentPropertyPlayerID","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"CBCObservableEnvironmentPropertyPlayerID","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"CBCObservableEnvironmentPropertyPlayerID","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"CBCObservableEnvironmentPropertyPlayerID","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty\/title","value":"CBCObservableEnvironmentProperty"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty\/fragments","value":[{"text":"CBCObservableEnvironmentProperty","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty\/navigatorTitle","value":[{"kind":"identifier","text":"CBCObservableEnvironmentProperty"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1playerID\/title","value":"playerID"},{"value":[{"text":"playerID","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1playerID\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1PublisherMetadata~1setPlayerID(_:)\/title","value":"setPlayerID:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setPlayerID:"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1PublisherMetadata~1setPlayerID(_:)\/fragments"},{"value":"CBCEnvironmentObserver","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CBCEnvironmentObserver"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/fragments"},{"value":[{"text":"CBCEnvironmentObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/navigatorTitle"},{"op":"replace","value":"CBCObservableEnvironmentPropertyPlayerID","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty~1playerID\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty~1playerID\/fragments","value":[{"kind":"identifier","text":"CBCObservableEnvironmentPropertyPlayerID"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}