{"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"addObserver:","kind":"identifier"}],"modules":[{"name":"ChartboostCoreSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addObserver"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentObserver","text":"ConsentObserver","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentManagementPlatform(im)addObserver:","required":true,"title":"addObserver(_:)"},"variants":[{"paths":["\/documentation\/chartboostcoresdk\/consentmanagementplatform\/addobserver(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostcoresdk\/consentmanagementplatform\/addobserver(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addObserver"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"observer","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentObserver","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver","kind":"typeIdentifier","text":"ConsentObserver"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"It is okay to add an observer before a consent adapter module is set.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/addObserver(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform"]]},"abstract":[{"type":"text","text":"Adds an observer to receive notifications whenever the CMP consent info changes."},{"type":"text","text":" "},{"text":"The Core SDK automatically notifies modules that conform to ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver","type":"reference","isActive":true},{"type":"text","text":" about these changes, so there is no need"},{"text":" ","type":"text"},{"text":"to manually add Core modules as observers.","type":"text"}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/addObserver(_:)":{"role":"symbol","abstract":[{"text":"Adds an observer to receive notifications whenever the CMP consent info changes.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The Core SDK automatically notifies modules that conform to "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver","type":"reference","isActive":true},{"text":" about these changes, so there is no need","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to manually add Core modules as observers."}],"navigatorTitle":[{"text":"addObserver:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/addObserver(_:)","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/addobserver(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addObserver","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentObserver","text":"ConsentObserver","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","required":true,"title":"addObserver(_:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform","kind":"symbol","navigatorTitle":[{"text":"ConsentManagementPlatform","kind":"identifier"}],"title":"ConsentManagementPlatform","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform","abstract":[{"type":"text","text":"Chartboost Core’s CMP in charge of handling user consent management."},{"type":"text","text":" "},{"type":"text","text":"Chartboost Core defines a unified API for publishers to request and query user consent,"},{"type":"text","text":" "},{"text":"and relies on a 3rd-party CMP SDK to provide the CMP functionality.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsentManagementPlatform","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentObserver":{"title":"ConsentObserver","url":"\/documentation\/chartboostcoresdk\/consentobserver","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsentObserver","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"An observer that gets notified whenever any change happens in the CMP consent info."}],"navigatorTitle":[{"kind":"identifier","text":"ConsentObserver"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"addObserver:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addObserver:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"addObserver:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<CBCConsentObserver>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ChartboostCoreSDK@objc(pl)CBCConsentObserver"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"observer"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1addObserver(_:)\/title","value":"addObserver:"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1addObserver(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addObserver:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/title","value":"CBCConsentManagementPlatform","op":"replace"},{"value":[{"text":"CBCConsentManagementPlatform","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/fragments"},{"value":"CBCConsentObserver","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver\/fragments","value":[{"text":"CBCConsentObserver","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}