{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"text":"Current user consent info as determined by the CMP.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/consentmanagementplatform\/consents"]},{"paths":["\/documentation\/chartboostcoresdk\/consentmanagementplatform\/consents"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents","interfaceLanguage":"swift"},"metadata":{"required":true,"title":"consents","symbolKind":"property","modules":[{"name":"ChartboostCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"consents"}],"externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentManagementPlatform(py)consents","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"consents"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","text":"ConsentKey","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea","kind":"typeIdentifier","text":"ConsentValue"},{"kind":"text","text":"]"}],"roleHeading":"Instance Property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"consents"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","text":"ConsentKey","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"ConsentValue","preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValue"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"Consent info may include IAB strings, like TCF or GPP, and parsed boolean-like signals like “CCPA Opt In Sale”"},{"type":"text","text":" "},{"type":"text","text":"and partner-specific signals."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"text":"Make sure to use predefined consent key constants defined in ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys"},{"text":" to access specific entries in","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the dictionary. You may use predefined consent value constants defined in "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues","isActive":true,"type":"reference"},{"text":" for comparing","type":"text"},{"type":"text","text":" "},{"text":"values of non-IAB strings (for example ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/ccpaOptIn"},{"type":"text","text":" and "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/gdprConsentGiven","type":"reference","isActive":true},{"text":").","type":"text"}]},{"inlineContent":[{"text":"Returns an empty dictionary if no consent adapter module is available.","type":"text"}],"type":"paragraph"}]}],"sections":[],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/consents":{"title":"consents","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/consents","type":"topic","required":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"consents","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","text":"ConsentKey","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea","kind":"typeIdentifier","text":"ConsentValue"},{"kind":"text","text":"]"}],"role":"symbol","abstract":[{"type":"text","text":"Current user consent info as determined by the CMP."}],"navigatorTitle":[{"text":"consents","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentValues":{"url":"\/documentation\/chartboostcoresdk\/consentvalues","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentValues"}],"navigatorTitle":[{"text":"ConsentValues","kind":"identifier"}],"type":"topic","title":"ConsentValues","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A namespace for Core’s predefined "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValue","isActive":true,"type":"reference"},{"text":" constants.","type":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKeys":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentKeys"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentkeys","title":"ConsentKeys","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys","abstract":[{"text":"A namespace for Core’s predefined ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","isActive":true,"type":"reference"},{"text":" constants.","type":"text"}],"navigatorTitle":[{"text":"ConsentKeys","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKeys/gdprConsentGiven":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"gdprConsentGiven"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConsentKey","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"}],"navigatorTitle":[{"kind":"identifier","text":"gdprConsentGiven"}],"url":"\/documentation\/chartboostcoresdk\/consentkeys\/gdprconsentgiven","role":"symbol","abstract":[{"text":"GDPR consent given key.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Possible values are: "},{"type":"codeVoice","code":"ConsentValue\/denied"},{"text":", ","type":"text"},{"code":"ConsentValue\/granted","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"ConsentValue\/doesNotApply"},{"type":"text","text":"."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/gdprConsentGiven","title":"gdprConsentGiven"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform","kind":"symbol","navigatorTitle":[{"text":"ConsentManagementPlatform","kind":"identifier"}],"title":"ConsentManagementPlatform","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform","abstract":[{"type":"text","text":"Chartboost Core’s CMP in charge of handling user consent management."},{"type":"text","text":" "},{"type":"text","text":"Chartboost Core defines a unified API for publishers to request and query user consent,"},{"type":"text","text":" "},{"text":"and relies on a 3rd-party CMP SDK to provide the CMP functionality.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsentManagementPlatform","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKey":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsentKey","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentkey","title":"ConsentKey","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","abstract":[{"text":"A key in a Core consents dictionary.","type":"text"}],"navigatorTitle":[{"text":"ConsentKey","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentValue":{"title":"ConsentValue","abstract":[{"type":"text","text":"A value in a Core consents dictionary."}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValue","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentValue"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentvalue","navigatorTitle":[{"text":"ConsentValue","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKeys/ccpaOptIn":{"url":"\/documentation\/chartboostcoresdk\/consentkeys\/ccpaoptin","kind":"symbol","type":"topic","title":"ccpaOptIn","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/ccpaOptIn","navigatorTitle":[{"kind":"identifier","text":"ccpaOptIn"}],"abstract":[{"type":"text","text":"CCPA opt-in key."},{"type":"text","text":" "},{"type":"text","text":"Possible values are: "},{"type":"codeVoice","code":"ConsentValue\/denied"},{"text":", ","type":"text"},{"type":"codeVoice","code":"ConsentValue\/granted"},{"type":"text","text":", "},{"code":"ConsentValue\/doesNotApply","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"ccpaOptIn","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConsentKey","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"consents","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"consents"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>"},{"text":" * ","kind":"text"},{"text":"consents","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"consents","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1consents\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1consents\/fragments","value":[{"kind":"identifier","text":"consents"}],"op":"replace"},{"value":"CBCConsentValues","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues\/title"},{"value":[{"kind":"identifier","text":"CBCConsentValues"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys\/title","op":"replace","value":"CBCConsentKeys"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys\/fragments","op":"replace","value":[{"text":"CBCConsentKeys","kind":"identifier"}]},{"value":"gdprConsentGiven","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1gdprConsentGiven\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1gdprConsentGiven\/fragments","op":"replace","value":[{"kind":"identifier","text":"gdprConsentGiven"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/title","value":"CBCConsentManagementPlatform","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"CBCConsentManagementPlatform"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/fragments"},{"value":"ccpaOptIn","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1ccpaOptIn\/title"},{"value":[{"text":"ccpaOptIn","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1ccpaOptIn\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}