{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform"]]},"sections":[],"abstract":[{"type":"text","text":"Informs the CMP that the user has denied consent."},{"type":"text","text":" "},{"type":"text","text":"This method should be used only when a custom consent dialog is presented to the user, thereby making the publisher"},{"type":"text","text":" "},{"text":"responsible for the UI-side of collecting consent. In most cases","type":"text"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:completion:)"},{"type":"text","text":" should be used instead."},{"text":" ","type":"text"},{"type":"text","text":"If the CMP does not support custom consent dialogs or the operation fails for any other reason, the completion"},{"text":" ","type":"text"},{"text":"handler is executed with a ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":" parameter."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"denyConsent","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"source"},{"text":": ","kind":"text"},{"text":"ConsentSource","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentSource","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"succeeded","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The source of the new consent. See the ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource","type":"reference","isActive":true},{"text":" documentation for more info.","type":"text"}]}],"name":"source"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Handler called to indicate if the operation went through successfully or not."}]}]}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"If no consent adapter module is available this method does nothing."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"title":"denyConsent(source:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"denyConsent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConsentSource","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentSource"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"succeeded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"denyConsentWithSource:completion:"}],"modules":[{"name":"ChartboostCoreSDK"}],"required":true,"externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentManagementPlatform(im)denyConsentWithSource:completion:"},"variants":[{"paths":["\/documentation\/chartboostcoresdk\/consentmanagementplatform\/denyconsent(source:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostcoresdk\/consentmanagementplatform\/denyconsent(source:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/denyConsent(source:completion:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentSource":{"title":"ConsentSource","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsentSource"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentsource","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource","role":"symbol","type":"topic","navigatorTitle":[{"text":"ConsentSource","kind":"identifier"}],"abstract":[{"type":"text","text":"The source of a consent change."}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentManagementPlatform"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform","role":"symbol","abstract":[{"type":"text","text":"Chartboost Core’s CMP in charge of handling user consent management."},{"type":"text","text":" "},{"type":"text","text":"Chartboost Core defines a unified API for publishers to request and query user consent,"},{"type":"text","text":" "},{"type":"text","text":"and relies on a 3rd-party CMP SDK to provide the CMP functionality."}],"title":"ConsentManagementPlatform","kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform","navigatorTitle":[{"kind":"identifier","text":"ConsentManagementPlatform"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/showConsentDialog(_:from:completion:)":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showConsentDialog","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentDialogType","text":"ConsentDialogType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"succeeded","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"showConsentDialog:from:completion:"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Instructs the CMP to present a consent dialog to the user for the purpose of collecting consent.","type":"text"}],"title":"showConsentDialog(_:from:completion:)","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:completion:)","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/showconsentdialog(_:from:completion:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/denyConsent(source:completion:)":{"kind":"symbol","navigatorTitle":[{"text":"denyConsentWithSource:completion:","kind":"identifier"}],"abstract":[{"text":"Informs the CMP that the user has denied consent.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This method should be used only when a custom consent dialog is presented to the user, thereby making the publisher"},{"type":"text","text":" "},{"text":"responsible for the UI-side of collecting consent. In most cases","type":"text"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:completion:)"},{"text":" should be used instead.","type":"text"},{"text":" ","type":"text"},{"text":"If the CMP does not support custom consent dialogs or the operation fails for any other reason, the completion","type":"text"},{"type":"text","text":" "},{"text":"handler is executed with a ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":" parameter."}],"title":"denyConsent(source:completion:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"denyConsent","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"source"},{"text":": ","kind":"text"},{"text":"ConsentSource","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentSource","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"succeeded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/denyconsent(source:completion:)","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/denyConsent(source:completion:)","type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"denyConsentWithSource:completion:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"denyConsentWithSource:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"denyConsentWithSource:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentSource","text":"CBCConsentSource","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"source"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"source","content":[{"type":"paragraph","inlineContent":[{"text":"The source of the new consent. See the ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource","isActive":true,"type":"reference"},{"text":" documentation for more info.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Handler called to indicate if the operation went through successfully or not."}]}],"name":"completion"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource\/title","op":"replace","value":"CBCConsentSource"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBCConsentSource"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource\/navigatorTitle","value":[{"text":"CBCConsentSource","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/title","op":"replace","value":"CBCConsentManagementPlatform"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/fragments","value":[{"kind":"identifier","text":"CBCConsentManagementPlatform"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/navigatorTitle","op":"replace","value":[{"text":"CBCConsentManagementPlatform","kind":"identifier"}]},{"op":"replace","value":"showConsentDialog:from:completion:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1showConsentDialog(_:from:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1showConsentDialog(_:from:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"showConsentDialog:from:completion:","kind":"identifier"}]},{"value":"denyConsentWithSource:completion:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1denyConsent(source:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1denyConsent(source:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"denyConsentWithSource:completion:","kind":"identifier"}],"op":"replace"}]}]}