{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:completion:)"},"abstract":[{"type":"text","text":"Instructs the CMP to present a consent dialog to the user for the purpose of collecting consent."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showConsentDialog"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"type","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConsentDialogType","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentDialogType","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentDialogType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"succeeded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"type","content":[{"type":"paragraph","inlineContent":[{"text":"The type of consent dialog to present. See the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentDialogType"},{"type":"text","text":" documentation for more info."},{"type":"text","text":" "},{"text":"If the CMP does not support a given type, it should default to whatever type it does support.","type":"text"}]}]},{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"text":"The view controller to present the consent dialog from.","type":"text"}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"This handler is called to indicate whether the consent dialog was successfully presented or not."},{"text":" ","type":"text"},{"type":"text","text":"Note that this is called at the moment the dialog is presented, "},{"type":"strong","inlineContent":[{"text":"not when it is dismissed","type":"text"}]},{"text":".","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If no consent adapter module is available this method does nothing."}]}]}],"variants":[{"paths":["\/documentation\/chartboostcoresdk\/consentmanagementplatform\/showconsentdialog(_:from:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostcoresdk\/consentmanagementplatform\/showconsentdialog(_:from:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"showConsentDialog","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentDialogType","text":"ConsentDialogType"},{"kind":"text","text":", "},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"succeeded"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"modules":[{"name":"ChartboostCoreSDK"}],"title":"showConsentDialog(_:from:completion:)","externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentManagementPlatform(im)showConsentDialog:from:completion:","symbolKind":"method","navigatorTitle":[{"text":"showConsentDialog:from:completion:","kind":"identifier"}],"required":true,"roleHeading":"Instance Method","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform"]]},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform","kind":"symbol","navigatorTitle":[{"text":"ConsentManagementPlatform","kind":"identifier"}],"title":"ConsentManagementPlatform","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform","abstract":[{"type":"text","text":"Chartboost Core’s CMP in charge of handling user consent management."},{"type":"text","text":" "},{"type":"text","text":"Chartboost Core defines a unified API for publishers to request and query user consent,"},{"type":"text","text":" "},{"text":"and relies on a 3rd-party CMP SDK to provide the CMP functionality.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsentManagementPlatform","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/showConsentDialog(_:from:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showConsentDialog"},{"text":"(","kind":"text"},{"text":"ConsentDialogType","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentDialogType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"succeeded","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"type":"topic","title":"showConsentDialog(_:from:completion:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:completion:)","required":true,"navigatorTitle":[{"text":"showConsentDialog:from:completion:","kind":"identifier"}],"abstract":[{"text":"Instructs the CMP to present a consent dialog to the user for the purpose of collecting consent.","type":"text"}],"url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/showconsentdialog(_:from:completion:)","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentDialogType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ConsentDialogType","kind":"identifier"}],"type":"topic","title":"ConsentDialogType","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentDialogType","navigatorTitle":[{"kind":"identifier","text":"ConsentDialogType"}],"abstract":[{"text":"The type of consent dialog to be presented to the user.","type":"text"}],"url":"\/documentation\/chartboostcoresdk\/consentdialogtype","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showConsentDialog:from:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showConsentDialog:from:completion:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"showConsentDialog:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentDialogType","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentDialogType","text":"CBCConsentDialogType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"text":" ","kind":"text"},{"kind":"identifier","text":"from:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#b)","text":"void (^)(_Bool)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/title","value":"CBCConsentManagementPlatform","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/fragments","value":[{"text":"CBCConsentManagementPlatform","kind":"identifier"}]},{"value":"showConsentDialog:from:completion:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1showConsentDialog(_:from:completion:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showConsentDialog:from:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1showConsentDialog(_:from:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentDialogType\/title","value":"CBCConsentDialogType"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentDialogType\/fragments","value":[{"text":"CBCConsentDialogType","kind":"identifier"}],"op":"replace"}]}]}