{"kind":"symbol","metadata":{"roleHeading":"Instance Method","symbolKind":"method","title":"showConsentDialog(_:from:)","externalID":"s:17ChartboostCoreSDK25ConsentManagementPlatformPAAE04showD6Dialog_4fromyAA0dH4TypeO_So16UIViewControllerCtF","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showConsentDialog"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentDialogType","text":"ConsentDialogType"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"ChartboostCoreSDK"}],"role":"symbol","extendedModule":"ChartboostCoreSDK"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showConsentDialog","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentDialogType","text":"ConsentDialogType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentDialogType"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":" "},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The type of consent dialog to present. See the "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentDialogType","type":"reference","isActive":true},{"type":"text","text":" documentation for more info."},{"type":"text","text":" "},{"type":"text","text":"If the CMP does not support a given type, it should default to whatever type it does support."}],"type":"paragraph"}],"name":"type"},{"content":[{"inlineContent":[{"text":"The view controller to present the consent dialog from.","type":"text"}],"type":"paragraph"}],"name":"viewController"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform"]]},"sections":[],"abstract":[{"text":"Instructs the CMP to present a consent dialog to the user for the purpose of collecting consent.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/consentmanagementplatform\/showconsentdialog(_:from:)"]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform","kind":"symbol","navigatorTitle":[{"text":"ConsentManagementPlatform","kind":"identifier"}],"title":"ConsentManagementPlatform","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform","abstract":[{"type":"text","text":"Chartboost Core’s CMP in charge of handling user consent management."},{"type":"text","text":" "},{"type":"text","text":"Chartboost Core defines a unified API for publishers to request and query user consent,"},{"type":"text","text":" "},{"text":"and relies on a 3rd-party CMP SDK to provide the CMP functionality.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsentManagementPlatform","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/showConsentDialog(_:from:)":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:)","kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/showconsentdialog(_:from:)","type":"topic","abstract":[{"text":"Instructs the CMP to present a consent dialog to the user for the purpose of collecting consent.","type":"text"}],"title":"showConsentDialog(_:from:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"showConsentDialog","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentDialogType","text":"ConsentDialogType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentDialogType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ConsentDialogType","kind":"identifier"}],"type":"topic","title":"ConsentDialogType","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentDialogType","navigatorTitle":[{"kind":"identifier","text":"ConsentDialogType"}],"abstract":[{"text":"The type of consent dialog to be presented to the user.","type":"text"}],"url":"\/documentation\/chartboostcoresdk\/consentdialogtype","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"CBCConsentManagementPlatform","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/title"},{"value":[{"text":"CBCConsentManagementPlatform","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/fragments","op":"replace"},{"value":"CBCConsentDialogType","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentDialogType\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentDialogType\/fragments","value":[{"kind":"identifier","text":"CBCConsentDialogType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}