{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"detachHandler","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"handler","kind":"internalParam"},{"kind":"text","text":": "},{"text":"LogHandler","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCLogHandler","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogHandler"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A custom class that conforms to the ","type":"text"},{"type":"codeVoice","code":"LogHandler"},{"type":"text","text":" protocol."}]}],"name":"handler"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCLogger(im)detachHandler:","modules":[{"name":"ChartboostCoreSDK"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detachHandler"},{"kind":"text","text":"("},{"text":"LogHandler","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCLogHandler","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","title":"detachHandler(_:)","navigatorTitle":[{"kind":"identifier","text":"detachHandler:"}]},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Logger\/detachHandler(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Detach a custom logger handler from the logging system.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Logger"]]},"variants":[{"paths":["\/documentation\/chartboostcoresdk\/logger\/detachhandler(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostcoresdk\/logger\/detachhandler(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Logger/detachHandler(_:)":{"navigatorTitle":[{"kind":"identifier","text":"detachHandler:"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Logger\/detachHandler(_:)","kind":"symbol","url":"\/documentation\/chartboostcoresdk\/logger\/detachhandler(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detachHandler","kind":"identifier"},{"kind":"text","text":"("},{"text":"LogHandler","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCLogHandler"},{"text":")","kind":"text"}],"abstract":[{"text":"Detach a custom logger handler from the logging system.","type":"text"}],"title":"detachHandler(_:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Logger":{"navigatorTitle":[{"text":"Logger","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Logger","url":"\/documentation\/chartboostcoresdk\/logger","abstract":[{"type":"text","text":"A unified logging subystem which receives and forwards logs to handlers that can be attached to it."}],"title":"Logger","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogHandler":{"title":"LogHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogHandler"}],"abstract":[{"text":"The protocol for custom log handlers for the unified logging subsystem.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogHandler","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LogHandler"}],"url":"\/documentation\/chartboostcoresdk\/loghandler"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"detachHandler:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"detachHandler:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"detachHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<CBCLogHandler>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ChartboostCoreSDK@objc(pl)CBCLogHandler"},{"kind":"text","text":" *) "},{"text":"handler","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Logger~1detachHandler(_:)\/title","op":"replace","value":"detachHandler:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Logger~1detachHandler(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"detachHandler:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Logger\/title","value":"CBCLogger"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Logger\/fragments","value":[{"text":"CBCLogger","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogHandler\/title","value":"CBCLogHandler","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogHandler\/fragments","value":[{"text":"CBCLogHandler","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}