{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Logger"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Log a message at the indicated severty level."}],"variants":[{"paths":["\/documentation\/chartboostcoresdk\/logger\/log(_:level:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostcoresdk\/logger\/log(_:level:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"log","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"message"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"level"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel","kind":"typeIdentifier","text":"LogLevel","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCLogLevel"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The logged message."}],"type":"paragraph"}],"name":"message"},{"name":"level","content":[{"inlineContent":[{"text":"The severity level.","type":"text"}],"type":"paragraph"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Logger\/log(_:level:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"ChartboostCoreSDK"}],"navigatorTitle":[{"text":"log:level:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"log"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"level","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCLogLevel","text":"LogLevel"},{"kind":"text","text":")"}],"role":"symbol","title":"log(_:level:)","symbolKind":"method","externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCLogger(im)log:level:","roleHeading":"Instance Method"},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Logger":{"title":"Logger","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Logger","role":"symbol","abstract":[{"text":"A unified logging subystem which receives and forwards logs to handlers that can be attached to it.","type":"text"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/logger","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"navigatorTitle":[{"text":"Logger","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel":{"navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"role":"symbol","title":"LogLevel","url":"\/documentation\/chartboostcoresdk\/loglevel","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogLevel","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel","abstract":[{"text":"Log severity levels for the unified logging subsystem.","type":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Logger/log(_:level:)":{"url":"\/documentation\/chartboostcoresdk\/logger\/log(_:level:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"log:level:"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Logger\/log(_:level:)","type":"topic","abstract":[{"text":"Log a message at the indicated severty level.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"log","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"level","kind":"externalParam"},{"kind":"text","text":": "},{"text":"LogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCLogLevel"},{"text":")","kind":"text"}],"title":"log(_:level:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"log:level:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"log:level:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"log:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"message","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"level:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"CBCLogLevel","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCLogLevel","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel"},{"text":") ","kind":"text"},{"text":"level","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The logged message."}]}],"name":"message"},{"name":"level","content":[{"inlineContent":[{"text":"The severity level.","type":"text"}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Logger\/title","value":"CBCLogger","op":"replace"},{"op":"replace","value":[{"text":"CBCLogger","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Logger\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Logger\/navigatorTitle","value":[{"text":"CBCLogger","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel\/title","op":"replace","value":"CBCLogLevel"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel\/fragments","op":"replace","value":[{"text":"CBCLogLevel","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"CBCLogLevel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Logger~1log(_:level:)\/title","value":"log:level:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Logger~1log(_:level:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"log:level:"}]}]}]}