{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/module\/init(credentials:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/module\/init(credentials:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module"]]},"abstract":[{"text":"The designated initializer for the module.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The Chartboost Core SDK will invoke this initializer when instantiating modules defined on"},{"type":"text","text":" "},{"type":"text","text":"the dashboard through reflection."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"credentials"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A dictionary containing all the information required to initialize"},{"type":"text","text":" "},{"type":"text","text":"this module, as defined on the Chartboost Core’s dashboard."}]}],"name":"credentials"}]},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"aside","name":"Note","style":"note","content":[{"inlineContent":[{"type":"text","text":"Modules should not perform costly operations on this initializer."},{"text":" ","type":"text"},{"text":"Chartboost Core SDK may instantiate and discard several instances of the same module.","type":"text"},{"text":" ","type":"text"},{"text":"Chartboost Core SDK keeps strong references to modules that are successfully initialized.","type":"text"}],"type":"paragraph"}]}],"kind":"content"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module\/init(credentials:)","interfaceLanguage":"swift"},"metadata":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"initWithCredentials:"}],"externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCModule(im)initWithCredentials:","role":"symbol","roleHeading":"Initializer","title":"init(credentials:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"credentials"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}],"symbolKind":"init","modules":[{"name":"ChartboostCoreSDK"}]},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Module":{"role":"symbol","type":"topic","title":"Module","abstract":[{"text":"The protocol to which all Chartboost Core modules must conform to.","type":"text"}],"url":"\/documentation\/chartboostcoresdk\/module","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Module"}],"navigatorTitle":[{"text":"Module","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Module/init(credentials:)":{"abstract":[{"type":"text","text":"The designated initializer for the module."},{"type":"text","text":" "},{"type":"text","text":"The Chartboost Core SDK will invoke this initializer when instantiating modules defined on"},{"type":"text","text":" "},{"type":"text","text":"the dashboard through reflection."}],"title":"init(credentials:)","url":"\/documentation\/chartboostcoresdk\/module\/init(credentials:)","role":"symbol","kind":"symbol","required":true,"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"credentials","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}],"navigatorTitle":[{"text":"initWithCredentials:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module\/init(credentials:)","type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"initWithCredentials:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"initWithCredentials:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithCredentials:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id>"},{"text":" *) ","kind":"text"},{"text":"credentials","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"credentials","content":[{"inlineContent":[{"text":"A dictionary containing all the information required to initialize","type":"text"},{"type":"text","text":" "},{"type":"text","text":"this module, as defined on the Chartboost Core’s dashboard."}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/title","value":"CBCModule"},{"op":"replace","value":[{"kind":"identifier","text":"CBCModule"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/fragments"},{"value":[{"kind":"identifier","text":"CBCModule"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/navigatorTitle","op":"replace"},{"value":"initWithCredentials:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module~1init(credentials:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module~1init(credentials:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCredentials:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}