{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module\/initialize(configuration:completion:)"},"abstract":[{"type":"text","text":"Sets up the module to make it ready to be used."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(initializeWithConfiguration:completion:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ModuleConfiguration","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCModuleConfiguration","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"inlineContent":[{"text":"A ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleConfiguration","type":"reference"},{"text":" for configuring the module.","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"A completion handler to be executed when the module is done initializing.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"An error should be passed if the initialization failed, whereas "},{"type":"codeVoice","code":"nil"},{"text":" should be passed if it succeeded.","type":"text"}]}]}]}],"variants":[{"paths":["\/documentation\/chartboostcoresdk\/module\/initialize(configuration:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostcoresdk\/module\/initialize(configuration:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initializeWithConfiguration:completion:"}],"externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCModule(im)initializeWithConfiguration:completion:","modules":[{"name":"ChartboostCoreSDK"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"text":"ModuleConfiguration","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCModuleConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"role":"symbol","title":"initialize(configuration:completion:)","roleHeading":"Instance Method"},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleConfiguration":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleConfiguration","navigatorTitle":[{"text":"ModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/moduleconfiguration","kind":"symbol","title":"ModuleConfiguration","abstract":[{"type":"text","text":"Configuration with parameters needed by "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module","type":"reference"},{"text":" on initialization.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ModuleConfiguration","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Module":{"role":"symbol","type":"topic","title":"Module","abstract":[{"text":"The protocol to which all Chartboost Core modules must conform to.","type":"text"}],"url":"\/documentation\/chartboostcoresdk\/module","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Module"}],"navigatorTitle":[{"text":"Module","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Module/initialize(configuration:completion:)":{"required":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module\/initialize(configuration:completion:)","abstract":[{"type":"text","text":"Sets up the module to make it ready to be used."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCModuleConfiguration","kind":"typeIdentifier","text":"ModuleConfiguration"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initializeWithConfiguration:completion:","kind":"identifier"}],"kind":"symbol","title":"initialize(configuration:completion:)","url":"\/documentation\/chartboostcoresdk\/module\/initialize(configuration:completion:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initializeWithConfiguration:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initializeWithConfiguration:completion:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"initializeWithConfiguration:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CBCModuleConfiguration","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCModuleConfiguration","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"A ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleConfiguration","isActive":true,"type":"reference"},{"text":" for configuring the module.","type":"text"}],"type":"paragraph"}],"name":"configuration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A completion handler to be executed when the module is done initializing."},{"type":"text","text":" "},{"type":"text","text":"An error should be passed if the initialization failed, whereas "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" should be passed if it succeeded."}]}],"name":"completion"}]}},{"value":"CBCModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"CBCModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleConfiguration\/navigatorTitle","value":[{"text":"CBCModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/title","value":"CBCModule","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/fragments","value":[{"kind":"identifier","text":"CBCModule"}],"op":"replace"},{"op":"replace","value":[{"text":"CBCModule","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module~1initialize(configuration:completion:)\/title","value":"initializeWithConfiguration:completion:"},{"value":[{"kind":"text","text":"- "},{"text":"initializeWithConfiguration:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module~1initialize(configuration:completion:)\/fragments","op":"replace"}]}]}