{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/consentadapterdelegate\/onconsentchange(key:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/consentadapterdelegate\/onconsentchange(key:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapterDelegate"]]},"abstract":[{"text":"Called whenever the ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/consents","isActive":true},{"text":" value changed.","type":"text"}],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentAdapterDelegate(im)onConsentChangeWithKey:","symbolKind":"method","title":"onConsentChange(key:)","navigatorTitle":[{"kind":"identifier","text":"onConsentChangeWithKey:"}],"modules":[{"name":"ChartboostCoreSDK"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConsentChange"},{"text":"(","kind":"text"},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ConsentKey","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapterDelegate\/onConsentChange(key:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onConsentChange","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"text":"ConsentKey","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The key that changed."}],"type":"paragraph"}],"name":"key"}],"kind":"parameters"}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapterDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ConsentAdapterDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapterDelegate","abstract":[{"text":"The delegate of a ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","isActive":true,"type":"reference"},{"text":" module.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It should get notified whenever any change happens in the CMP consent."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConsentAdapterDelegate"}],"url":"\/documentation\/chartboostcoresdk\/consentadapterdelegate","title":"ConsentAdapterDelegate"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter/consents":{"type":"topic","required":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/consents","abstract":[{"text":"Current user consent info as determined by the CMP.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"consents","kind":"identifier"},{"kind":"text","text":": ["},{"text":"ConsentKey","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea","text":"ConsentValue","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"consents"}],"url":"\/documentation\/chartboostcoresdk\/consentadapter\/consents","title":"consents"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapterDelegate/onConsentChange(key:)":{"type":"topic","required":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapterDelegate\/onConsentChange(key:)","abstract":[{"text":"Called whenever the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/consents","type":"reference"},{"text":" value changed.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConsentChange"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"key"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","text":"ConsentKey"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onConsentChangeWithKey:"}],"url":"\/documentation\/chartboostcoresdk\/consentadapterdelegate\/onconsentchange(key:)","title":"onConsentChange(key:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKey":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsentKey","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentkey","title":"ConsentKey","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","abstract":[{"text":"A key in a Core consents dictionary.","type":"text"}],"navigatorTitle":[{"text":"ConsentKey","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ConsentAdapter","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","abstract":[{"text":"The protocol to which a CMP adapter module must conform to.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ConsentAdapter","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/consentadapter","title":"ConsentAdapter"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"onConsentChangeWithKey:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConsentChangeWithKey:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onConsentChangeWithKey:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"key","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapterDelegate\/title","op":"replace","value":"CBCConsentAdapterDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapterDelegate\/fragments","value":[{"kind":"identifier","text":"CBCConsentAdapterDelegate"}]},{"op":"replace","value":"consents","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1consents\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1consents\/fragments","value":[{"text":"consents","kind":"identifier"}],"op":"replace"},{"value":"onConsentChangeWithKey:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapterDelegate~1onConsentChange(key:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapterDelegate~1onConsentChange(key:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onConsentChangeWithKey:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/title","op":"replace","value":"CBCConsentAdapter"},{"op":"replace","value":[{"kind":"identifier","text":"CBCConsentAdapter"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}