{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/networkconnectiontype\/cellular3g"]},{"paths":["\/documentation\/chartboostcoresdk\/networkconnectiontype\/cellular3g"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType"]]},"metadata":{"modules":[{"name":"ChartboostCoreSDK"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cellular3G","kind":"identifier"}],"externalID":"c:@M@ChartboostCoreSDK@E@CBCNetworkConnectionType@CBCNetworkConnectionTypeCellular3G","navigatorTitle":[{"kind":"identifier","text":"CBCNetworkConnectionTypeCellular3G"}],"role":"symbol","symbolKind":"case","title":"NetworkConnectionType.cellular3G"},"abstract":[{"text":"3G cellular network connection.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellular3G","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellular3G"}]}]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType":{"title":"NetworkConnectionType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkConnectionType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType","role":"symbol","navigatorTitle":[{"text":"NetworkConnectionType","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/networkconnectiontype","abstract":[{"type":"text","text":"Network connection type."}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType/cellular3G":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellular3G","url":"\/documentation\/chartboostcoresdk\/networkconnectiontype\/cellular3g","title":"NetworkConnectionType.cellular3G","navigatorTitle":[{"kind":"identifier","text":"CBCNetworkConnectionTypeCellular3G"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellular3G"}],"abstract":[{"type":"text","text":"3G cellular network connection."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"CBCNetworkConnectionTypeCellular3G","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"CBCNetworkConnectionTypeCellular3G","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"CBCNetworkConnectionTypeCellular3G"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType\/title","value":"CBCNetworkConnectionType","op":"replace"},{"value":[{"text":"CBCNetworkConnectionType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType\/navigatorTitle","value":[{"text":"CBCNetworkConnectionType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1cellular3G\/title","op":"replace","value":"CBCNetworkConnectionTypeCellular3G"},{"value":[{"kind":"identifier","text":"CBCNetworkConnectionTypeCellular3G"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1cellular3G\/fragments","op":"replace"}]}]}