{"metadata":{"roleHeading":"Case","externalID":"c:@M@ChartboostCoreSDK@E@CBCNetworkConnectionType@CBCNetworkConnectionTypeCellularUnknown","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cellularUnknown"}],"navigatorTitle":[{"text":"CBCNetworkConnectionTypeCellularUnknown","kind":"identifier"}],"title":"NetworkConnectionType.cellularUnknown","modules":[{"name":"ChartboostCoreSDK"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Cellular network connection of unknown generation.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellularUnknown"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/chartboostcoresdk\/networkconnectiontype\/cellularunknown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostcoresdk\/networkconnectiontype\/cellularunknown"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cellularUnknown","kind":"identifier"}]}]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType":{"navigatorTitle":[{"text":"NetworkConnectionType","kind":"identifier"}],"title":"NetworkConnectionType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NetworkConnectionType"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType","url":"\/documentation\/chartboostcoresdk\/networkconnectiontype","abstract":[{"type":"text","text":"Network connection type."}],"role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType/cellularUnknown":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cellularUnknown"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellularUnknown","kind":"symbol","abstract":[{"type":"text","text":"Cellular network connection of unknown generation."}],"title":"NetworkConnectionType.cellularUnknown","type":"topic","url":"\/documentation\/chartboostcoresdk\/networkconnectiontype\/cellularunknown","navigatorTitle":[{"text":"CBCNetworkConnectionTypeCellularUnknown","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"CBCNetworkConnectionTypeCellularUnknown","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBCNetworkConnectionTypeCellularUnknown"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"CBCNetworkConnectionTypeCellularUnknown","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType\/title","op":"replace","value":"CBCNetworkConnectionType"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType\/fragments","value":[{"kind":"identifier","text":"CBCNetworkConnectionType"}],"op":"replace"},{"value":"CBCNetworkConnectionTypeCellularUnknown","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1cellularUnknown\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1cellularUnknown\/fragments","value":[{"kind":"identifier","text":"CBCNetworkConnectionTypeCellularUnknown"}],"op":"replace"}]}]}