{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType"]]},"metadata":{"symbolKind":"case","modules":[{"name":"ChartboostCoreSDK"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"CBCNetworkConnectionTypeCellular5G"}],"title":"NetworkConnectionType.cellular5G","role":"symbol","externalID":"c:@M@ChartboostCoreSDK@E@CBCNetworkConnectionType@CBCNetworkConnectionTypeCellular5G","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellular5G"}]},"abstract":[{"type":"text","text":"5G cellular network connection."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellular5G"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellular5G"},"kind":"symbol","variants":[{"paths":["\/documentation\/chartboostcoresdk\/networkconnectiontype\/cellular5g"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/networkconnectiontype\/cellular5g"]}],"sections":[],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType":{"navigatorTitle":[{"text":"NetworkConnectionType","kind":"identifier"}],"title":"NetworkConnectionType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NetworkConnectionType"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType","url":"\/documentation\/chartboostcoresdk\/networkconnectiontype","abstract":[{"type":"text","text":"Network connection type."}],"role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType/cellular5G":{"navigatorTitle":[{"text":"CBCNetworkConnectionTypeCellular5G","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/networkconnectiontype\/cellular5g","type":"topic","role":"symbol","abstract":[{"text":"5G cellular network connection.","type":"text"}],"title":"NetworkConnectionType.cellular5G","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellular5G"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellular5G","kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"CBCNetworkConnectionTypeCellular5G"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CBCNetworkConnectionTypeCellular5G"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"CBCNetworkConnectionTypeCellular5G"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType\/title","op":"replace","value":"CBCNetworkConnectionType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType\/fragments","value":[{"kind":"identifier","text":"CBCNetworkConnectionType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1cellular5G\/title","value":"CBCNetworkConnectionTypeCellular5G"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1cellular5G\/fragments","value":[{"text":"CBCNetworkConnectionTypeCellular5G","kind":"identifier"}]}]}]}