{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"symbolKind":"case","externalID":"c:@M@ChartboostCoreSDK@E@CBCNetworkConnectionType@CBCNetworkConnectionTypeUnknown","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"title":"NetworkConnectionType.unknown","modules":[{"name":"ChartboostCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CBCNetworkConnectionTypeUnknown"}],"role":"symbol"},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/unknown","interfaceLanguage":"swift"},"abstract":[{"text":"Unknown connection type.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/networkconnectiontype\/unknown"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/networkconnectiontype\/unknown"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType/unknown":{"navigatorTitle":[{"text":"CBCNetworkConnectionTypeUnknown","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/unknown","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/networkconnectiontype\/unknown","abstract":[{"text":"Unknown connection type.","type":"text"}],"title":"NetworkConnectionType.unknown"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType":{"navigatorTitle":[{"text":"NetworkConnectionType","kind":"identifier"}],"title":"NetworkConnectionType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NetworkConnectionType"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType","url":"\/documentation\/chartboostcoresdk\/networkconnectiontype","abstract":[{"type":"text","text":"Network connection type."}],"role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"CBCNetworkConnectionTypeUnknown","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"CBCNetworkConnectionTypeUnknown"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"CBCNetworkConnectionTypeUnknown"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"CBCNetworkConnectionTypeUnknown","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1unknown\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1unknown\/fragments","value":[{"kind":"identifier","text":"CBCNetworkConnectionTypeUnknown"}],"op":"replace"},{"value":"CBCNetworkConnectionType","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType\/title","op":"replace"},{"value":[{"text":"CBCNetworkConnectionType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType\/fragments","op":"replace"}]}]}