{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/wired"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType"]]},"metadata":{"title":"NetworkConnectionType.wired","navigatorTitle":[{"kind":"identifier","text":"CBCNetworkConnectionTypeWired"}],"externalID":"c:@M@ChartboostCoreSDK@E@CBCNetworkConnectionType@CBCNetworkConnectionTypeWired","modules":[{"name":"ChartboostCoreSDK"}],"role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"wired","kind":"identifier"}],"symbolKind":"case"},"abstract":[{"type":"text","text":"Wired network connection."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/networkconnectiontype\/wired"]},{"paths":["\/documentation\/chartboostcoresdk\/networkconnectiontype\/wired"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"wired","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType":{"title":"NetworkConnectionType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkConnectionType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType","role":"symbol","navigatorTitle":[{"text":"NetworkConnectionType","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/networkconnectiontype","abstract":[{"type":"text","text":"Network connection type."}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType/wired":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/wired","url":"\/documentation\/chartboostcoresdk\/networkconnectiontype\/wired","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wired","kind":"identifier"}],"kind":"symbol","title":"NetworkConnectionType.wired","abstract":[{"type":"text","text":"Wired network connection."}],"role":"symbol","navigatorTitle":[{"text":"CBCNetworkConnectionTypeWired","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"CBCNetworkConnectionTypeWired","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"CBCNetworkConnectionTypeWired"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"CBCNetworkConnectionTypeWired","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"CBCNetworkConnectionType","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType\/title"},{"value":[{"text":"CBCNetworkConnectionType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBCNetworkConnectionType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1wired\/title","value":"CBCNetworkConnectionTypeWired"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1wired\/fragments","value":[{"kind":"identifier","text":"CBCNetworkConnectionTypeWired"}],"op":"replace"}]}]}