{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentDialogType\/detailed"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/consentdialogtype\/detailed"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/consentdialogtype\/detailed"]}],"kind":"symbol","abstract":[{"type":"text","text":"A dialog used to collect consent, presenting detailed information and possibly allowing"},{"type":"text","text":" "},{"type":"text","text":"for granular consent choices."}],"metadata":{"roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detailed"}],"modules":[{"name":"ChartboostCoreSDK"}],"externalID":"c:@M@ChartboostCoreSDK@E@CBCConsentDialogType@CBCConsentDialogTypeDetailed","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"CBCConsentDialogTypeDetailed"}],"title":"ConsentDialogType.detailed"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentDialogType"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"detailed","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentDialogType/detailed":{"abstract":[{"text":"A dialog used to collect consent, presenting detailed information and possibly allowing","type":"text"},{"type":"text","text":" "},{"text":"for granular consent choices.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detailed"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBCConsentDialogTypeDetailed"}],"type":"topic","title":"ConsentDialogType.detailed","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentDialogType\/detailed","url":"\/documentation\/chartboostcoresdk\/consentdialogtype\/detailed"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentDialogType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ConsentDialogType","kind":"identifier"}],"type":"topic","title":"ConsentDialogType","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentDialogType","navigatorTitle":[{"kind":"identifier","text":"ConsentDialogType"}],"abstract":[{"text":"The type of consent dialog to be presented to the user.","type":"text"}],"url":"\/documentation\/chartboostcoresdk\/consentdialogtype","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"CBCConsentDialogTypeDetailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"CBCConsentDialogTypeDetailed","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"CBCConsentDialogTypeDetailed","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentDialogType~1detailed\/title","op":"replace","value":"CBCConsentDialogTypeDetailed"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentDialogType~1detailed\/fragments","op":"replace","value":[{"text":"CBCConsentDialogTypeDetailed","kind":"identifier"}]},{"value":"CBCConsentDialogType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentDialogType\/title"},{"value":[{"kind":"identifier","text":"CBCConsentDialogType"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentDialogType\/fragments","op":"replace"}]}]}