{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/attachLogHandler(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/chartboostcore\/attachloghandler(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/chartboostcore\/attachloghandler(_:)"]}],"kind":"symbol","abstract":[{"text":"Attach a custom logger handler to the logging system.","type":"text"}],"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"attachLogHandler","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCLogHandler","text":"LogHandler"},{"text":")","kind":"text"}],"roleHeading":"Type Method","navigatorTitle":[{"text":"attachLogHandler:","kind":"identifier"}],"title":"attachLogHandler(_:)","modules":[{"name":"ChartboostCoreSDK"}],"externalID":"c:@M@ChartboostCoreSDK@objc(cs)ChartboostCore(cm)attachLogHandler:"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"attachLogHandler","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"handler","kind":"internalParam"},{"kind":"text","text":": "},{"text":"LogHandler","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogHandler","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCLogHandler"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A custom class that conforms to the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogHandler"},{"text":" protocol.","type":"text"}]}],"name":"handler"}],"kind":"parameters"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore","abstract":[{"type":"text","text":"The main interface to the Chartboost Core SDK."},{"text":" ","type":"text"},{"type":"text","text":"Provides users with access to all of Core’s functionalities."}],"kind":"symbol","navigatorTitle":[{"text":"ChartboostCore","kind":"identifier"}],"title":"ChartboostCore","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChartboostCore"}],"url":"\/documentation\/chartboostcoresdk\/chartboostcore"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/attachLogHandler(_:)":{"navigatorTitle":[{"kind":"identifier","text":"attachLogHandler:"}],"title":"attachLogHandler(_:)","kind":"symbol","abstract":[{"text":"Attach a custom logger handler to the logging system.","type":"text"}],"type":"topic","url":"\/documentation\/chartboostcoresdk\/chartboostcore\/attachloghandler(_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachLogHandler"},{"text":"(","kind":"text"},{"text":"LogHandler","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCLogHandler"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/attachLogHandler(_:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogHandler":{"title":"LogHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogHandler"}],"abstract":[{"text":"The protocol for custom log handlers for the unified logging subsystem.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogHandler","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LogHandler"}],"url":"\/documentation\/chartboostcoresdk\/loghandler"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","value":"attachLogHandler:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"attachLogHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"attachLogHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<CBCLogHandler>","preciseIdentifier":"c:Qo@M@ChartboostCoreSDK@objc(pl)CBCLogHandler"},{"kind":"text","text":" *) "},{"text":"handler","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"ChartboostCore","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore\/title"},{"value":[{"text":"ChartboostCore","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1attachLogHandler(_:)\/title","op":"replace","value":"attachLogHandler:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"attachLogHandler:"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1attachLogHandler(_:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogHandler\/title","op":"replace","value":"CBCLogHandler"},{"value":[{"kind":"identifier","text":"CBCLogHandler"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogHandler\/fragments"}]}]}