{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/consent"},"kind":"symbol","metadata":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"consent"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentManagementPlatform","text":"ConsentManagementPlatform","kind":"typeIdentifier"}],"modules":[{"name":"ChartboostCoreSDK"}],"roleHeading":"Type Property","externalID":"c:@M@ChartboostCoreSDK@objc(cs)ChartboostCore(cpy)consent","title":"consent","navigatorTitle":[{"text":"consent","kind":"identifier"}],"symbolKind":"property","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"consent","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentManagementPlatform","text":"ConsentManagementPlatform","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"sections":[],"abstract":[{"type":"text","text":"The CMP in charge of handling user consent."}],"variants":[{"paths":["\/documentation\/chartboostcoresdk\/chartboostcore\/consent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostcoresdk\/chartboostcore\/consent"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore":{"navigatorTitle":[{"text":"ChartboostCore","kind":"identifier"}],"role":"symbol","title":"ChartboostCore","url":"\/documentation\/chartboostcoresdk\/chartboostcore","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChartboostCore","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore","abstract":[{"text":"The main interface to the Chartboost Core SDK.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Provides users with access to all of Core’s functionalities."}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentManagementPlatform"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform","role":"symbol","abstract":[{"type":"text","text":"Chartboost Core’s CMP in charge of handling user consent management."},{"type":"text","text":" "},{"type":"text","text":"Chartboost Core defines a unified API for publishers to request and query user consent,"},{"type":"text","text":" "},{"type":"text","text":"and relies on a 3rd-party CMP SDK to provide the CMP functionality."}],"title":"ConsentManagementPlatform","kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform","navigatorTitle":[{"kind":"identifier","text":"ConsentManagementPlatform"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/consent":{"title":"consent","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"consent"},{"text":": ","kind":"text"},{"text":"ConsentManagementPlatform","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentManagementPlatform"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/consent","url":"\/documentation\/chartboostcoresdk\/chartboostcore\/consent","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"consent","kind":"identifier"}],"abstract":[{"type":"text","text":"The CMP in charge of handling user consent."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"consent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"consent","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@ChartboostCoreSDK@objc(pl)CBCConsentManagementPlatform","kind":"typeIdentifier","text":"id<CBCConsentManagementPlatform>"},{"text":" ","kind":"text"},{"text":"consent","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ChartboostCore","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore\/title"},{"op":"replace","value":[{"text":"ChartboostCore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore\/fragments"},{"value":[{"kind":"identifier","text":"ChartboostCore"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore\/navigatorTitle"},{"value":"CBCConsentManagementPlatform","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/fragments","value":[{"text":"CBCConsentManagementPlatform","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBCConsentManagementPlatform"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1consent\/title","value":"consent"},{"value":[{"text":"consent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1consent\/fragments"}]}]}