{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detachLogHandler","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"handler","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCLogHandler","text":"LogHandler","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogHandler","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A custom class that conforms to the "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogHandler","type":"reference","isActive":true},{"type":"text","text":" protocol."}]}],"name":"handler"}],"kind":"parameters"}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/detachLogHandler(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Detach a custom logger handler from the logging system.","type":"text"}],"sections":[],"metadata":{"symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"ChartboostCoreSDK"}],"title":"detachLogHandler(_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detachLogHandler"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCLogHandler","text":"LogHandler","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"detachLogHandler:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ChartboostCoreSDK@objc(cs)ChartboostCore(cm)detachLogHandler:"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore"]]},"variants":[{"paths":["\/documentation\/chartboostcoresdk\/chartboostcore\/detachloghandler(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/chartboostcore\/detachloghandler(_:)"]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/detachLogHandler(_:)":{"type":"topic","kind":"symbol","url":"\/documentation\/chartboostcoresdk\/chartboostcore\/detachloghandler(_:)","abstract":[{"type":"text","text":"Detach a custom logger handler from the logging system."}],"role":"symbol","title":"detachLogHandler(_:)","navigatorTitle":[{"kind":"identifier","text":"detachLogHandler:"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/detachLogHandler(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"detachLogHandler","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCLogHandler","text":"LogHandler","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore":{"navigatorTitle":[{"text":"ChartboostCore","kind":"identifier"}],"role":"symbol","title":"ChartboostCore","url":"\/documentation\/chartboostcoresdk\/chartboostcore","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChartboostCore","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore","abstract":[{"text":"The main interface to the Chartboost Core SDK.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Provides users with access to all of Core’s functionalities."}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogHandler":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogHandler"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogHandler","abstract":[{"text":"The protocol for custom log handlers for the unified logging subsystem.","type":"text"}],"url":"\/documentation\/chartboostcoresdk\/loghandler","title":"LogHandler","navigatorTitle":[{"text":"LogHandler","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","value":"detachLogHandler:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"detachLogHandler:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"detachLogHandler:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@ChartboostCoreSDK@objc(pl)CBCLogHandler","text":"id<CBCLogHandler>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"handler","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":{"parameters":[{"name":"handler","content":[{"inlineContent":[{"type":"text","text":"A custom class that conforms to the "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogHandler","isActive":true},{"type":"text","text":" protocol."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"detachLogHandler:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1detachLogHandler(_:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"detachLogHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1detachLogHandler(_:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore\/title","value":"ChartboostCore","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore\/fragments","value":[{"kind":"identifier","text":"ChartboostCore"}],"op":"replace"},{"value":[{"text":"ChartboostCore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogHandler\/title","op":"replace","value":"CBCLogHandler"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogHandler\/fragments","value":[{"kind":"identifier","text":"CBCLogHandler"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogHandler\/navigatorTitle","value":[{"kind":"identifier","text":"CBCLogHandler"}],"op":"replace"}]}]}