{"sections":[],"abstract":[{"text":"Initializes the Core SDK and its modules.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/initializeSDK(configuration:moduleObserver:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(initializeSDKWithConfiguration:moduleObserver:) "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initializeSDK","kind":"identifier"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SDKConfiguration","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCSDKConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"moduleObserver"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleObserver","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModuleObserver","text":"ModuleObserver","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Initialization configuration parameters.","type":"text"}],"type":"paragraph"}],"name":"configuration"},{"name":"moduleObserver","content":[{"inlineContent":[{"type":"text","text":"An observer to be notified whenever a Core module finishes initialization."}],"type":"paragraph"}]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"text":"As part of initialization Core will:","type":"text"}],"type":"paragraph"},{"items":[{"content":[{"inlineContent":[{"text":"Fetch an app config from the Chartboost Core dashboard with all the info needed for Core and its","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"modules to function."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Instantiate modules defined on the Charboost Core dashboard.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Initialize all the provided modules (both the ones explicitly passed in ","type":"text"},{"type":"codeVoice","code":"configuration"},{"text":" and then","type":"text"},{"text":" ","type":"text"},{"text":"those defined on the dashboard, skipping duplicates).","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Keep all modules successfully initialized alive by creating strong references to them."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Set a module that conforms to ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","isActive":true,"type":"reference"},{"text":" as the backing CMP for ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/consent","type":"reference"},{"type":"text","text":","},{"text":" ","type":"text"},{"type":"text","text":"and thus enabling CMP functionalities."}]}]}],"type":"unorderedList"}],"kind":"content"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore"]]},"metadata":{"externalID":"c:@M@ChartboostCoreSDK@objc(cs)ChartboostCore(cm)initializeSDKWithConfiguration:moduleObserver:","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initializeSDK","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCSDKConfiguration","text":"SDKConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"moduleObserver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModuleObserver","text":"ModuleObserver"},{"kind":"text","text":"?)"}],"symbolKind":"method","navigatorTitle":[{"text":"initializeSDKWithConfiguration:moduleObserver:","kind":"identifier"}],"modules":[{"name":"ChartboostCoreSDK"}],"title":"initializeSDK(configuration:moduleObserver:)","role":"symbol","roleHeading":"Type Method"},"variants":[{"paths":["\/documentation\/chartboostcoresdk\/chartboostcore\/initializesdk(configuration:moduleobserver:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/chartboostcore\/initializesdk(configuration:moduleobserver:)"]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ConsentAdapter","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","abstract":[{"text":"The protocol to which a CMP adapter module must conform to.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ConsentAdapter","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/consentadapter","title":"ConsentAdapter"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleObserver":{"type":"topic","title":"ModuleObserver","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleObserver","abstract":[{"text":"An observer to be notified whenever a Core module finishes initialization.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModuleObserver"}],"role":"symbol","url":"\/documentation\/chartboostcoresdk\/moduleobserver","navigatorTitle":[{"kind":"identifier","text":"ModuleObserver"}],"kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore","abstract":[{"type":"text","text":"The main interface to the Chartboost Core SDK."},{"text":" ","type":"text"},{"type":"text","text":"Provides users with access to all of Core’s functionalities."}],"kind":"symbol","navigatorTitle":[{"text":"ChartboostCore","kind":"identifier"}],"title":"ChartboostCore","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChartboostCore"}],"url":"\/documentation\/chartboostcoresdk\/chartboostcore"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/SDKConfiguration":{"url":"\/documentation\/chartboostcoresdk\/sdkconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDKConfiguration"}],"abstract":[{"type":"text","text":"Configuration with parameters needed by the Chartboost Core SDK on initialization."}],"type":"topic","title":"SDKConfiguration","navigatorTitle":[{"kind":"identifier","text":"SDKConfiguration"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/initializeSDK(configuration:moduleObserver:)":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/initializeSDK(configuration:moduleObserver:)","abstract":[{"text":"Initializes the Core SDK and its modules.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initializeSDKWithConfiguration:moduleObserver:"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/chartboostcore\/initializesdk(configuration:moduleobserver:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initializeSDK"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCSDKConfiguration","text":"SDKConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"moduleObserver","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ModuleObserver","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModuleObserver"},{"kind":"text","text":"?)"}],"title":"initializeSDK(configuration:moduleObserver:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/consent":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The CMP in charge of handling user consent."}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"consent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentManagementPlatform","text":"ConsentManagementPlatform"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/consent","navigatorTitle":[{"text":"consent","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/chartboostcore\/consent","title":"consent"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initializeSDKWithConfiguration:moduleObserver:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"initializeSDKWithConfiguration:moduleObserver:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"initializeSDKWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CBCSDKConfiguration","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCSDKConfiguration","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":" "},{"text":"moduleObserver:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<CBCModuleObserver>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@ChartboostCoreSDK@objc(pl)CBCModuleObserver"},{"text":" *) ","kind":"text"},{"text":"moduleObserver","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/title","op":"replace","value":"CBCConsentAdapter"},{"value":[{"kind":"identifier","text":"CBCConsentAdapter"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/fragments"},{"value":"CBCModuleObserver","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleObserver\/title","op":"replace"},{"op":"replace","value":[{"text":"CBCModuleObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleObserver\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore\/title","op":"replace","value":"ChartboostCore"},{"value":[{"text":"ChartboostCore","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration\/title","value":"CBCSDKConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"CBCSDKConfiguration"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration\/fragments","op":"replace"},{"op":"replace","value":"initializeSDKWithConfiguration:moduleObserver:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1initializeSDK(configuration:moduleObserver:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1initializeSDK(configuration:moduleObserver:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initializeSDKWithConfiguration:moduleObserver:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1consent\/title","value":"consent","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1consent\/fragments","value":[{"text":"consent","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}