{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"makeModule"},{"kind":"text","text":"("},{"text":"className","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"credentials","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"Module","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModule"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The name of the module class."}],"type":"paragraph"}],"name":"className"},{"name":"credentials","content":[{"inlineContent":[{"type":"text","text":"The dictionary object to pass to "},{"code":"Module.init(credentials:)","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A closure that receives the generated module."}]}],"name":"completion"}]}],"metadata":{"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"ChartboostCoreSDK"}],"title":"makeModule(className:credentials:completion:)","required":true,"symbolKind":"method","navigatorTitle":[{"text":"makeModuleWithClassName:credentials:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"makeModule"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"className"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"credentials","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Module","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModule"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCModuleFactory(im)makeModuleWithClassName:credentials:completion:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/modulefactory\/makemodule(classname:credentials:completion:)"]},{"paths":["\/documentation\/chartboostcoresdk\/modulefactory\/makemodule(classname:credentials:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleFactory"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleFactory\/makeModule(className:credentials:completion:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Returns a module instantiate via reflection."}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleFactory":{"navigatorTitle":[{"text":"ModuleFactory","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/modulefactory","type":"topic","role":"symbol","abstract":[{"text":"Factory to instantiate a Core module using its class name via reflection.","type":"text"}],"title":"ModuleFactory","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ModuleFactory","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleFactory","kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleFactory/makeModule(className:credentials:completion:)":{"kind":"symbol","type":"topic","title":"makeModule(className:credentials:completion:)","required":true,"role":"symbol","navigatorTitle":[{"text":"makeModuleWithClassName:credentials:completion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleFactory\/makeModule(className:credentials:completion:)","url":"\/documentation\/chartboostcoresdk\/modulefactory\/makemodule(classname:credentials:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"makeModule","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"className"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"credentials","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"Module","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModule"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns a module instantiate via reflection."}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Module":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Module","kind":"identifier"}],"kind":"symbol","title":"Module","url":"\/documentation\/chartboostcoresdk\/module","type":"topic","abstract":[{"type":"text","text":"The protocol to which all Chartboost Core modules must conform to."}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module","role":"symbol","navigatorTitle":[{"text":"Module","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"makeModuleWithClassName:credentials:completion:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"makeModuleWithClassName:credentials:completion:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"makeModuleWithClassName:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"className","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"credentials:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary<NSString *,id>"},{"text":" *) ","kind":"text"},{"text":"credentials","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#*Qo@M@ChartboostCoreSDK@objc(pl)CBCModule)","text":"void (^)(id<CBCModule>)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"CBCModuleFactory","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleFactory\/title"},{"value":[{"kind":"identifier","text":"CBCModuleFactory"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleFactory\/fragments"},{"value":"makeModuleWithClassName:credentials:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleFactory~1makeModule(className:credentials:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"makeModuleWithClassName:credentials:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleFactory~1makeModule(className:credentials:completion:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/title","op":"replace","value":"CBCModule"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/fragments","value":[{"text":"CBCModule","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}