{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleObserver\/onModuleInitializationCompleted(_:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleObserver"]]},"variants":[{"paths":["\/documentation\/chartboostcoresdk\/moduleobserver\/onmoduleinitializationcompleted(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/moduleobserver\/onmoduleinitializationcompleted(_:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onModuleInitializationCompleted"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"result","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleInitializationResult","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCModuleInitializationResult","text":"ModuleInitializationResult"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"result","content":[{"inlineContent":[{"text":"The result of the initialization.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note that Chartboost Core may attempt to initialize the same module multiple times"},{"type":"text","text":" "},{"text":"before this method is called. This method will only be invoked once the module","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"has been successfully initialized or when the SDK has ceased its attempts at initialization."}]}],"kind":"content"}],"abstract":[{"text":"Called whenever a module is initialized by the Chartboost Core SDK.","type":"text"}],"metadata":{"title":"onModuleInitializationCompleted(_:)","externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCModuleObserver(im)onModuleInitializationCompleted:","modules":[{"name":"ChartboostCoreSDK"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onModuleInitializationCompleted:"}],"required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onModuleInitializationCompleted","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCModuleInitializationResult","text":"ModuleInitializationResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","roleHeading":"Instance Method"},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleInitializationResult":{"navigatorTitle":[{"kind":"identifier","text":"ModuleInitializationResult"}],"abstract":[{"type":"text","text":"A result object with the information regarding a module initialization operation."}],"url":"\/documentation\/chartboostcoresdk\/moduleinitializationresult","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModuleInitializationResult"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleInitializationResult","title":"ModuleInitializationResult","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleObserver/onModuleInitializationCompleted(_:)":{"title":"onModuleInitializationCompleted(_:)","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleObserver\/onModuleInitializationCompleted(_:)","url":"\/documentation\/chartboostcoresdk\/moduleobserver\/onmoduleinitializationcompleted(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onModuleInitializationCompleted"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCModuleInitializationResult","text":"ModuleInitializationResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"role":"symbol","abstract":[{"type":"text","text":"Called whenever a module is initialized by the Chartboost Core SDK."}],"navigatorTitle":[{"text":"onModuleInitializationCompleted:","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleObserver":{"title":"ModuleObserver","navigatorTitle":[{"text":"ModuleObserver","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/chartboostcoresdk\/moduleobserver","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleObserver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ModuleObserver","kind":"identifier"}],"abstract":[{"type":"text","text":"An observer to be notified whenever a Core module finishes initialization."}],"kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onModuleInitializationCompleted:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onModuleInitializationCompleted:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onModuleInitializationCompleted:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCModuleInitializationResult","text":"CBCModuleInitializationResult","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleInitializationResult"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The result of the initialization.","type":"text"}]}],"name":"result"}],"kind":"parameters"}},{"value":"CBCModuleInitializationResult","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleInitializationResult\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleInitializationResult\/fragments","op":"replace","value":[{"text":"CBCModuleInitializationResult","kind":"identifier"}]},{"value":[{"text":"CBCModuleInitializationResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleInitializationResult\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleObserver~1onModuleInitializationCompleted(_:)\/title","value":"onModuleInitializationCompleted:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleObserver~1onModuleInitializationCompleted(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onModuleInitializationCompleted:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleObserver\/title","value":"CBCModuleObserver","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleObserver\/fragments","value":[{"text":"CBCModuleObserver","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"CBCModuleObserver"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleObserver\/navigatorTitle"}]}]}