{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/VendorIDScope"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/VendorIDScope\/developer"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/vendoridscope\/developer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/vendoridscope\/developer"]}],"abstract":[{"type":"text","text":"Developer scope."}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"CBCVendorIDScopeDeveloper"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"developer","kind":"identifier"}],"externalID":"c:@M@ChartboostCoreSDK@E@CBCVendorIDScope@CBCVendorIDScopeDeveloper","title":"VendorIDScope.developer","modules":[{"name":"ChartboostCoreSDK"}],"symbolKind":"case","role":"symbol"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"developer"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/VendorIDScope/developer":{"url":"\/documentation\/chartboostcoresdk\/vendoridscope\/developer","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/VendorIDScope\/developer","kind":"symbol","type":"topic","title":"VendorIDScope.developer","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"developer"}],"role":"symbol","navigatorTitle":[{"text":"CBCVendorIDScopeDeveloper","kind":"identifier"}],"abstract":[{"text":"Developer scope.","type":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/VendorIDScope":{"navigatorTitle":[{"text":"VendorIDScope","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/vendoridscope","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"VendorIDScope","kind":"identifier"}],"type":"topic","abstract":[{"text":"The scope of a vendor identifier.","type":"text"}],"role":"symbol","title":"VendorIDScope","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/VendorIDScope","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CBCVendorIDScopeDeveloper"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"CBCVendorIDScopeDeveloper","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"CBCVendorIDScopeDeveloper","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1VendorIDScope~1developer\/title","value":"CBCVendorIDScopeDeveloper"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1VendorIDScope~1developer\/fragments","value":[{"kind":"identifier","text":"CBCVendorIDScopeDeveloper"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1VendorIDScope\/title","value":"CBCVendorIDScope"},{"value":[{"text":"CBCVendorIDScope","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1VendorIDScope\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1VendorIDScope\/navigatorTitle","value":[{"text":"CBCVendorIDScope","kind":"identifier"}]}]}]}