{"sections":[],"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/VendorIDScope\/!=(_:_:)"],"generated":true,"title":"Operators","anchor":"Operators"}],"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","role":"collectionGroup","modules":[{"name":"ChartboostCoreSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/VendorIDScope"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/vendoridscope\/equatable-implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/VendorIDScope\/Equatable-Implementations"},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/VendorIDScope":{"navigatorTitle":[{"text":"VendorIDScope","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/vendoridscope","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"VendorIDScope","kind":"identifier"}],"type":"topic","abstract":[{"text":"The scope of a vendor identifier.","type":"text"}],"role":"symbol","title":"VendorIDScope","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/VendorIDScope","kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/VendorIDScope/!=(_:_:)":{"type":"topic","title":"!=(_:_:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/VendorIDScope\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/chartboostcoresdk\/vendoridscope\/!=(_:_:)","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"CBCVendorIDScope","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1VendorIDScope\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1VendorIDScope\/fragments","value":[{"text":"CBCVendorIDScope","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"CBCVendorIDScope","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1VendorIDScope\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}