{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/vendoridscope\/unknown"]},{"paths":["\/documentation\/chartboostcoresdk\/vendoridscope\/unknown"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/VendorIDScope\/unknown"},"metadata":{"symbolKind":"case","externalID":"c:@M@ChartboostCoreSDK@E@CBCVendorIDScope@CBCVendorIDScopeUnknown","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknown"}],"title":"VendorIDScope.unknown","modules":[{"name":"ChartboostCoreSDK"}],"navigatorTitle":[{"text":"CBCVendorIDScopeUnknown","kind":"identifier"}],"role":"symbol"},"abstract":[{"type":"text","text":"Unknown scope."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/VendorIDScope"]]},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/VendorIDScope/unknown":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unknown","kind":"identifier"}],"title":"VendorIDScope.unknown","abstract":[{"type":"text","text":"Unknown scope."}],"kind":"symbol","navigatorTitle":[{"text":"CBCVendorIDScopeUnknown","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/VendorIDScope\/unknown","url":"\/documentation\/chartboostcoresdk\/vendoridscope\/unknown","role":"symbol","type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/VendorIDScope":{"url":"\/documentation\/chartboostcoresdk\/vendoridscope","abstract":[{"type":"text","text":"The scope of a vendor identifier."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/VendorIDScope","title":"VendorIDScope","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"VendorIDScope","kind":"identifier"}],"navigatorTitle":[{"text":"VendorIDScope","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"CBCVendorIDScopeUnknown"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"CBCVendorIDScopeUnknown","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"CBCVendorIDScopeUnknown","kind":"identifier"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1VendorIDScope~1unknown\/title","value":"CBCVendorIDScopeUnknown","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1VendorIDScope~1unknown\/fragments","value":[{"text":"CBCVendorIDScopeUnknown","kind":"identifier"}]},{"value":"CBCVendorIDScope","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1VendorIDScope\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1VendorIDScope\/fragments","value":[{"kind":"identifier","text":"CBCVendorIDScope"}],"op":"replace"}]}]}