{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Called every time there’s a change in the value of one of the environment properties with a"},{"type":"text","text":" "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty","type":"reference"},{"text":" counterpart.","type":"text"}],"variants":[{"paths":["\/documentation\/chartboostcoresdk\/environmentobserver\/onchange(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/environmentobserver\/onchange(_:)"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onChange"},{"kind":"text","text":"("},{"text":"ObservableEnvironmentProperty","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCObservableEnvironmentProperty"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"onChange:"}],"role":"symbol","required":true,"title":"onChange(_:)","externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCEnvironmentObserver(im)onChange:","modules":[{"name":"ChartboostCoreSDK"}],"symbolKind":"method"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onChange","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"property","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty","text":"ObservableEnvironmentProperty","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCObservableEnvironmentProperty"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A constant that identifies the environment property that changed.","type":"text"},{"type":"text","text":" "},{"text":"Note that in order to access the new value for that field you’ll have to go through the Core environment.","type":"text"}]}],"name":"property"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver"]]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver\/onChange(_:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/EnvironmentObserver/onChange(_:)":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver\/onChange(_:)","title":"onChange(_:)","kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"onChange:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onChange","kind":"identifier"},{"kind":"text","text":"("},{"text":"ObservableEnvironmentProperty","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCObservableEnvironmentProperty"},{"text":")","kind":"text"}],"url":"\/documentation\/chartboostcoresdk\/environmentobserver\/onchange(_:)","type":"topic","abstract":[{"type":"text","text":"Called every time there’s a change in the value of one of the environment properties with a"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty","isActive":true,"type":"reference"},{"type":"text","text":" counterpart."}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/EnvironmentObserver":{"url":"\/documentation\/chartboostcoresdk\/environmentobserver","kind":"symbol","title":"EnvironmentObserver","abstract":[{"type":"text","text":"An observer that gets notified when the value of some observable environment field changes."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvironmentObserver"}],"navigatorTitle":[{"text":"EnvironmentObserver","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty":{"url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty","kind":"symbol","abstract":[{"type":"text","text":"A constant that identifies an environment property that can be observed via a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver"},{"text":".","type":"text"}],"title":"ObservableEnvironmentProperty","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObservableEnvironmentProperty"}],"navigatorTitle":[{"kind":"identifier","text":"ObservableEnvironmentProperty"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"onChange:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onChange:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onChange:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"CBCObservableEnvironmentProperty","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCObservableEnvironmentProperty"},{"kind":"text","text":") "},{"text":"property","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"onChange:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver~1onChange(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver~1onChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onChange:"}]},{"value":"CBCEnvironmentObserver","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBCEnvironmentObserver"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty\/title","value":"CBCObservableEnvironmentProperty","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty\/fragments","value":[{"text":"CBCObservableEnvironmentProperty","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}