{"abstract":[{"type":"text","text":"An environment that contains information intended solely for attribution purposes."}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AttributionEnvironment\/advertisingID"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AttributionEnvironment\/userAgent(completion:)"],"generated":true,"anchor":"Instance-Methods"}],"metadata":{"roleHeading":"Protocol","modules":[{"name":"ChartboostCoreSDK"}],"role":"symbol","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"AttributionEnvironment","kind":"identifier"}],"navigatorTitle":[{"text":"AttributionEnvironment","kind":"identifier"}],"title":"AttributionEnvironment","externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCAttributionEnvironment"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CBCAttributionEnvironment) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AttributionEnvironment"}],"languages":["swift"]}]},{"content":[{"text":"Overview","type":"heading","anchor":"overview","level":2},{"style":"warning","type":"aside","name":"Warning","content":[{"type":"paragraph","inlineContent":[{"text":"Make sure to access UI-related properties from the main thread.","type":"text"}]}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/attributionenvironment"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/attributionenvironment"]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AttributionEnvironment","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AttributionEnvironment":{"navigatorTitle":[{"text":"AttributionEnvironment","kind":"identifier"}],"abstract":[{"type":"text","text":"An environment that contains information intended solely for attribution purposes."}],"url":"\/documentation\/chartboostcoresdk\/attributionenvironment","kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AttributionEnvironment","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AttributionEnvironment","title":"AttributionEnvironment","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AttributionEnvironment/userAgent(completion:)":{"required":true,"navigatorTitle":[{"text":"userAgentWithCompletion:","kind":"identifier"}],"abstract":[{"text":"Obtain the device user agent asynchronously.","type":"text"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/attributionenvironment\/useragent(completion:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userAgent"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"userAgent"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AttributionEnvironment\/userAgent(completion:)","title":"userAgent(completion:)","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AttributionEnvironment/advertisingID":{"type":"topic","title":"advertisingID","url":"\/documentation\/chartboostcoresdk\/attributionenvironment\/advertisingid","kind":"symbol","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"advertisingID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"advertisingID","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AttributionEnvironment\/advertisingID","abstract":[{"type":"text","text":"The system advertising identifier (IFA)."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"value":"CBCAttributionEnvironment","path":"\/metadata\/title","op":"replace"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"CBCAttributionEnvironment","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBCAttributionEnvironment"}]},{"value":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AttributionEnvironment\/advertisingID"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AttributionEnvironment\/userAgent(completion:)"],"generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBCAttributionEnvironment","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"CBCAttributionEnvironment","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AttributionEnvironment\/title"},{"value":[{"text":"CBCAttributionEnvironment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AttributionEnvironment\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AttributionEnvironment\/navigatorTitle","value":[{"text":"CBCAttributionEnvironment","kind":"identifier"}]},{"value":"userAgentWithCompletion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AttributionEnvironment~1userAgent(completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AttributionEnvironment~1userAgent(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userAgentWithCompletion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AttributionEnvironment~1advertisingID\/title","op":"replace","value":"advertisingID"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AttributionEnvironment~1advertisingID\/fragments","value":[{"kind":"identifier","text":"advertisingID"}],"op":"replace"}]}]}