{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The main interface to the Chartboost Core SDK."},{"text":" ","type":"text"},{"type":"text","text":"Provides users with access to all of Core’s functionalities."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChartboostCore","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/chartboostcore"]},{"paths":["\/documentation\/chartboostcoresdk\/chartboostcore"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/advertisingEnvironment","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/analyticsEnvironment","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/attributionEnvironment","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/consent","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/logLevel","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/publisherMetadata","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/sdkVersion"],"title":"Type Properties"},{"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/attachLogHandler(_:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/detachLogHandler(_:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/initializeSDK(configuration:moduleObserver:)"]}],"metadata":{"modules":[{"name":"ChartboostCoreSDK"}],"title":"ChartboostCore","externalID":"c:@M@ChartboostCoreSDK@objc(cs)ChartboostCore","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChartboostCore"}],"roleHeading":"Class","navigatorTitle":[{"text":"ChartboostCore","kind":"identifier"}],"role":"symbol"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChartboostCoreSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SQ","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SH"],"title":"Conforms To"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"]]},"references":{"doc://org.cocoapods.ChartboostCoreSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.ChartboostCoreSDK/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/attributionEnvironment":{"url":"\/documentation\/chartboostcoresdk\/chartboostcore\/attributionenvironment","abstract":[{"text":"The environment that contains information intended solely for attribution purposes.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"attributionEnvironment"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attributionEnvironment"},{"text":": ","kind":"text"},{"text":"AttributionEnvironment","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCAttributionEnvironment"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/attributionEnvironment","title":"attributionEnvironment","type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/consent":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The CMP in charge of handling user consent."}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"consent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentManagementPlatform","text":"ConsentManagementPlatform"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/consent","navigatorTitle":[{"text":"consent","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/chartboostcore\/consent","title":"consent"},"doc://org.cocoapods.ChartboostCoreSDK/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/detachLogHandler(_:)":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Detach a custom logger handler from the logging system."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"detachLogHandler","kind":"identifier"},{"kind":"text","text":"("},{"text":"LogHandler","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCLogHandler"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/detachLogHandler(_:)","navigatorTitle":[{"kind":"identifier","text":"detachLogHandler:"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/chartboostcore\/detachloghandler(_:)","title":"detachLogHandler(_:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/logLevel":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/logLevel","abstract":[{"type":"text","text":"The Chartboost Core console log level."}],"kind":"symbol","navigatorTitle":[{"text":"logLevel","kind":"identifier"}],"title":"logLevel","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"logLevel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"LogLevel","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCLogLevel"}],"url":"\/documentation\/chartboostcoresdk\/chartboostcore\/loglevel"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/advertisingEnvironment":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The environment that contains information intended solely for advertising purposes."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"advertisingEnvironment","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdvertisingEnvironment","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCAdvertisingEnvironment"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/advertisingEnvironment","navigatorTitle":[{"kind":"identifier","text":"advertisingEnvironment"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/chartboostcore\/advertisingenvironment","title":"advertisingEnvironment"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/publisherMetadata":{"role":"symbol","type":"topic","abstract":[{"text":"Publisher-provided metadata.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"publisherMetadata"},{"text":": ","kind":"text"},{"text":"PublisherMetadata","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCPublisherMetadata","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/publisherMetadata","navigatorTitle":[{"kind":"identifier","text":"publisherMetadata"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/chartboostcore\/publishermetadata","title":"publisherMetadata"},"doc://org.cocoapods.ChartboostCoreSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SQ"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/initializeSDK(configuration:moduleObserver:)":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/initializeSDK(configuration:moduleObserver:)","abstract":[{"text":"Initializes the Core SDK and its modules.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initializeSDKWithConfiguration:moduleObserver:"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/chartboostcore\/initializesdk(configuration:moduleobserver:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initializeSDK"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCSDKConfiguration","text":"SDKConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"moduleObserver","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ModuleObserver","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModuleObserver"},{"kind":"text","text":"?)"}],"title":"initializeSDK(configuration:moduleObserver:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore","abstract":[{"type":"text","text":"The main interface to the Chartboost Core SDK."},{"text":" ","type":"text"},{"type":"text","text":"Provides users with access to all of Core’s functionalities."}],"kind":"symbol","navigatorTitle":[{"text":"ChartboostCore","kind":"identifier"}],"title":"ChartboostCore","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChartboostCore"}],"url":"\/documentation\/chartboostcoresdk\/chartboostcore"},"doc://org.cocoapods.ChartboostCoreSDK/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(cs)NSObject"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/attachLogHandler(_:)":{"navigatorTitle":[{"kind":"identifier","text":"attachLogHandler:"}],"title":"attachLogHandler(_:)","kind":"symbol","abstract":[{"text":"Attach a custom logger handler to the logging system.","type":"text"}],"type":"topic","url":"\/documentation\/chartboostcoresdk\/chartboostcore\/attachloghandler(_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachLogHandler"},{"text":"(","kind":"text"},{"text":"LogHandler","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCLogHandler"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/attachLogHandler(_:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/analyticsEnvironment":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The environment that contains information intended solely for analytics purposes."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"analyticsEnvironment","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnalyticsEnvironment","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCAnalyticsEnvironment"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/analyticsEnvironment","navigatorTitle":[{"kind":"identifier","text":"analyticsEnvironment"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/chartboostcore\/analyticsenvironment","title":"analyticsEnvironment"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/sdkVersion":{"role":"symbol","type":"topic","abstract":[{"text":"The version of the Core SDK.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sdkVersion"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/sdkVersion","navigatorTitle":[{"kind":"identifier","text":"sdkVersion"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/chartboostcore\/sdkversion","title":"sdkVersion"},"doc://org.cocoapods.ChartboostCoreSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SH"},"doc://org.cocoapods.ChartboostCoreSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"ChartboostCore","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ChartboostCore","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ChartboostCore"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/advertisingEnvironment","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/analyticsEnvironment","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/attributionEnvironment","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/consent","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/logLevel","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/publisherMetadata","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/sdkVersion"]},{"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/attachLogHandler(_:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/detachLogHandler(_:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/initializeSDK(configuration:moduleObserver:)"]}]},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChartboostCore","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1attributionEnvironment\/title","op":"replace","value":"attributionEnvironment"},{"value":[{"text":"attributionEnvironment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1attributionEnvironment\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1consent\/title","value":"consent"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1consent\/fragments","op":"replace","value":[{"text":"consent","kind":"identifier"}]},{"value":"detachLogHandler:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1detachLogHandler(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1detachLogHandler(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"detachLogHandler:"}],"op":"replace"},{"op":"replace","value":"logLevel","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1logLevel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1logLevel\/fragments","op":"replace","value":[{"kind":"identifier","text":"logLevel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1advertisingEnvironment\/title","op":"replace","value":"advertisingEnvironment"},{"value":[{"text":"advertisingEnvironment","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1advertisingEnvironment\/fragments","op":"replace"},{"value":"publisherMetadata","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1publisherMetadata\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1publisherMetadata\/fragments","op":"replace","value":[{"text":"publisherMetadata","kind":"identifier"}]},{"value":"initializeSDKWithConfiguration:moduleObserver:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1initializeSDK(configuration:moduleObserver:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1initializeSDK(configuration:moduleObserver:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"initializeSDKWithConfiguration:moduleObserver:","kind":"identifier"}],"op":"replace"},{"value":"ChartboostCore","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore\/fragments","value":[{"kind":"identifier","text":"ChartboostCore"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1attachLogHandler(_:)\/title","op":"replace","value":"attachLogHandler:"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1attachLogHandler(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"attachLogHandler:"}],"op":"replace"},{"value":"analyticsEnvironment","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1analyticsEnvironment\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1analyticsEnvironment\/fragments","value":[{"text":"analyticsEnvironment","kind":"identifier"}]},{"value":"sdkVersion","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1sdkVersion\/title"},{"value":[{"text":"sdkVersion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1sdkVersion\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}