{"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An observer that gets notified whenever any change happens in the CMP consent info."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CBCConsentObserver) "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConsentObserver","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"]]},"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver\/onConsentChange(fullConsents:modifiedKeys:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver\/onConsentModuleReady(initialConsents:)"],"anchor":"Instance-Methods"}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"ConsentObserver","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentObserver","title":"ConsentObserver","modules":[{"name":"ChartboostCoreSDK"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsentObserver","kind":"identifier"}],"symbolKind":"protocol","roleHeading":"Protocol"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/consentobserver"]},{"paths":["\/documentation\/chartboostcoresdk\/consentobserver"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentObserver/onConsentChange(fullConsents:modifiedKeys:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConsentChange","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fullConsents"},{"text":": [","kind":"text"},{"text":"ConsentKey","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"},{"kind":"text","text":" : "},{"text":"ConsentValue","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"modifiedKeys"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","text":"ConsentKey"},{"text":">)","kind":"text"}],"title":"onConsentChange(fullConsents:modifiedKeys:)","url":"\/documentation\/chartboostcoresdk\/consentobserver\/onconsentchange(fullconsents:modifiedkeys:)","kind":"symbol","abstract":[{"text":"Called whenever the ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents","type":"reference"},{"type":"text","text":" value changed."}],"required":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver\/onConsentChange(fullConsents:modifiedKeys:)","navigatorTitle":[{"kind":"identifier","text":"onConsentChangeWithFullConsents:modifiedKeys:"}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/consents":{"kind":"symbol","title":"consents","abstract":[{"type":"text","text":"Current user consent info as determined by the CMP."}],"type":"topic","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/consents","required":true,"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents","navigatorTitle":[{"kind":"identifier","text":"consents"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"consents"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","text":"ConsentKey"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea","text":"ConsentValue","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentObserver/onConsentModuleReady(initialConsents:)":{"title":"onConsentModuleReady(initialConsents:)","required":true,"type":"topic","url":"\/documentation\/chartboostcoresdk\/consentobserver\/onconsentmoduleready(initialconsents:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onConsentModuleReadyWithInitialConsents:"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver\/onConsentModuleReady(initialConsents:)","abstract":[{"type":"text","text":"Called when the "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","type":"reference"},{"text":" module is initialized and the ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform","isActive":true},{"type":"text","text":" object"},{"text":" ","type":"text"},{"text":"is ready to be used.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"At this moment "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents","type":"reference","isActive":true},{"text":" will have proper values and methods like","type":"text"},{"text":" ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:)","isActive":true},{"text":" will no longer be no-ops.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onConsentModuleReady","kind":"identifier"},{"text":"(","kind":"text"},{"text":"initialConsents","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"ConsentKey","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"},{"text":" : ","kind":"text"},{"text":"ConsentValue","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea"},{"kind":"text","text":"])"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsentAdapter"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","abstract":[{"type":"text","text":"The protocol to which a CMP adapter module must conform to."}],"url":"\/documentation\/chartboostcoresdk\/consentadapter","title":"ConsentAdapter","navigatorTitle":[{"text":"ConsentAdapter","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentObserver":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsentObserver"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver","abstract":[{"type":"text","text":"An observer that gets notified whenever any change happens in the CMP consent info."}],"url":"\/documentation\/chartboostcoresdk\/consentobserver","title":"ConsentObserver","navigatorTitle":[{"text":"ConsentObserver","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentManagementPlatform"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform","role":"symbol","abstract":[{"type":"text","text":"Chartboost Core’s CMP in charge of handling user consent management."},{"type":"text","text":" "},{"type":"text","text":"Chartboost Core defines a unified API for publishers to request and query user consent,"},{"type":"text","text":" "},{"type":"text","text":"and relies on a 3rd-party CMP SDK to provide the CMP functionality."}],"title":"ConsentManagementPlatform","kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform","navigatorTitle":[{"kind":"identifier","text":"ConsentManagementPlatform"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/showConsentDialog(_:from:)":{"kind":"symbol","title":"showConsentDialog(_:from:)","abstract":[{"type":"text","text":"Instructs the CMP to present a consent dialog to the user for the purpose of collecting consent."}],"type":"topic","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/showconsentdialog(_:from:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showConsentDialog","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ConsentDialogType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentDialogType"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"CBCConsentObserver","op":"replace"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"CBCConsentObserver"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CBCConsentObserver"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver\/onConsentChange(fullConsents:modifiedKeys:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver\/onConsentModuleReady(initialConsents:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"CBCConsentObserver","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver~1onConsentChange(fullConsents:modifiedKeys:)\/title","value":"onConsentChangeWithFullConsents:modifiedKeys:"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver~1onConsentChange(fullConsents:modifiedKeys:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onConsentChangeWithFullConsents:modifiedKeys:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1consents\/title","value":"consents","op":"replace"},{"value":[{"kind":"identifier","text":"consents"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1consents\/fragments"},{"op":"replace","value":"onConsentModuleReadyWithInitialConsents:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver~1onConsentModuleReady(initialConsents:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver~1onConsentModuleReady(initialConsents:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onConsentModuleReadyWithInitialConsents:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/title","value":"CBCConsentAdapter","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/fragments","value":[{"kind":"identifier","text":"CBCConsentAdapter"}]},{"op":"replace","value":[{"kind":"identifier","text":"CBCConsentAdapter"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver\/title","value":"CBCConsentObserver"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver\/fragments","value":[{"kind":"identifier","text":"CBCConsentObserver"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver\/navigatorTitle","value":[{"kind":"identifier","text":"CBCConsentObserver"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/title","value":"CBCConsentManagementPlatform","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/fragments","value":[{"text":"CBCConsentManagementPlatform","kind":"identifier"}]},{"value":[{"text":"CBCConsentManagementPlatform","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/navigatorTitle"}]}]}