{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(CBCConsentKeys) ","kind":"text"},{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ConsentKeys","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"metadata":{"symbolKind":"class","externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCConsentKeys","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConsentKeys","kind":"identifier"}],"title":"ConsentKeys","modules":[{"name":"ChartboostCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ConsentKeys"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys"},"abstract":[{"text":"A namespace for Core’s predefined ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","isActive":true,"type":"reference"},{"type":"text","text":" constants."}],"variants":[{"paths":["\/documentation\/chartboostcoresdk\/consentkeys"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostcoresdk\/consentkeys"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChartboostCoreSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SQ","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/ccpaOptIn","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/gdprConsentGiven","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/gpp","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/tcf","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/usp"]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.ChartboostCoreSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.ChartboostCoreSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKeys/ccpaOptIn":{"url":"\/documentation\/chartboostcoresdk\/consentkeys\/ccpaoptin","kind":"symbol","type":"topic","title":"ccpaOptIn","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/ccpaOptIn","navigatorTitle":[{"kind":"identifier","text":"ccpaOptIn"}],"abstract":[{"type":"text","text":"CCPA opt-in key."},{"type":"text","text":" "},{"type":"text","text":"Possible values are: "},{"type":"codeVoice","code":"ConsentValue\/denied"},{"text":", ","type":"text"},{"type":"codeVoice","code":"ConsentValue\/granted"},{"type":"text","text":", "},{"code":"ConsentValue\/doesNotApply","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"ccpaOptIn","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConsentKey","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKeys":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentKeys"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentkeys","title":"ConsentKeys","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys","abstract":[{"text":"A namespace for Core’s predefined ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","isActive":true,"type":"reference"},{"text":" constants.","type":"text"}],"navigatorTitle":[{"text":"ConsentKeys","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKey":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsentKey","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentkey","title":"ConsentKey","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","abstract":[{"text":"A key in a Core consents dictionary.","type":"text"}],"navigatorTitle":[{"text":"ConsentKey","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKeys/gdprConsentGiven":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"gdprConsentGiven"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConsentKey","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"}],"navigatorTitle":[{"kind":"identifier","text":"gdprConsentGiven"}],"url":"\/documentation\/chartboostcoresdk\/consentkeys\/gdprconsentgiven","role":"symbol","abstract":[{"text":"GDPR consent given key.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Possible values are: "},{"type":"codeVoice","code":"ConsentValue\/denied"},{"text":", ","type":"text"},{"code":"ConsentValue\/granted","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"ConsentValue\/doesNotApply"},{"type":"text","text":"."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/gdprConsentGiven","title":"gdprConsentGiven"},"doc://org.cocoapods.ChartboostCoreSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKeys/gpp":{"title":"gpp","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/gpp","type":"topic","url":"\/documentation\/chartboostcoresdk\/consentkeys\/gpp","abstract":[{"type":"text","text":"GPP key."},{"text":" ","type":"text"},{"type":"text","text":"Possible values are IAB’s GPP strings, as defined in https:\/\/github.com\/InteractiveAdvertisingBureau\/Global-Privacy-Platform\/blob\/main\/Core\/Consent%20String%20Specification.md"}],"role":"symbol","navigatorTitle":[{"text":"gpp","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"gpp","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","text":"ConsentKey","kind":"typeIdentifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ChartboostCoreSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKeys/usp":{"url":"\/documentation\/chartboostcoresdk\/consentkeys\/usp","kind":"symbol","type":"topic","title":"usp","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/usp","navigatorTitle":[{"text":"usp","kind":"identifier"}],"abstract":[{"text":"USP key.","type":"text"},{"text":" ","type":"text"},{"text":"Possible values are IAB’s USP strings, as defined in https:\/\/github.com\/InteractiveAdvertisingBureau\/USPrivacy\/blob\/master\/CCPA\/US%20Privacy%20String.md","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"usp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConsentKey","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKeys/tcf":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"tcf","kind":"identifier"},{"kind":"text","text":": "},{"text":"ConsentKey","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentkeys\/tcf","title":"tcf","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/tcf","abstract":[{"text":"TCF key.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Possible values are IAB’s TCF strings, as defined in https:\/\/github.com\/InteractiveAdvertisingBureau\/GDPR-Transparency-and-Consent-Framework\/blob\/master\/TCFv2\/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md"}],"navigatorTitle":[{"text":"tcf","kind":"identifier"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"CBCConsentKeys"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"CBCConsentKeys"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CBCConsentKeys"}]},{"value":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/ccpaOptIn","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/gdprConsentGiven","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/gpp","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/tcf","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKeys\/usp"],"title":"Type Properties"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"CBCConsentKeys","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]},"path":"\/primaryContentSections\/0"},{"value":"ccpaOptIn","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1ccpaOptIn\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1ccpaOptIn\/fragments","value":[{"text":"ccpaOptIn","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys\/title","value":"CBCConsentKeys","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys\/fragments","value":[{"text":"CBCConsentKeys","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1gdprConsentGiven\/title","value":"gdprConsentGiven","op":"replace"},{"value":[{"kind":"identifier","text":"gdprConsentGiven"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1gdprConsentGiven\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1gpp\/title","value":"gpp"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1gpp\/fragments","op":"replace","value":[{"text":"gpp","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1usp\/title","value":"usp","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"usp"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1usp\/fragments"},{"value":"tcf","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1tcf\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentKeys~1tcf\/fragments","op":"replace","value":[{"kind":"identifier","text":"tcf"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}