{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"]]},"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"ConsentValues","kind":"identifier"}],"modules":[{"name":"ChartboostCoreSDK"}],"role":"symbol","externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCConsentValues","title":"ConsentValues","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentValues"}],"roleHeading":"Class"},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A namespace for Core’s predefined "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValue","type":"reference"},{"type":"text","text":" constants."}],"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/denied","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/doesNotApply","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/granted"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChartboostCoreSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SQ","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SH"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(CBCConsentValues) "},{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ConsentValues","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/chartboostcoresdk\/consentvalues"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/consentvalues"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.ChartboostCoreSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.ChartboostCoreSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.ChartboostCoreSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.ChartboostCoreSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentValues/granted":{"url":"\/documentation\/chartboostcoresdk\/consentvalues\/granted","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/granted","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"granted","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea","text":"ConsentValue"}],"navigatorTitle":[{"text":"granted","kind":"identifier"}],"title":"granted","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Indicates the user granted consent.","type":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentValue":{"title":"ConsentValue","abstract":[{"type":"text","text":"A value in a Core consents dictionary."}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValue","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentValue"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentvalue","navigatorTitle":[{"text":"ConsentValue","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentValues/denied":{"url":"\/documentation\/chartboostcoresdk\/consentvalues\/denied","type":"topic","navigatorTitle":[{"text":"denied","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"denied"},{"kind":"text","text":": "},{"preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea","text":"ConsentValue","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/denied","abstract":[{"text":"Indicates the user denied consent.","type":"text"}],"title":"denied"},"doc://org.cocoapods.ChartboostCoreSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentValues":{"url":"\/documentation\/chartboostcoresdk\/consentvalues","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentValues"}],"navigatorTitle":[{"text":"ConsentValues","kind":"identifier"}],"type":"topic","title":"ConsentValues","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A namespace for Core’s predefined "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValue","isActive":true,"type":"reference"},{"text":" constants.","type":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentValues/doesNotApply":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/doesNotApply","title":"doesNotApply","role":"symbol","abstract":[{"text":"Indicates the standard does not apply.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"doesNotApply"}],"url":"\/documentation\/chartboostcoresdk\/consentvalues\/doesnotapply","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"doesNotApply","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea","text":"ConsentValue","kind":"typeIdentifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CBCConsentValues"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"CBCConsentValues","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"CBCConsentValues"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/denied","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/doesNotApply","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/granted"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBCConsentValues"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues~1granted\/title","value":"granted"},{"value":[{"text":"granted","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues~1granted\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues~1denied\/title","value":"denied"},{"value":[{"kind":"identifier","text":"denied"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues~1denied\/fragments"},{"value":"CBCConsentValues","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues\/fragments","value":[{"text":"CBCConsentValues","kind":"identifier"}]},{"value":"doesNotApply","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues~1doesNotApply\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues~1doesNotApply\/fragments","value":[{"text":"doesNotApply","kind":"identifier"}]}]}]}