{"metadata":{"role":"symbol","roleHeading":"Protocol","modules":[{"name":"ChartboostCoreSDK"}],"title":"ConsentAdapter","symbolKind":"protocol","externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentAdapter","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ConsentAdapter","kind":"identifier"}],"navigatorTitle":[{"text":"ConsentAdapter","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/consents","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/delegate","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/shouldCollectConsent","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/userDefaultsIABStrings"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/denyConsent(source:completion:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/grantConsent(source:completion:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/log(_:level:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/resetConsent(completion:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/showConsentDialog(_:from:completion:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/startObservingUserDefaultsIABStrings()"],"title":"Instance Methods"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CBCConsentAdapter) "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsentAdapter","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module","text":"Module","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModule"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Overview","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Core SDK identifies a CMP adapter from the list of modules it initializes based on conformance to this protocol."},{"text":" ","type":"text"},{"type":"text","text":"When the publisher uses Core’s CMP APIs (the "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/consent","isActive":true},{"type":"text","text":") method calls are forwarded to a Core module"},{"type":"text","text":" "},{"type":"text","text":"that conforms to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter"},{"text":", and such a module is also expected to report consent info changes back to the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Core SDK via its "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/delegate"},{"type":"text","text":" property."}]}]}],"kind":"symbol","abstract":[{"text":"The protocol to which a CMP adapter module must conform to.","type":"text"}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module"],"kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/consentadapter"]},{"paths":["\/documentation\/chartboostcoresdk\/consentadapter"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter/resetConsent(completion:)":{"type":"topic","role":"symbol","abstract":[{"text":"Informs the CMP that the given consent should be reset.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If the CMP does not support the "},{"type":"codeVoice","code":"reset()"},{"text":" function or the operation fails for any other reason, the completion","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"handler is executed with a "},{"type":"codeVoice","code":"false"},{"type":"text","text":" parameter."}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/resetConsent(completion:)","title":"resetConsent(completion:)","url":"\/documentation\/chartboostcoresdk\/consentadapter\/resetconsent(completion:)","kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resetConsent","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"succeeded"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"resetConsentWithCompletion:","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter/showConsentDialog(_:from:completion:)":{"role":"symbol","required":true,"type":"topic","abstract":[{"type":"text","text":"Instructs the CMP to present a consent dialog to the user for the purpose of collecting consent."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showConsentDialog"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"ConsentDialogType","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentDialogType"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"succeeded"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/showConsentDialog(_:from:completion:)","navigatorTitle":[{"text":"showConsentDialog:from:completion:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentadapter\/showconsentdialog(_:from:completion:)","title":"showConsentDialog(_:from:completion:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter/grantConsent(source:completion:)":{"type":"topic","title":"grantConsent(source:completion:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"grantConsent"},{"kind":"text","text":"("},{"text":"source","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConsentSource","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentSource"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"succeeded","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"required":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/grantConsent(source:completion:)","abstract":[{"text":"Informs the CMP that the user has granted consent.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This method should be used only when a custom consent dialog is presented to the user, thereby making the publisher"},{"type":"text","text":" "},{"type":"text","text":"responsible for the UI-side of collecting consent. In most cases "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/showConsentDialog(_:from:completion:)","isActive":true},{"type":"text","text":" should"},{"type":"text","text":" "},{"type":"text","text":"be used instead."},{"text":" ","type":"text"},{"type":"text","text":"If the CMP does not support custom consent dialogs or the operation fails for any other reason, the completion"},{"type":"text","text":" "},{"text":"handler is executed with a ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" parameter."}],"navigatorTitle":[{"kind":"identifier","text":"grantConsentWithSource:completion:"}],"url":"\/documentation\/chartboostcoresdk\/consentadapter\/grantconsent(source:completion:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Module":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Module","kind":"identifier"}],"kind":"symbol","title":"Module","url":"\/documentation\/chartboostcoresdk\/module","type":"topic","abstract":[{"type":"text","text":"The protocol to which all Chartboost Core modules must conform to."}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module","role":"symbol","navigatorTitle":[{"text":"Module","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter/shouldCollectConsent":{"type":"topic","role":"symbol","title":"shouldCollectConsent","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/shouldCollectConsent","url":"\/documentation\/chartboostcoresdk\/consentadapter\/shouldcollectconsent","abstract":[{"text":"Indicates whether the CMP has determined that consent should be collected from the user.","type":"text"}],"kind":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldCollectConsent"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"shouldCollectConsent"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapterDelegate":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ConsentAdapterDelegate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapterDelegate","abstract":[{"text":"The delegate of a ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","isActive":true,"type":"reference"},{"text":" module.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It should get notified whenever any change happens in the CMP consent."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConsentAdapterDelegate"}],"url":"\/documentation\/chartboostcoresdk\/consentadapterdelegate","title":"ConsentAdapterDelegate"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/consent":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The CMP in charge of handling user consent."}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"consent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentManagementPlatform","text":"ConsentManagementPlatform"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/consent","navigatorTitle":[{"text":"consent","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/chartboostcore\/consent","title":"consent"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter/consents":{"type":"topic","required":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/consents","abstract":[{"text":"Current user consent info as determined by the CMP.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"consents","kind":"identifier"},{"kind":"text","text":": ["},{"text":"ConsentKey","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea","text":"ConsentValue","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"consents"}],"url":"\/documentation\/chartboostcoresdk\/consentadapter\/consents","title":"consents"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter/userDefaultsIABStrings":{"title":"userDefaultsIABStrings","abstract":[{"text":"Obtains the IAB consent strings currently stored in UserDefaults.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the CMP follows the IAB standard this can be used to obtain all the relevant IAB strings already mapped"},{"text":" ","type":"text"},{"type":"text","text":"to Core’s "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","isActive":true},{"text":" constants.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/userDefaultsIABStrings","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"userDefaultsIABStrings","kind":"identifier"},{"kind":"text","text":": ["},{"text":"ConsentKey","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"ConsentValue","preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea"},{"kind":"text","text":"]"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentadapter\/userdefaultsiabstrings","type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter/delegate":{"title":"delegate","url":"\/documentation\/chartboostcoresdk\/consentadapter\/delegate","required":true,"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"abstract":[{"text":"The delegate to be notified whenever any change happens in the CMP consent info.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This delegate is set by Core SDK and is an essential communication channel between Core and the CMP."},{"text":" ","type":"text"},{"type":"text","text":"Adapters should not set it themselves."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentAdapterDelegate","kind":"typeIdentifier","text":"ConsentAdapterDelegate"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter/startObservingUserDefaultsIABStrings()":{"url":"\/documentation\/chartboostcoresdk\/consentadapter\/startobservinguserdefaultsiabstrings()","abstract":[{"text":"Adds an observer to get notified whenever IAB strings stored in UserDefaults change.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If the CMP follows the IAB standard this can be used to start observing consent changes"},{"type":"text","text":" "},{"type":"text","text":"on initialization and have chages automatically trigger the appropriate "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapterDelegate"},{"text":" ","type":"text"},{"type":"text","text":"methods."}],"title":"startObservingUserDefaultsIABStrings()","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/startObservingUserDefaultsIABStrings()","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startObservingUserDefaultsIABStrings","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"keyword","text":"Any"}],"role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ConsentAdapter","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","abstract":[{"text":"The protocol to which a CMP adapter module must conform to.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ConsentAdapter","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/consentadapter","title":"ConsentAdapter"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter/denyConsent(source:completion:)":{"title":"denyConsent(source:completion:)","url":"\/documentation\/chartboostcoresdk\/consentadapter\/denyconsent(source:completion:)","required":true,"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/denyConsent(source:completion:)","navigatorTitle":[{"kind":"identifier","text":"denyConsentWithSource:completion:"}],"type":"topic","abstract":[{"type":"text","text":"Informs the CMP that the user has denied consent."},{"type":"text","text":" "},{"type":"text","text":"This method should be used only when a custom consent dialog is presented to the user, thereby making the publisher"},{"type":"text","text":" "},{"text":"responsible for the UI-side of collecting consent. In most cases ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/showConsentDialog(_:from:completion:)"},{"type":"text","text":" should"},{"text":" ","type":"text"},{"type":"text","text":"be used instead."},{"type":"text","text":" "},{"text":"If the CMP does not support custom consent dialogs or the operation fails for any other reason, the completion","type":"text"},{"type":"text","text":" "},{"text":"handler is executed with a ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" parameter."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"denyConsent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"source","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ConsentSource","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentSource"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"succeeded","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentKey":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsentKey","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentkey","title":"ConsentKey","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentKey","abstract":[{"text":"A key in a Core consents dictionary.","type":"text"}],"navigatorTitle":[{"text":"ConsentKey","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter/log(_:level:)":{"title":"log(_:level:)","url":"\/documentation\/chartboostcoresdk\/consentadapter\/log(_:level:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/log(_:level:)","abstract":[{"text":"Logs a message using the Core SDK’s internal logging system.","type":"text"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"log","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"level"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"LogLevel","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCLogLevel"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"CBCConsentAdapter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"CBCConsentAdapter","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"CBCConsentAdapter","kind":"identifier"}]},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/consents","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/delegate","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/shouldCollectConsent"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/denyConsent(source:completion:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/grantConsent(source:completion:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/resetConsent(completion:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter\/showConsentDialog(_:from:completion:)"]}],"path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBCConsentAdapter","kind":"identifier"},{"kind":"text","text":" <"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module","text":"CBCModule","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModule","kind":"typeIdentifier"},{"kind":"text","text":">"}]}],"kind":"declarations"},"op":"replace"},{"value":"resetConsentWithCompletion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1resetConsent(completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"resetConsentWithCompletion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1resetConsent(completion:)\/fragments"},{"value":"showConsentDialog:from:completion:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1showConsentDialog(_:from:completion:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"showConsentDialog:from:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1showConsentDialog(_:from:completion:)\/fragments","op":"replace"},{"value":"grantConsentWithSource:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1grantConsent(source:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"grantConsentWithSource:completion:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1grantConsent(source:completion:)\/fragments"},{"value":"CBCModule","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/title"},{"value":[{"text":"CBCModule","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1shouldCollectConsent\/title","value":"shouldCollectConsent","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"shouldCollectConsent"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1shouldCollectConsent\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapterDelegate\/title","value":"CBCConsentAdapterDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapterDelegate\/fragments","value":[{"kind":"identifier","text":"CBCConsentAdapterDelegate"}]},{"value":"consent","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1consent\/title"},{"value":[{"kind":"identifier","text":"consent"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1consent\/fragments","op":"replace"},{"value":"consents","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1consents\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1consents\/fragments","value":[{"kind":"identifier","text":"consents"}]},{"op":"replace","value":"delegate","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1delegate\/title"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1delegate\/fragments","op":"replace"},{"value":"CBCConsentAdapter","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/fragments","value":[{"text":"CBCConsentAdapter","kind":"identifier"}],"op":"replace"},{"value":"denyConsentWithSource:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1denyConsent(source:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"denyConsentWithSource:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter~1denyConsent(source:completion:)\/fragments"}]}]}