{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(CBCConsentManagementPlatform) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsentManagementPlatform"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","text":"Overview","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Note that a "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","type":"reference","isActive":true},{"text":" module must be integrated to enable Core’s","type":"text"},{"type":"text","text":" "},{"text":"All methods are no-ops unless a ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","type":"reference","isActive":true},{"type":"text","text":" Core module is integrated in the app and initialized."},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver"},{"type":"text","text":" objects passed on a call to "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/addObserver(_:)","type":"reference","isActive":true},{"type":"text","text":" will get a call to"},{"type":"text","text":" "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver\/onConsentModuleReady(initialConsents:)"},{"type":"text","text":" when the "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","type":"reference"},{"type":"text","text":" is initialized"},{"type":"text","text":" "},{"type":"text","text":"and the "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform","isActive":true,"type":"reference"},{"type":"text","text":" is ready to be used."}],"type":"paragraph"}]}],"kind":"symbol","sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/shouldCollectConsent"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/addObserver(_:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/denyConsent(source:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/denyConsent(source:completion:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/grantConsent(source:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/grantConsent(source:completion:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/removeObserver(_:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/resetConsent()","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/resetConsent(completion:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:completion:)"],"title":"Instance Methods"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ConsentManagementPlatform"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsentManagementPlatform"}],"modules":[{"name":"ChartboostCoreSDK"}],"roleHeading":"Protocol","symbolKind":"protocol","externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentManagementPlatform","title":"ConsentManagementPlatform"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform","interfaceLanguage":"swift"},"abstract":[{"text":"Chartboost Core’s CMP in charge of handling user consent management.","type":"text"},{"text":" ","type":"text"},{"text":"Chartboost Core defines a unified API for publishers to request and query user consent,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and relies on a 3rd-party CMP SDK to provide the CMP functionality."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"]]},"variants":[{"paths":["\/documentation\/chartboostcoresdk\/consentmanagementplatform"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/consentmanagementplatform"]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentObserver":{"title":"ConsentObserver","url":"\/documentation\/chartboostcoresdk\/consentobserver","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsentObserver","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"An observer that gets notified whenever any change happens in the CMP consent info."}],"navigatorTitle":[{"kind":"identifier","text":"ConsentObserver"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/resetConsent(completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resetConsent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"succeeded","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"resetConsentWithCompletion:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/resetconsent(completion:)","type":"topic","kind":"symbol","title":"resetConsent(completion:)","abstract":[{"type":"text","text":"Informs the CMP that the given consent should be reset."},{"text":" ","type":"text"},{"type":"text","text":"If the CMP does not support the "},{"type":"codeVoice","code":"reset()"},{"text":" function or the operation fails for any other reason, the completion","type":"text"},{"type":"text","text":" "},{"text":"handler is executed with a ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" parameter."}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/resetConsent(completion:)","required":true},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/grantConsent(source:)":{"type":"topic","title":"grantConsent(source:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"grantConsent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentSource","text":"ConsentSource"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/grantConsent(source:)","abstract":[{"type":"text","text":"Informs the CMP that the user has granted consent."},{"text":" ","type":"text"},{"type":"text","text":"This method should be used only when a custom consent dialog is presented to the user, thereby making the publisher"},{"type":"text","text":" "},{"text":"responsible for the UI-side of collecting consent. In most cases ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:completion:)","isActive":true,"type":"reference"},{"text":" should","type":"text"},{"type":"text","text":" "},{"text":"be used instead.","type":"text"}],"url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/grantconsent(source:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/showConsentDialog(_:from:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showConsentDialog"},{"text":"(","kind":"text"},{"text":"ConsentDialogType","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentDialogType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"succeeded","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"type":"topic","title":"showConsentDialog(_:from:completion:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:completion:)","required":true,"navigatorTitle":[{"text":"showConsentDialog:from:completion:","kind":"identifier"}],"abstract":[{"text":"Instructs the CMP to present a consent dialog to the user for the purpose of collecting consent.","type":"text"}],"url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/showconsentdialog(_:from:completion:)","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/grantConsent(source:completion:)":{"url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/grantconsent(source:completion:)","kind":"symbol","type":"topic","title":"grantConsent(source:completion:)","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/grantConsent(source:completion:)","navigatorTitle":[{"text":"grantConsentWithSource:completion:","kind":"identifier"}],"abstract":[{"text":"Informs the CMP that the user has granted consent.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This method should be used only when a custom consent dialog is presented to the user, thereby making the publisher"},{"text":" ","type":"text"},{"text":"responsible for the UI-side of collecting consent. In most cases ","type":"text"},{"type":"codeVoice","code":"showConsentDialog(_:from:completion:)"},{"text":" should","type":"text"},{"type":"text","text":" "},{"text":"be used instead.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If the CMP does not support custom consent dialogs or the operation fails for any other reason, the completion"},{"text":" ","type":"text"},{"type":"text","text":"handler is executed with a "},{"code":"false","type":"codeVoice"},{"type":"text","text":" parameter."}],"required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"grantConsent"},{"text":"(","kind":"text"},{"text":"source","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ConsentSource","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentSource","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"succeeded"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/denyConsent(source:)":{"title":"denyConsent(source:)","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/denyconsent(source:)","role":"symbol","abstract":[{"text":"Informs the CMP that the user has denied consent.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This method should be used only when a custom consent dialog is presented to the user, thereby making the publisher"},{"type":"text","text":" "},{"type":"text","text":"responsible for the UI-side of collecting consent. In most cases "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:completion:)","isActive":true,"type":"reference"},{"type":"text","text":" should"},{"text":" ","type":"text"},{"type":"text","text":"be used instead."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/denyConsent(source:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"denyConsent","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"source"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentSource","kind":"typeIdentifier","text":"ConsentSource"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/removeObserver(_:)":{"type":"topic","title":"removeObserver(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeObserver"},{"text":"(","kind":"text"},{"text":"ConsentObserver","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentObserver","kind":"typeIdentifier"},{"kind":"text","text":")"}],"required":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/removeObserver(_:)","abstract":[{"text":"Removes a previously-added observer.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"removeObserver:"}],"url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/removeobserver(_:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/shouldCollectConsent":{"title":"shouldCollectConsent","type":"topic","kind":"symbol","required":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/shouldCollectConsent","navigatorTitle":[{"text":"shouldCollectConsent","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/shouldcollectconsent","abstract":[{"type":"text","text":"Indicates whether the CMP has determined that consent should be collected from the user."},{"text":" ","type":"text"},{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":" if no consent adapter module is available."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shouldCollectConsent"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/showConsentDialog(_:from:)":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:)","kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/showconsentdialog(_:from:)","type":"topic","abstract":[{"text":"Instructs the CMP to present a consent dialog to the user for the purpose of collecting consent.","type":"text"}],"title":"showConsentDialog(_:from:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"showConsentDialog","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentDialogType","text":"ConsentDialogType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/addObserver(_:)":{"role":"symbol","abstract":[{"text":"Adds an observer to receive notifications whenever the CMP consent info changes.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The Core SDK automatically notifies modules that conform to "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver","type":"reference","isActive":true},{"text":" about these changes, so there is no need","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to manually add Core modules as observers."}],"navigatorTitle":[{"text":"addObserver:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/addObserver(_:)","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/addobserver(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addObserver","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCConsentObserver","text":"ConsentObserver","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","required":true,"title":"addObserver(_:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform","kind":"symbol","navigatorTitle":[{"text":"ConsentManagementPlatform","kind":"identifier"}],"title":"ConsentManagementPlatform","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform","abstract":[{"type":"text","text":"Chartboost Core’s CMP in charge of handling user consent management."},{"type":"text","text":" "},{"type":"text","text":"Chartboost Core defines a unified API for publishers to request and query user consent,"},{"type":"text","text":" "},{"text":"and relies on a 3rd-party CMP SDK to provide the CMP functionality.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsentManagementPlatform","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ConsentAdapter","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","abstract":[{"text":"The protocol to which a CMP adapter module must conform to.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ConsentAdapter","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/consentadapter","title":"ConsentAdapter"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/denyConsent(source:completion:)":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/denyConsent(source:completion:)","navigatorTitle":[{"text":"denyConsentWithSource:completion:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"denyConsent"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"source"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ConsentSource","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCConsentSource"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"succeeded"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"denyConsent(source:completion:)","kind":"symbol","type":"topic","required":true,"role":"symbol","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/denyconsent(source:completion:)","abstract":[{"text":"Informs the CMP that the user has denied consent.","type":"text"},{"type":"text","text":" "},{"text":"This method should be used only when a custom consent dialog is presented to the user, thereby making the publisher","type":"text"},{"type":"text","text":" "},{"text":"responsible for the UI-side of collecting consent. In most cases ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:completion:)"},{"text":" should","type":"text"},{"text":" ","type":"text"},{"text":"be used instead.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the CMP does not support custom consent dialogs or the operation fails for any other reason, the completion"},{"type":"text","text":" "},{"text":"handler is executed with a ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" parameter.","type":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/resetConsent()":{"title":"resetConsent()","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/resetconsent()","role":"symbol","abstract":[{"type":"text","text":"Informs the CMP that the given consent should be reset."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/resetConsent()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resetConsent","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentObserver/onConsentModuleReady(initialConsents:)":{"title":"onConsentModuleReady(initialConsents:)","url":"\/documentation\/chartboostcoresdk\/consentobserver\/onconsentmoduleready(initialconsents:)","type":"topic","required":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentObserver\/onConsentModuleReady(initialConsents:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConsentModuleReady"},{"text":"(","kind":"text"},{"text":"initialConsents","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"ConsentKey","kind":"typeIdentifier","preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya"},{"kind":"text","text":" : "},{"text":"ConsentValue","preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"role":"symbol","abstract":[{"type":"text","text":"Called when the "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","isActive":true,"type":"reference"},{"type":"text","text":" module is initialized and the "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform","isActive":true},{"text":" object","type":"text"},{"text":" ","type":"text"},{"text":"is ready to be used.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"At this moment "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents"},{"type":"text","text":" will have proper values and methods like"},{"text":" ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:)","type":"reference","isActive":true},{"type":"text","text":" will no longer be no-ops."}],"navigatorTitle":[{"text":"onConsentModuleReadyWithInitialConsents:","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentManagementPlatform/consents":{"title":"consents","url":"\/documentation\/chartboostcoresdk\/consentmanagementplatform\/consents","type":"topic","required":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"consents","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:17ChartboostCoreSDK10ConsentKeya","text":"ConsentKey","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea","kind":"typeIdentifier","text":"ConsentValue"},{"kind":"text","text":"]"}],"role":"symbol","abstract":[{"type":"text","text":"Current user consent info as determined by the CMP."}],"navigatorTitle":[{"text":"consents","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"CBCConsentManagementPlatform"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"CBCConsentManagementPlatform"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"CBCConsentManagementPlatform","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/consents","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/shouldCollectConsent"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/addObserver(_:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/denyConsent(source:completion:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/grantConsent(source:completion:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/removeObserver(_:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/resetConsent(completion:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentManagementPlatform\/showConsentDialog(_:from:completion:)"]}],"path":"\/topicSections","op":"replace"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBCConsentManagementPlatform"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver\/title","op":"replace","value":"CBCConsentObserver"},{"value":[{"kind":"identifier","text":"CBCConsentObserver"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1resetConsent(completion:)\/title","value":"resetConsentWithCompletion:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"resetConsentWithCompletion:"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1resetConsent(completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1showConsentDialog(_:from:completion:)\/title","op":"replace","value":"showConsentDialog:from:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1showConsentDialog(_:from:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"showConsentDialog:from:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1grantConsent(source:completion:)\/title","value":"grantConsentWithSource:completion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1grantConsent(source:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"grantConsentWithSource:completion:"}],"op":"replace"},{"value":"removeObserver:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1removeObserver(_:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"removeObserver:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1removeObserver(_:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1shouldCollectConsent\/title","value":"shouldCollectConsent","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1shouldCollectConsent\/fragments","value":[{"kind":"identifier","text":"shouldCollectConsent"}],"op":"replace"},{"value":"addObserver:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1addObserver(_:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"addObserver:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1addObserver(_:)\/fragments"},{"value":"CBCConsentManagementPlatform","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/title","op":"replace"},{"op":"replace","value":[{"text":"CBCConsentManagementPlatform","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/title","value":"CBCConsentAdapter","op":"replace"},{"op":"replace","value":[{"text":"CBCConsentAdapter","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/fragments"},{"value":"denyConsentWithSource:completion:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1denyConsent(source:completion:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"denyConsentWithSource:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1denyConsent(source:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver~1onConsentModuleReady(initialConsents:)\/title","value":"onConsentModuleReadyWithInitialConsents:"},{"value":[{"kind":"text","text":"- "},{"text":"onConsentModuleReadyWithInitialConsents:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentObserver~1onConsentModuleReady(initialConsents:)\/fragments"},{"value":"consents","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1consents\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentManagementPlatform~1consents\/fragments","op":"replace","value":[{"kind":"identifier","text":"consents"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}