{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"]]},"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentSource"}],"modules":[{"name":"ChartboostCoreSDK"}],"role":"symbol","externalID":"c:@M@ChartboostCoreSDK@E@CBCConsentSource","navigatorTitle":[{"text":"ConsentSource","kind":"identifier"}],"roleHeading":"Enumeration","symbolKind":"enum","title":"ConsentSource"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/consentsource"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/consentsource"]}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SQ","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SH","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SY"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"abstract":[{"text":"The source of a consent change.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource"},"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource\/developer","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource\/user"],"title":"Enumeration Cases"},{"anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource\/init(rawValue:)"],"title":"Initializers","generated":true},{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource\/description"],"title":"Instance Properties"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource\/Equatable-Implementations","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(CBCConsentSource) "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentSource"}]}]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s23CustomStringConvertibleP"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentSource/RawRepresentable-Implementations":{"url":"\/documentation\/chartboostcoresdk\/consentsource\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource\/RawRepresentable-Implementations","type":"topic","abstract":[],"title":"RawRepresentable Implementations","role":"collectionGroup"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentSource/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource\/init(rawValue:)","role":"symbol","url":"\/documentation\/chartboostcoresdk\/consentsource\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","abstract":[]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentSource":{"title":"ConsentSource","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsentSource"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentsource","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource","role":"symbol","type":"topic","navigatorTitle":[{"text":"ConsentSource","kind":"identifier"}],"abstract":[{"type":"text","text":"The source of a consent change."}]},"doc://org.cocoapods.ChartboostCoreSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SH"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SQ"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentSource/user":{"abstract":[{"type":"text","text":"The consent was collected from the user as a result of an explicit user action."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"user"}],"kind":"symbol","type":"topic","title":"ConsentSource.user","url":"\/documentation\/chartboostcoresdk\/consentsource\/user","role":"symbol","navigatorTitle":[{"text":"CBCConsentSourceUser","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource\/user"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentSource/developer":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"developer","kind":"identifier"}],"abstract":[{"type":"text","text":"The consent was set by the developer without an explicit user action."}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource\/developer","navigatorTitle":[{"kind":"identifier","text":"CBCConsentSourceDeveloper"}],"title":"ConsentSource.developer","url":"\/documentation\/chartboostcoresdk\/consentsource\/developer"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentSource/description":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource\/description","url":"\/documentation\/chartboostcoresdk\/consentsource\/description","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","title":"description","abstract":[{"text":"The string representation of the consent source.","type":"text"}],"role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/SY":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentSource/Equatable-Implementations":{"url":"\/documentation\/chartboostcoresdk\/consentsource\/equatable-implementations","kind":"article","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource\/Equatable-Implementations","type":"topic","role":"collectionGroup","title":"Equatable Implementations"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"CBCConsentSource","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CBCConsentSource"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"CBCConsentSource","kind":"identifier"}]},{"value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource\/developer","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource\/user"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CBCConsentSource","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"CBCConsentSource","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource\/fragments","value":[{"text":"CBCConsentSource","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource\/navigatorTitle","value":[{"kind":"identifier","text":"CBCConsentSource"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource~1user\/title","value":"CBCConsentSourceUser"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource~1user\/fragments","value":[{"text":"CBCConsentSourceUser","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource~1developer\/title","value":"CBCConsentSourceDeveloper"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource~1developer\/fragments","value":[{"text":"CBCConsentSourceDeveloper","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}