{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver"},"kind":"symbol","variants":[{"paths":["\/documentation\/chartboostcoresdk\/environmentobserver"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/environmentobserver"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CBCEnvironmentObserver) "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EnvironmentObserver","kind":"identifier"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"An observer that gets notified when the value of some observable environment field changes."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"]]},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EnvironmentObserver","kind":"identifier"}],"modules":[{"name":"ChartboostCoreSDK"}],"symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"EnvironmentObserver"}],"role":"symbol","roleHeading":"Protocol","externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCEnvironmentObserver","title":"EnvironmentObserver"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver\/onChange(_:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/EnvironmentObserver/onChange(_:)":{"type":"topic","kind":"symbol","required":true,"url":"\/documentation\/chartboostcoresdk\/environmentobserver\/onchange(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onChange","kind":"identifier"},{"kind":"text","text":"("},{"text":"ObservableEnvironmentProperty","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCObservableEnvironmentProperty","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Called every time there’s a change in the value of one of the environment properties with a","type":"text"},{"text":" ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty"},{"text":" counterpart.","type":"text"}],"role":"symbol","title":"onChange(_:)","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver\/onChange(_:)","navigatorTitle":[{"text":"onChange:","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty","navigatorTitle":[{"text":"ObservableEnvironmentProperty","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty","kind":"symbol","title":"ObservableEnvironmentProperty","abstract":[{"text":"A constant that identifies an environment property that can be observed via a ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver","type":"reference","isActive":true},{"type":"text","text":"."}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ObservableEnvironmentProperty","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/EnvironmentObserver":{"url":"\/documentation\/chartboostcoresdk\/environmentobserver","navigatorTitle":[{"text":"EnvironmentObserver","kind":"identifier"}],"title":"EnvironmentObserver","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"EnvironmentObserver","kind":"identifier"}],"type":"topic","abstract":[{"text":"An observer that gets notified when the value of some observable environment field changes.","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","value":"CBCEnvironmentObserver","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","value":[{"text":"CBCEnvironmentObserver","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CBCEnvironmentObserver"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver\/onChange(_:)"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBCEnvironmentObserver"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"onChange:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver~1onChange(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver~1onChange(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onChange:"}]},{"value":"CBCObservableEnvironmentProperty","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty\/fragments","op":"replace","value":[{"text":"CBCObservableEnvironmentProperty","kind":"identifier"}]},{"value":[{"text":"CBCObservableEnvironmentProperty","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/title","value":"CBCEnvironmentObserver"},{"value":[{"text":"CBCEnvironmentObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/fragments"},{"value":[{"text":"CBCEnvironmentObserver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}