{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/debug","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/disabled","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/error","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/info","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/verbose","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/warning"]},{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/init(rawValue:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/init(string:)"],"title":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/description"],"title":"Instance Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/Comparable-Implementations","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/Equatable-Implementations","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/RawRepresentable-Implementations"],"generated":true}],"abstract":[{"text":"Log severity levels for the unified logging subsystem.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(CBCLogLevel) ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LogLevel"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/loglevel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/loglevel"]}],"metadata":{"externalID":"c:@M@ChartboostCoreSDK@E@CBCLogLevel","navigatorTitle":[{"text":"LogLevel","kind":"identifier"}],"roleHeading":"Enumeration","title":"LogLevel","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LogLevel","kind":"identifier"}],"modules":[{"name":"ChartboostCoreSDK"}],"symbolKind":"enum","role":"symbol"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/SL","doc:\/\/org.cocoapods.ChartboostCoreSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/Se","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SE","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SQ","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SH","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SY"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/SY":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://org.cocoapods.ChartboostCoreSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel":{"navigatorTitle":[{"text":"LogLevel","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"kind":"symbol","abstract":[{"text":"Log severity levels for the unified logging subsystem.","type":"text"}],"url":"\/documentation\/chartboostcoresdk\/loglevel","title":"LogLevel","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/Se":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/Se","title":"Swift.Decodable","type":"unresolvable"},"doc://org.cocoapods.ChartboostCoreSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel/verbose":{"navigatorTitle":[{"text":"CBCLogLevelVerbose","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/loglevel\/verbose","type":"topic","role":"symbol","abstract":[{"text":"Log very low level and\/or noisy information that may be useful during development or troubleshooting.","type":"text"}],"title":"LogLevel.verbose","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"verbose","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/verbose","kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel/disabled":{"navigatorTitle":[{"text":"CBCLogLevelDisabled","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/loglevel\/disabled","type":"topic","role":"symbol","abstract":[{"text":"No logging is expected to be performed.","type":"text"}],"title":"LogLevel.disabled","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"disabled","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/disabled","kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel/debug":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CBCLogLevelDebug"}],"title":"LogLevel.debug","url":"\/documentation\/chartboostcoresdk\/loglevel\/debug","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/debug","abstract":[{"type":"text","text":"Log information that may be useful during development or troubleshooting."}],"role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel/warning":{"navigatorTitle":[{"text":"CBCLogLevelWarning","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/loglevel\/warning","type":"topic","role":"symbol","abstract":[{"text":"Log information that may result in a failure.","type":"text"}],"title":"LogLevel.warning","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"warning","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/warning","kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel/description":{"abstract":[{"type":"text","text":"The string representation of the log level."}],"title":"description","url":"\/documentation\/chartboostcoresdk\/loglevel\/description","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/description"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel/RawRepresentable-Implementations":{"kind":"article","title":"RawRepresentable Implementations","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/RawRepresentable-Implementations","type":"topic","url":"\/documentation\/chartboostcoresdk\/loglevel\/rawrepresentable-implementations","role":"collectionGroup","abstract":[]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel/init(string:)":{"url":"\/documentation\/chartboostcoresdk\/loglevel\/init(string:)","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/init(string:)","title":"init(string:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"string"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel/Comparable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/Comparable-Implementations","url":"\/documentation\/chartboostcoresdk\/loglevel\/comparable-implementations","title":"Comparable Implementations","kind":"article","type":"topic","abstract":[]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel/error":{"navigatorTitle":[{"text":"CBCLogLevelError","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/error","abstract":[{"text":"Log information that communicates an error.","type":"text"}],"title":"LogLevel.error","url":"\/documentation\/chartboostcoresdk\/loglevel\/error","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel/Equatable-Implementations":{"url":"\/documentation\/chartboostcoresdk\/loglevel\/equatable-implementations","type":"topic","role":"collectionGroup","abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/Equatable-Implementations","kind":"article"},"doc://org.cocoapods.ChartboostCoreSDK/SE":{"title":"Swift.Encodable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SE","type":"unresolvable"},"doc://org.cocoapods.ChartboostCoreSDK/SL":{"title":"Swift.Comparable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SL","type":"unresolvable"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel/init(rawValue:)":{"url":"\/documentation\/chartboostcoresdk\/loglevel\/init(rawvalue:)","type":"topic","role":"symbol","abstract":[],"title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/init(rawValue:)","kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/SH":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel/info":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/info","abstract":[{"type":"text","text":"Log helpful, non-essential information."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBCLogLevelInfo"}],"title":"LogLevel.info","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/loglevel\/info"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"CBCLogLevel","path":"\/metadata\/title","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"CBCLogLevel","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"CBCLogLevel"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/debug","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/disabled","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/error","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/info","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/verbose","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/warning"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CBCLogLevel","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"CBCLogLevel","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CBCLogLevel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel~1verbose\/title","op":"replace","value":"CBCLogLevelVerbose"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel~1verbose\/fragments","value":[{"text":"CBCLogLevelVerbose","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel~1disabled\/title","op":"replace","value":"CBCLogLevelDisabled"},{"value":[{"text":"CBCLogLevelDisabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel~1disabled\/fragments"},{"value":"CBCLogLevelDebug","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel~1debug\/title"},{"op":"replace","value":[{"kind":"identifier","text":"CBCLogLevelDebug"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel~1debug\/fragments"},{"value":"CBCLogLevelWarning","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel~1warning\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel~1warning\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBCLogLevelWarning"}]},{"op":"replace","value":"CBCLogLevelError","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel~1error\/title"},{"value":[{"kind":"identifier","text":"CBCLogLevelError"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel~1error\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel~1info\/title","value":"CBCLogLevelInfo","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel~1info\/fragments","value":[{"kind":"identifier","text":"CBCLogLevelInfo"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}