{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(CBCModuleObserver) "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ModuleObserver","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"navigatorTitle":[{"text":"ModuleObserver","kind":"identifier"}],"externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCModuleObserver","modules":[{"name":"ChartboostCoreSDK"}],"roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ModuleObserver","kind":"identifier"}],"title":"ModuleObserver","symbolKind":"protocol","role":"symbol"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleObserver","interfaceLanguage":"swift"},"abstract":[{"text":"An observer to be notified whenever a Core module finishes initialization.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/moduleobserver"]},{"paths":["\/documentation\/chartboostcoresdk\/moduleobserver"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleObserver\/onModuleInitializationCompleted(_:)"]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleObserver":{"type":"topic","title":"ModuleObserver","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleObserver","abstract":[{"text":"An observer to be notified whenever a Core module finishes initialization.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModuleObserver"}],"role":"symbol","url":"\/documentation\/chartboostcoresdk\/moduleobserver","navigatorTitle":[{"kind":"identifier","text":"ModuleObserver"}],"kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleObserver/onModuleInitializationCompleted(_:)":{"navigatorTitle":[{"text":"onModuleInitializationCompleted:","kind":"identifier"}],"abstract":[{"text":"Called whenever a module is initialized by the Chartboost Core SDK.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onModuleInitializationCompleted"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCModuleInitializationResult","kind":"typeIdentifier","text":"ModuleInitializationResult"},{"kind":"text","text":")"}],"required":true,"kind":"symbol","type":"topic","url":"\/documentation\/chartboostcoresdk\/moduleobserver\/onmoduleinitializationcompleted(_:)","title":"onModuleInitializationCompleted(_:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleObserver\/onModuleInitializationCompleted(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"CBCModuleObserver"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"CBCModuleObserver","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"CBCModuleObserver","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleObserver\/onModuleInitializationCompleted(_:)"]}],"path":"\/topicSections","op":"replace"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBCModuleObserver"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleObserver\/title","value":"CBCModuleObserver","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleObserver\/fragments","value":[{"text":"CBCModuleObserver","kind":"identifier"}],"op":"replace"},{"value":"onModuleInitializationCompleted:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleObserver~1onModuleInitializationCompleted(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleObserver~1onModuleInitializationCompleted(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onModuleInitializationCompleted:"}]}]}]}