{"abstract":[{"type":"text","text":"The protocol to which all Chartboost Core modules must conform to."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CBCModule) "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Module","kind":"identifier"}]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"Module"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Module"}],"modules":[{"name":"ChartboostCoreSDK"}],"roleHeading":"Protocol","symbolKind":"protocol","externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCModule","title":"Module"},"kind":"symbol","sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module\/init(credentials:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module\/moduleID","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module\/moduleVersion"]},{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module\/initialize(configuration:completion:)"],"title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/module"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/module"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"]]},"relationshipsSections":[{"title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter"],"type":"inheritedBy"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module"},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Module/moduleVersion":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module\/moduleVersion","role":"symbol","required":true,"navigatorTitle":[{"text":"moduleVersion","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/module\/moduleversion","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"moduleVersion","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","title":"moduleVersion","abstract":[{"type":"text","text":"The version of the module."}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Module/moduleID":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"moduleID"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"required":true,"kind":"symbol","abstract":[{"text":"The module identifier.","type":"text"}],"url":"\/documentation\/chartboostcoresdk\/module\/moduleid","title":"moduleID","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module\/moduleID","type":"topic","role":"symbol","navigatorTitle":[{"text":"moduleID","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Module/initialize(configuration:completion:)":{"abstract":[{"type":"text","text":"Sets up the module to make it ready to be used."}],"role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"initializeWithConfiguration:completion:"}],"url":"\/documentation\/chartboostcoresdk\/module\/initialize(configuration:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCModuleConfiguration","text":"ModuleConfiguration"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"type":"topic","title":"initialize(configuration:completion:)","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module\/initialize(configuration:completion:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentAdapter":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ConsentAdapter","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter","abstract":[{"text":"The protocol to which a CMP adapter module must conform to.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ConsentAdapter","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/consentadapter","title":"ConsentAdapter"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Module":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Module","kind":"identifier"}],"kind":"symbol","title":"Module","url":"\/documentation\/chartboostcoresdk\/module","type":"topic","abstract":[{"type":"text","text":"The protocol to which all Chartboost Core modules must conform to."}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module","role":"symbol","navigatorTitle":[{"text":"Module","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Module/init(credentials:)":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module\/init(credentials:)","role":"symbol","required":true,"navigatorTitle":[{"text":"initWithCredentials:","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/module\/init(credentials:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"credentials"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}],"type":"topic","title":"init(credentials:)","abstract":[{"text":"The designated initializer for the module.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The Chartboost Core SDK will invoke this initializer when instantiating modules defined on"},{"type":"text","text":" "},{"text":"the dashboard through reflection.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"CBCModule"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"CBCModule"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"CBCModule"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module\/moduleID","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module\/moduleVersion"]},{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module\/init(credentials:)","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module\/initialize(configuration:completion:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentAdapter"],"title":"Inherited By","type":"inheritedBy"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"CBCModule","kind":"identifier"}],"languages":["occ"]}]}},{"value":"moduleVersion","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module~1moduleVersion\/title"},{"op":"replace","value":[{"kind":"identifier","text":"moduleVersion"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module~1moduleVersion\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module~1moduleID\/title","op":"replace","value":"moduleID"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module~1moduleID\/fragments","op":"replace","value":[{"text":"moduleID","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module~1initialize(configuration:completion:)\/title","value":"initializeWithConfiguration:completion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module~1initialize(configuration:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initializeWithConfiguration:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/title","value":"CBCConsentAdapter","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentAdapter\/fragments","value":[{"text":"CBCConsentAdapter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/title","value":"CBCModule"},{"value":[{"kind":"identifier","text":"CBCModule"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/fragments","op":"replace"},{"value":"initWithCredentials:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module~1init(credentials:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module~1init(credentials:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCredentials:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}