{"kind":"symbol","sections":[],"metadata":{"symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ModuleFactory","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ModuleFactory"}],"role":"symbol","title":"ModuleFactory","roleHeading":"Protocol","modules":[{"name":"ChartboostCoreSDK"}],"externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCModuleFactory"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"]]},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleFactory","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Factory to instantiate a Core module using its class name via reflection."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(CBCModuleFactory) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ModuleFactory","kind":"identifier"}],"languages":["swift"]}]},{"content":[{"anchor":"overview","level":2,"text":"Overview","type":"heading"},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Users can generally ignore this protocol. It is intended to be used"},{"text":" ","type":"text"},{"text":"only internally and by Chartboost’s Core Unity wrapper.","type":"text"}]}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleFactory\/makeModule(className:credentials:completion:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/modulefactory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/modulefactory"]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleFactory/makeModule(className:credentials:completion:)":{"kind":"symbol","type":"topic","title":"makeModule(className:credentials:completion:)","required":true,"role":"symbol","navigatorTitle":[{"text":"makeModuleWithClassName:credentials:completion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleFactory\/makeModule(className:credentials:completion:)","url":"\/documentation\/chartboostcoresdk\/modulefactory\/makemodule(classname:credentials:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"makeModule","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"className"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"credentials","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"Module","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModule"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Returns a module instantiate via reflection."}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleFactory":{"navigatorTitle":[{"text":"ModuleFactory","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/modulefactory","type":"topic","role":"symbol","abstract":[{"text":"Factory to instantiate a Core module using its class name via reflection.","type":"text"}],"title":"ModuleFactory","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ModuleFactory","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleFactory","kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"CBCModuleFactory"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBCModuleFactory"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"CBCModuleFactory","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleFactory\/makeModule(className:credentials:completion:)"]}]},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CBCModuleFactory","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleFactory~1makeModule(className:credentials:completion:)\/title","op":"replace","value":"makeModuleWithClassName:credentials:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleFactory~1makeModule(className:credentials:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"makeModuleWithClassName:credentials:completion:"}]},{"value":"CBCModuleFactory","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleFactory\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleFactory\/fragments","value":[{"text":"CBCModuleFactory","kind":"identifier"}]}]}]}