{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(CBCModuleConfiguration) "},{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ModuleConfiguration"}]}],"kind":"declarations"}],"sections":[],"metadata":{"navigatorTitle":[{"text":"ModuleConfiguration","kind":"identifier"}],"modules":[{"name":"ChartboostCoreSDK"}],"externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCModuleConfiguration","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ModuleConfiguration","kind":"identifier"}],"symbolKind":"class","title":"ModuleConfiguration","role":"symbol"},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleConfiguration","interfaceLanguage":"swift"},"abstract":[{"text":"Configuration with parameters needed by ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module","isActive":true},{"type":"text","text":" on initialization."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/moduleconfiguration"]},{"paths":["\/documentation\/chartboostcoresdk\/moduleconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChartboostCoreSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SQ","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleConfiguration\/chartboostAppID"],"title":"Instance Properties"}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleConfiguration":{"navigatorTitle":[{"text":"ModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/moduleconfiguration","type":"topic","role":"symbol","title":"ModuleConfiguration","abstract":[{"text":"Configuration with parameters needed by ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module"},{"type":"text","text":" on initialization."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleConfiguration","kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.ChartboostCoreSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.ChartboostCoreSDK/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.ChartboostCoreSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.ChartboostCoreSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Module":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Module","kind":"identifier"}],"kind":"symbol","title":"Module","url":"\/documentation\/chartboostcoresdk\/module","type":"topic","abstract":[{"type":"text","text":"The protocol to which all Chartboost Core modules must conform to."}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module","role":"symbol","navigatorTitle":[{"text":"Module","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleConfiguration/chartboostAppID":{"navigatorTitle":[{"text":"chartboostAppID","kind":"identifier"}],"abstract":[{"type":"text","text":"The Chartboost App ID which should match the value on the Chartboost dashboard."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chartboostAppID","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","type":"topic","url":"\/documentation\/chartboostcoresdk\/moduleconfiguration\/chartboostappid","title":"chartboostAppID","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleConfiguration\/chartboostAppID"},"doc://org.cocoapods.ChartboostCoreSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.ChartboostCoreSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"CBCModuleConfiguration","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"text":"CBCModuleConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"CBCModuleConfiguration","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleConfiguration\/chartboostAppID"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"CBCModuleConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleConfiguration\/title","value":"CBCModuleConfiguration"},{"value":[{"kind":"identifier","text":"CBCModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleConfiguration\/fragments"},{"value":"CBCModule","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/title"},{"op":"replace","value":[{"text":"CBCModule","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/fragments"},{"op":"replace","value":"chartboostAppID","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleConfiguration~1chartboostAppID\/title"},{"value":[{"text":"chartboostAppID","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleConfiguration~1chartboostAppID\/fragments"}]}]}