{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Network connection type."}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellular2G","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellular3G","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellular4G","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellular5G","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellularUnknown","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/unknown","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/wifi","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/wired"]},{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/CustomStringConvertible-Implementations","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/Equatable-Implementations","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SQ","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SH","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SY"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/networkconnectiontype"]},{"paths":["\/documentation\/chartboostcoresdk\/networkconnectiontype"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ChartboostCoreSDK@E@CBCNetworkConnectionType","navigatorTitle":[{"kind":"identifier","text":"NetworkConnectionType"}],"role":"symbol","symbolKind":"enum","modules":[{"name":"ChartboostCoreSDK"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NetworkConnectionType"}],"title":"NetworkConnectionType","roleHeading":"Enumeration"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(CBCNetworkConnectionType) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NetworkConnectionType","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType/cellular4G":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBCNetworkConnectionTypeCellular4G"}],"abstract":[{"text":"4G cellular network connection.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellular4G","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cellular4G","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/networkconnectiontype\/cellular4g","title":"NetworkConnectionType.cellular4G","type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType/cellular5G":{"navigatorTitle":[{"text":"CBCNetworkConnectionTypeCellular5G","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/networkconnectiontype\/cellular5g","type":"topic","role":"symbol","abstract":[{"text":"5G cellular network connection.","type":"text"}],"title":"NetworkConnectionType.cellular5G","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cellular5G"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellular5G","kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType/cellularUnknown":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cellularUnknown"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellularUnknown","kind":"symbol","abstract":[{"type":"text","text":"Cellular network connection of unknown generation."}],"title":"NetworkConnectionType.cellularUnknown","type":"topic","url":"\/documentation\/chartboostcoresdk\/networkconnectiontype\/cellularunknown","navigatorTitle":[{"text":"CBCNetworkConnectionTypeCellularUnknown","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType/wired":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"wired","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/networkconnectiontype\/wired","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/wired","abstract":[{"type":"text","text":"Wired network connection."}],"title":"NetworkConnectionType.wired","kind":"symbol","navigatorTitle":[{"text":"CBCNetworkConnectionTypeWired","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType/wifi":{"navigatorTitle":[{"text":"CBCNetworkConnectionTypeWifi","kind":"identifier"}],"title":"NetworkConnectionType.wifi","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"wifi","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/wifi","url":"\/documentation\/chartboostcoresdk\/networkconnectiontype\/wifi","abstract":[{"type":"text","text":"WiFi network connection."}],"role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType/cellular3G":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cellular3G","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/networkconnectiontype\/cellular3g","title":"NetworkConnectionType.cellular3G","type":"topic","role":"symbol","abstract":[{"type":"text","text":"3G cellular network connection."}],"navigatorTitle":[{"kind":"identifier","text":"CBCNetworkConnectionTypeCellular3G"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellular3G","kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","type":"topic","kind":"article","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/RawRepresentable-Implementations","abstract":[],"url":"\/documentation\/chartboostcoresdk\/networkconnectiontype\/rawrepresentable-implementations","role":"collectionGroup"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType/cellular2G":{"title":"NetworkConnectionType.cellular2G","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellular2G","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cellular2G","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBCNetworkConnectionTypeCellular2G"}],"url":"\/documentation\/chartboostcoresdk\/networkconnectiontype\/cellular2g","abstract":[{"type":"text","text":"2G cellular network connection."}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType/init(rawValue:)":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/init(rawValue:)","url":"\/documentation\/chartboostcoresdk\/networkconnectiontype\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","title":"init(rawValue:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType/CustomStringConvertible-Implementations":{"url":"\/documentation\/chartboostcoresdk\/networkconnectiontype\/customstringconvertible-implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/CustomStringConvertible-Implementations","abstract":[],"title":"CustomStringConvertible Implementations","kind":"article"},"doc://org.cocoapods.ChartboostCoreSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType/unknown":{"navigatorTitle":[{"text":"CBCNetworkConnectionTypeUnknown","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/unknown","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unknown","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/networkconnectiontype\/unknown","abstract":[{"text":"Unknown connection type.","type":"text"}],"title":"NetworkConnectionType.unknown"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType/Equatable-Implementations":{"kind":"article","title":"Equatable Implementations","url":"\/documentation\/chartboostcoresdk\/networkconnectiontype\/equatable-implementations","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/Equatable-Implementations","role":"collectionGroup"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/NetworkConnectionType":{"navigatorTitle":[{"text":"NetworkConnectionType","kind":"identifier"}],"title":"NetworkConnectionType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NetworkConnectionType"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType","url":"\/documentation\/chartboostcoresdk\/networkconnectiontype","abstract":[{"type":"text","text":"Network connection type."}],"role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/SY":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://org.cocoapods.ChartboostCoreSDK/SH":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"CBCNetworkConnectionType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"CBCNetworkConnectionType","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBCNetworkConnectionType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellular2G","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellular3G","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellular4G","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellular5G","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/cellularUnknown","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/unknown","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/wifi","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/NetworkConnectionType\/wired"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CBCNetworkConnectionType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1cellular4G\/title","value":"CBCNetworkConnectionTypeCellular4G"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1cellular4G\/fragments","op":"replace","value":[{"text":"CBCNetworkConnectionTypeCellular4G","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1cellular5G\/title","value":"CBCNetworkConnectionTypeCellular5G","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1cellular5G\/fragments","value":[{"kind":"identifier","text":"CBCNetworkConnectionTypeCellular5G"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1cellularUnknown\/title","value":"CBCNetworkConnectionTypeCellularUnknown","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1cellularUnknown\/fragments","value":[{"text":"CBCNetworkConnectionTypeCellularUnknown","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1wired\/title","value":"CBCNetworkConnectionTypeWired","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1wired\/fragments","value":[{"kind":"identifier","text":"CBCNetworkConnectionTypeWired"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1wifi\/title","op":"replace","value":"CBCNetworkConnectionTypeWifi"},{"value":[{"kind":"identifier","text":"CBCNetworkConnectionTypeWifi"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1wifi\/fragments"},{"value":"CBCNetworkConnectionTypeCellular3G","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1cellular3G\/title"},{"value":[{"text":"CBCNetworkConnectionTypeCellular3G","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1cellular3G\/fragments"},{"value":"CBCNetworkConnectionTypeCellular2G","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1cellular2G\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1cellular2G\/fragments","op":"replace","value":[{"text":"CBCNetworkConnectionTypeCellular2G","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1unknown\/title","op":"replace","value":"CBCNetworkConnectionTypeUnknown"},{"op":"replace","value":[{"text":"CBCNetworkConnectionTypeUnknown","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType~1unknown\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType\/title","value":"CBCNetworkConnectionType"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1NetworkConnectionType\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBCNetworkConnectionType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}