{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SQ","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SH","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SY"],"type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(CBCObservableEnvironmentProperty) ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObservableEnvironmentProperty"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"A constant that identifies an environment property that can be observed via a ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver","isActive":true,"type":"reference"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"ObservableEnvironmentProperty"}],"title":"ObservableEnvironmentProperty","role":"symbol","roleHeading":"Enumeration","externalID":"c:@M@ChartboostCoreSDK@E@CBCObservableEnvironmentProperty","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ObservableEnvironmentProperty","kind":"identifier"}],"modules":[{"name":"ChartboostCoreSDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/observableenvironmentproperty"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/observableenvironmentproperty"]}],"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/frameworkName","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/frameworkVersion","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/isUserUnderage","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/playerID","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/publisherAppID","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/publisherSessionID"]},{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/description"],"title":"Instance Properties"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/Equatable-Implementations","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/RawRepresentable-Implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"]]},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment/publisherAppID":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"publisherAppID","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/publisherAppID","title":"publisherAppID","required":true,"kind":"symbol","type":"topic","abstract":[{"text":"The publisher-defined application identifier set by the publisher through a call to ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/PublisherMetadata\/setPublisherAppID(_:)","isActive":true,"type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"publisherAppID","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/analyticsenvironment\/publisherappid","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty/frameworkName":{"url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/frameworkname","type":"topic","navigatorTitle":[{"text":"CBCObservableEnvironmentPropertyFrameworkName","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"frameworkName","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/frameworkName","abstract":[{"type":"text","text":"Property identifier associated to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/frameworkName"},{"text":".","type":"text"}],"title":"ObservableEnvironmentProperty.frameworkName"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment/frameworkVersion":{"navigatorTitle":[{"text":"frameworkVersion","kind":"identifier"}],"title":"frameworkVersion","url":"\/documentation\/chartboostcoresdk\/analyticsenvironment\/frameworkversion","kind":"symbol","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"frameworkVersion","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/frameworkVersion","abstract":[{"type":"text","text":"The framework version set by the publisher through a call to "},{"code":"PublisherMetadata\/setFramework(name:, version:)","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty/init(rawValue:)":{"url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/init(rawvalue:)","kind":"symbol","abstract":[],"title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/init(rawValue:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty":{"url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty","kind":"symbol","abstract":[{"type":"text","text":"A constant that identifies an environment property that can be observed via a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver"},{"text":".","type":"text"}],"title":"ObservableEnvironmentProperty","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObservableEnvironmentProperty"}],"navigatorTitle":[{"kind":"identifier","text":"ObservableEnvironmentProperty"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty/frameworkVersion":{"navigatorTitle":[{"text":"CBCObservableEnvironmentPropertyFrameworkVersion","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/frameworkversion","title":"ObservableEnvironmentProperty.frameworkVersion","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"frameworkVersion"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/frameworkVersion","abstract":[{"type":"text","text":"Property identifier associated to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/frameworkVersion"},{"type":"text","text":"."}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment/frameworkName":{"navigatorTitle":[{"text":"frameworkName","kind":"identifier"}],"required":true,"kind":"symbol","title":"frameworkName","abstract":[{"text":"The framework name set by the publisher through a call to ","type":"text"},{"code":"PublisherMetadata\/setFramework(name:, version:)","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"frameworkName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/frameworkName","url":"\/documentation\/chartboostcoresdk\/analyticsenvironment\/frameworkname"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty/publisherSessionID":{"navigatorTitle":[{"kind":"identifier","text":"CBCObservableEnvironmentPropertyPublisherSessionID"}],"kind":"symbol","title":"ObservableEnvironmentProperty.publisherSessionID","abstract":[{"text":"Property identifier associated to ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/frameworkName","isActive":true},{"text":".","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"publisherSessionID","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/publisherSessionID","url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/publishersessionid"},"doc://org.cocoapods.ChartboostCoreSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment/playerID":{"navigatorTitle":[{"text":"playerID","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/analyticsenvironment\/playerid","title":"playerID","kind":"symbol","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"playerID","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/playerID","abstract":[{"type":"text","text":"The player identifier set by the publisher through a call to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/PublisherMetadata\/setPlayerID(_:)"},{"type":"text","text":"."}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty/isUserUnderage":{"abstract":[{"type":"text","text":"Property identifier associated to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/isUserUnderage"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/isUserUnderage","type":"topic","title":"ObservableEnvironmentProperty.isUserUnderage","url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/isuserunderage","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBCObservableEnvironmentPropertyIsUserUnderage"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isUserUnderage"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/EnvironmentObserver":{"url":"\/documentation\/chartboostcoresdk\/environmentobserver","kind":"symbol","title":"EnvironmentObserver","abstract":[{"type":"text","text":"An observer that gets notified when the value of some observable environment field changes."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvironmentObserver"}],"navigatorTitle":[{"text":"EnvironmentObserver","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/rawrepresentable-implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/RawRepresentable-Implementations","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty/publisherAppID":{"navigatorTitle":[{"text":"CBCObservableEnvironmentPropertyPublisherAppID","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/publisherappid","title":"ObservableEnvironmentProperty.publisherAppID","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"publisherAppID","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/publisherAppID","abstract":[{"type":"text","text":"Property identifier associated to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/publisherAppID"},{"type":"text","text":"."}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.ChartboostCoreSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty/playerID":{"navigatorTitle":[{"text":"CBCObservableEnvironmentPropertyPlayerID","kind":"identifier"}],"title":"ObservableEnvironmentProperty.playerID","url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/playerid","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playerID"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/playerID","abstract":[{"type":"text","text":"Property identifier associated to "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/playerID"},{"type":"text","text":"."}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty/description":{"url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/description","title":"description","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/description","abstract":[{"type":"text","text":"The string representation of the property."}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/SH":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment/isUserUnderage":{"type":"topic","url":"\/documentation\/chartboostcoresdk\/analyticsenvironment\/isuserunderage","kind":"symbol","title":"isUserUnderage","navigatorTitle":[{"kind":"identifier","text":"isUserUnderage"}],"role":"symbol","abstract":[{"text":"Indicates whether the user is underage. This is determined by the latest value set by the publisher through","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"a call to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/PublisherMetadata\/setIsUserUnderage(_:)"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isUserUnderage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/isUserUnderage","required":true},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ObservableEnvironmentProperty/Equatable-Implementations":{"url":"\/documentation\/chartboostcoresdk\/observableenvironmentproperty\/equatable-implementations","title":"Equatable Implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/Equatable-Implementations","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"CBCObservableEnvironmentProperty","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CBCObservableEnvironmentProperty"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"CBCObservableEnvironmentProperty","kind":"identifier"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/frameworkName","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/frameworkVersion","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/isUserUnderage","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/playerID","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/publisherAppID","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ObservableEnvironmentProperty\/publisherSessionID"],"title":"Enumeration Cases"}],"op":"replace"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBCObservableEnvironmentProperty"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1publisherAppID\/title","value":"publisherAppID","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1publisherAppID\/fragments","op":"replace","value":[{"text":"publisherAppID","kind":"identifier"}]},{"value":"CBCObservableEnvironmentPropertyFrameworkName","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty~1frameworkName\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty~1frameworkName\/fragments","op":"replace","value":[{"kind":"identifier","text":"CBCObservableEnvironmentPropertyFrameworkName"}]},{"value":"frameworkVersion","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1frameworkVersion\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1frameworkVersion\/fragments","value":[{"kind":"identifier","text":"frameworkVersion"}],"op":"replace"},{"value":"CBCObservableEnvironmentProperty","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty\/title"},{"op":"replace","value":[{"text":"CBCObservableEnvironmentProperty","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty~1frameworkVersion\/title","value":"CBCObservableEnvironmentPropertyFrameworkVersion","op":"replace"},{"value":[{"text":"CBCObservableEnvironmentPropertyFrameworkVersion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty~1frameworkVersion\/fragments"},{"value":"frameworkName","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1frameworkName\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1frameworkName\/fragments","value":[{"text":"frameworkName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty~1publisherSessionID\/title","value":"CBCObservableEnvironmentPropertyPublisherSessionID","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty~1publisherSessionID\/fragments","value":[{"kind":"identifier","text":"CBCObservableEnvironmentPropertyPublisherSessionID"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1playerID\/title","value":"playerID"},{"value":[{"kind":"identifier","text":"playerID"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1playerID\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty~1isUserUnderage\/title","value":"CBCObservableEnvironmentPropertyIsUserUnderage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty~1isUserUnderage\/fragments","value":[{"text":"CBCObservableEnvironmentPropertyIsUserUnderage","kind":"identifier"}]},{"value":"CBCEnvironmentObserver","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/fragments","value":[{"text":"CBCEnvironmentObserver","kind":"identifier"}],"op":"replace"},{"value":"CBCObservableEnvironmentPropertyPublisherAppID","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty~1publisherAppID\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty~1publisherAppID\/fragments","op":"replace","value":[{"text":"CBCObservableEnvironmentPropertyPublisherAppID","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty~1playerID\/title","op":"replace","value":"CBCObservableEnvironmentPropertyPlayerID"},{"value":[{"kind":"identifier","text":"CBCObservableEnvironmentPropertyPlayerID"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ObservableEnvironmentProperty~1playerID\/fragments","op":"replace"},{"value":"isUserUnderage","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1isUserUnderage\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1isUserUnderage\/fragments","op":"replace","value":[{"kind":"identifier","text":"isUserUnderage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}