{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(CBCSDKConfiguration) ","kind":"text"},{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SDKConfiguration","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Configuration with parameters needed by the Chartboost Core SDK on initialization."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/init(chartboostAppID:modules:skippedModuleIDs:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/chartboostAppID","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/modules","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/skippedModuleIDs"]}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDKConfiguration"}],"externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCSDKConfiguration","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDKConfiguration","kind":"identifier"}],"roleHeading":"Class","title":"SDKConfiguration","modules":[{"name":"ChartboostCoreSDK"}]},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.ChartboostCoreSDK\/s7CVarArgP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SQ","doc:\/\/org.cocoapods.ChartboostCoreSDK\/SH"]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/sdkconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/sdkconfiguration"]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/SDKConfiguration/modules":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/modules","abstract":[{"text":"Optional list of modules to be initialized and managed by the Core SDK.","type":"text"},{"type":"text","text":" "},{"text":"In addition to these ","type":"text"},{"code":"moduels","type":"codeVoice"},{"text":", SDK fetches a list of modules to initialize along SDK initialization.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Modules already defined on Chartboost Core’s dashboard do not need to be provided here, otherwise"},{"text":" ","type":"text"},{"type":"text","text":"the fetched duplicates are skipped."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"modules"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/sdkconfiguration\/modules","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modules"},{"text":": [","kind":"text"},{"text":"Module","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModule"},{"kind":"text","text":"]"}],"title":"modules"},"doc://org.cocoapods.ChartboostCoreSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/initializeSDK(configuration:moduleObserver:)":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/initializeSDK(configuration:moduleObserver:)","abstract":[{"text":"Initializes the Core SDK and its modules.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initializeSDKWithConfiguration:moduleObserver:"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/chartboostcore\/initializesdk(configuration:moduleobserver:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initializeSDK"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCSDKConfiguration","text":"SDKConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"moduleObserver","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ModuleObserver","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModuleObserver"},{"kind":"text","text":"?)"}],"title":"initializeSDK(configuration:moduleObserver:)"},"doc://org.cocoapods.ChartboostCoreSDK/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s7CVarArgP"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/SDKConfiguration/chartboostAppID":{"url":"\/documentation\/chartboostcoresdk\/sdkconfiguration\/chartboostappid","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chartboostAppID","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","abstract":[{"type":"text","text":"The Chartboost App ID which should match the value on the Chartboost dashboard."},{"type":"text","text":" "},{"type":"text","text":"After the first successful initialization of Chartboost Core SDK, the "},{"code":"chartboostAppID","type":"codeVoice"},{"type":"text","text":" in subsequent"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/initializeSDK(configuration:moduleObserver:)","type":"reference","isActive":true},{"type":"text","text":" calls will be ignored."}],"title":"chartboostAppID","navigatorTitle":[{"text":"chartboostAppID","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/chartboostAppID"},"doc://org.cocoapods.ChartboostCoreSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/SDKConfiguration":{"url":"\/documentation\/chartboostcoresdk\/sdkconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDKConfiguration"}],"abstract":[{"type":"text","text":"Configuration with parameters needed by the Chartboost Core SDK on initialization."}],"type":"topic","title":"SDKConfiguration","navigatorTitle":[{"kind":"identifier","text":"SDKConfiguration"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/SDKConfiguration/init(chartboostAppID:modules:skippedModuleIDs:)":{"url":"\/documentation\/chartboostcoresdk\/sdkconfiguration\/init(chartboostappid:modules:skippedmoduleids:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"chartboostAppID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModule","text":"Module","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"skippedModuleIDs","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"abstract":[{"type":"text","text":"Initializes a configuration object."}],"type":"topic","title":"init(chartboostAppID:modules:skippedModuleIDs:)","navigatorTitle":[{"text":"initWithChartboostAppID:modules:skippedModuleIDs:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/init(chartboostAppID:modules:skippedModuleIDs:)"},"doc://org.cocoapods.ChartboostCoreSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.ChartboostCoreSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.ChartboostCoreSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/SDKConfiguration/skippedModuleIDs":{"type":"topic","navigatorTitle":[{"text":"skippedModuleIDs","kind":"identifier"}],"title":"skippedModuleIDs","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/skippedModuleIDs","kind":"symbol","abstract":[{"type":"text","text":"Identifiers of modules that should not be initialized along SDK initialization."},{"type":"text","text":" "},{"text":"Modules are not initialized along SDK initialization if their module IDs are on this list.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This is typically used for deferring the initialization of fetched modules defined on Chartboost Core’s"},{"type":"text","text":" "},{"type":"text","text":"dashboard, but it’s also effective against the "},{"code":"modules","type":"codeVoice"},{"type":"text","text":" in this SDK configuration."},{"type":"text","text":" "},{"type":"text","text":"Skipped modules do not trigger any "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleObserver"},{"text":" callback.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"skippedModuleIDs"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"url":"\/documentation\/chartboostcoresdk\/sdkconfiguration\/skippedmoduleids"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleObserver":{"type":"topic","title":"ModuleObserver","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleObserver","abstract":[{"text":"An observer to be notified whenever a Core module finishes initialization.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModuleObserver"}],"role":"symbol","url":"\/documentation\/chartboostcoresdk\/moduleobserver","navigatorTitle":[{"kind":"identifier","text":"ModuleObserver"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"CBCSDKConfiguration"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"CBCSDKConfiguration","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"CBCSDKConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/chartboostAppID","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/modules","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/skippedModuleIDs"]},{"identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/init(chartboostAppID:modules:skippedModuleIDs:)"],"title":"Instance Methods"}]},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.ChartboostCoreSDK\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CBCSDKConfiguration"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"value":"modules","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration~1modules\/title"},{"value":[{"kind":"identifier","text":"modules"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration~1modules\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1initializeSDK(configuration:moduleObserver:)\/title","value":"initializeSDKWithConfiguration:moduleObserver:"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1initializeSDK(configuration:moduleObserver:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"initializeSDKWithConfiguration:moduleObserver:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration~1chartboostAppID\/title","value":"chartboostAppID"},{"value":[{"text":"chartboostAppID","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration~1chartboostAppID\/fragments"},{"value":"CBCSDKConfiguration","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration\/fragments","value":[{"kind":"identifier","text":"CBCSDKConfiguration"}],"op":"replace"},{"op":"replace","value":"initWithChartboostAppID:modules:skippedModuleIDs:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration~1init(chartboostAppID:modules:skippedModuleIDs:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration~1init(chartboostAppID:modules:skippedModuleIDs:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithChartboostAppID:modules:skippedModuleIDs:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration~1skippedModuleIDs\/title","value":"skippedModuleIDs"},{"op":"replace","value":[{"kind":"identifier","text":"skippedModuleIDs"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration~1skippedModuleIDs\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleObserver\/title","value":"CBCModuleObserver"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleObserver\/fragments","value":[{"text":"CBCModuleObserver","kind":"identifier"}],"op":"replace"}]}]}