{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/consentvalues\/doesnotapply"]},{"paths":["\/documentation\/chartboostcoresdk\/consentvalues\/doesnotapply"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues"]]},"sections":[],"abstract":[{"type":"text","text":"Indicates the standard does not apply."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"doesNotApply"},{"kind":"text","text":": "},{"preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValue","text":"ConsentValue"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/doesNotApply","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"doesNotApply","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConsentValue","preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea"}],"title":"doesNotApply","navigatorTitle":[{"kind":"identifier","text":"doesNotApply"}],"symbolKind":"property","externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCConsentValues(cpy)doesNotApply","roleHeading":"Type Property","modules":[{"name":"ChartboostCoreSDK"}],"role":"symbol"},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentValue":{"title":"ConsentValue","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsentValue"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consentvalue","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValue","role":"symbol","type":"topic","navigatorTitle":[{"text":"ConsentValue","kind":"identifier"}],"abstract":[{"text":"A value in a Core consents dictionary.","type":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentValues/doesNotApply":{"title":"doesNotApply","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues\/doesNotApply","url":"\/documentation\/chartboostcoresdk\/consentvalues\/doesnotapply","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"doesNotApply","kind":"identifier"},{"kind":"text","text":": "},{"text":"ConsentValue","preciseIdentifier":"s:17ChartboostCoreSDK12ConsentValuea","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"doesNotApply"}],"abstract":[{"text":"Indicates the standard does not apply.","type":"text"}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentValues":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValues","navigatorTitle":[{"text":"ConsentValues","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/consentvalues","kind":"symbol","title":"ConsentValues","abstract":[{"text":"A namespace for Core’s predefined ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentValue","isActive":true},{"text":" constants.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConsentValues"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"doesNotApply","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"doesNotApply"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"text":"doesNotApply","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues~1doesNotApply\/title","op":"replace","value":"doesNotApply"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues~1doesNotApply\/fragments","value":[{"kind":"identifier","text":"doesNotApply"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues\/title","value":"CBCConsentValues"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues\/fragments","op":"replace","value":[{"text":"CBCConsentValues","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentValues\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CBCConsentValues"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}