{"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CBCConsentSourceDeveloper"}],"externalID":"c:@M@ChartboostCoreSDK@E@CBCConsentSource@CBCConsentSourceDeveloper","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"developer","kind":"identifier"}],"title":"ConsentSource.developer","roleHeading":"Case","modules":[{"name":"ChartboostCoreSDK"}]},"variants":[{"paths":["\/documentation\/chartboostcoresdk\/consentsource\/developer"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/consentsource\/developer"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"developer","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource\/developer","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The consent was set by the developer without an explicit user action."}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentSource":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource","navigatorTitle":[{"text":"ConsentSource","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsentSource","kind":"identifier"}],"title":"ConsentSource","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/chartboostcoresdk\/consentsource","abstract":[{"text":"The source of a consent change.","type":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsentSource/developer":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsentSource\/developer","abstract":[{"type":"text","text":"The consent was set by the developer without an explicit user action."}],"url":"\/documentation\/chartboostcoresdk\/consentsource\/developer","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"developer","kind":"identifier"}],"type":"topic","title":"ConsentSource.developer","kind":"symbol","navigatorTitle":[{"text":"CBCConsentSourceDeveloper","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"CBCConsentSourceDeveloper","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"CBCConsentSourceDeveloper","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"CBCConsentSourceDeveloper","kind":"identifier"}],"platforms":["iOS"]}]}},{"value":"CBCConsentSource","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource\/fragments","value":[{"kind":"identifier","text":"CBCConsentSource"}]},{"value":"CBCConsentSourceDeveloper","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource~1developer\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CBCConsentSourceDeveloper"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsentSource~1developer\/fragments","op":"replace"}]}]}