{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogEntry\/subsystem","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogEntry"]]},"metadata":{"externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCLogEntry(py)subsystem","navigatorTitle":[{"text":"subsystem","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"ChartboostCoreSDK"}],"title":"subsystem","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"subsystem","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","roleHeading":"Instance Property"},"abstract":[{"text":"A subsystem for the log.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/logentry\/subsystem"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/logentry\/subsystem"]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"subsystem","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"This value is used as the subsystem for "},{"type":"codeVoice","code":"OSLog(subsystem:category:)"},{"type":"text","text":" by "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsoleLogHandler","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogEntry":{"abstract":[{"type":"text","text":"An object containing information about a single log message."}],"navigatorTitle":[{"kind":"identifier","text":"LogEntry"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LogEntry","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/logentry","kind":"symbol","title":"LogEntry","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogEntry"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsoleLogHandler":{"title":"ConsoleLogHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsoleLogHandler"}],"abstract":[{"text":"A ","type":"text"},{"code":"LogHandler","type":"codeVoice"},{"text":" that logs to the console.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsoleLogHandler","role":"symbol","navigatorTitle":[{"text":"ConsoleLogHandler","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/consoleloghandler"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogEntry/subsystem":{"kind":"symbol","abstract":[{"text":"A subsystem for the log.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"subsystem"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogEntry\/subsystem","url":"\/documentation\/chartboostcoresdk\/logentry\/subsystem","title":"subsystem","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"subsystem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"subsystem"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"subsystem"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"subsystem","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogEntry\/title","value":"CBCLogEntry","op":"replace"},{"op":"replace","value":[{"text":"CBCLogEntry","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogEntry\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsoleLogHandler\/title","value":"CBCConsoleLogHandler","op":"replace"},{"value":[{"kind":"identifier","text":"CBCConsoleLogHandler"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsoleLogHandler\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogEntry~1subsystem\/title","value":"subsystem","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogEntry~1subsystem\/fragments","value":[{"text":"subsystem","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}