{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogHandler\/handle(_:)"},"metadata":{"title":"handle(_:)","required":true,"symbolKind":"method","role":"symbol","externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCLogHandler(im)handle:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handle"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCLogEntry","text":"LogEntry"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"handle:","kind":"identifier"}],"modules":[{"name":"ChartboostCoreSDK"}]},"sections":[],"kind":"symbol","abstract":[{"text":"Called on every handler previously registered with ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/attachLogHandler(_:)","isActive":true},{"type":"text","text":" to handle "},{"type":"codeVoice","code":"entry"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/chartboostcoresdk\/loghandler\/handle(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostcoresdk\/loghandler\/handle(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogHandler"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"entry","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogEntry","text":"LogEntry","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCLogEntry","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogHandler":{"title":"LogHandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogHandler"}],"abstract":[{"text":"The protocol for custom log handlers for the unified logging subsystem.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogHandler","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LogHandler"}],"url":"\/documentation\/chartboostcoresdk\/loghandler"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogEntry":{"abstract":[{"type":"text","text":"An object containing information about a single log message."}],"navigatorTitle":[{"kind":"identifier","text":"LogEntry"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LogEntry","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/logentry","kind":"symbol","title":"LogEntry","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogEntry"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/attachLogHandler(_:)":{"navigatorTitle":[{"kind":"identifier","text":"attachLogHandler:"}],"title":"attachLogHandler(_:)","kind":"symbol","abstract":[{"text":"Attach a custom logger handler to the logging system.","type":"text"}],"type":"topic","url":"\/documentation\/chartboostcoresdk\/chartboostcore\/attachloghandler(_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"attachLogHandler"},{"text":"(","kind":"text"},{"text":"LogHandler","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCLogHandler"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/attachLogHandler(_:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogHandler/handle(_:)":{"navigatorTitle":[{"kind":"identifier","text":"handle:"}],"title":"handle(_:)","kind":"symbol","abstract":[{"type":"text","text":"Called on every handler previously registered with "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/attachLogHandler(_:)","type":"reference","isActive":true},{"text":" to handle ","type":"text"},{"type":"codeVoice","code":"entry"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/chartboostcoresdk\/loghandler\/handle(_:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"handle","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCLogEntry","kind":"typeIdentifier","text":"LogEntry"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogHandler\/handle(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"handle:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handle:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"handle:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogEntry","text":"CBCLogEntry","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCLogEntry","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"entry","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"CBCLogHandler","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogHandler\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogHandler\/fragments","value":[{"kind":"identifier","text":"CBCLogHandler"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogEntry\/title","value":"CBCLogEntry","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"CBCLogEntry"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogEntry\/fragments"},{"op":"replace","value":"attachLogHandler:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1attachLogHandler(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1attachLogHandler(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"attachLogHandler:"}]},{"value":"handle:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogHandler~1handle(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"handle:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogHandler~1handle(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}