{"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"chartboostAppID","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"ChartboostCoreSDK"}],"externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCSDKConfiguration(py)chartboostAppID","title":"chartboostAppID","navigatorTitle":[{"kind":"identifier","text":"chartboostAppID"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/sdkconfiguration\/chartboostappid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/sdkconfiguration\/chartboostappid"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/chartboostAppID"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"chartboostAppID","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}]}],"abstract":[{"type":"text","text":"The Chartboost App ID which should match the value on the Chartboost dashboard."},{"text":" ","type":"text"},{"type":"text","text":"After the first successful initialization of Chartboost Core SDK, the "},{"code":"chartboostAppID","type":"codeVoice"},{"type":"text","text":" in subsequent"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/initializeSDK(configuration:moduleObserver:)","type":"reference"},{"type":"text","text":" calls will be ignored."}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/SDKConfiguration/chartboostAppID":{"url":"\/documentation\/chartboostcoresdk\/sdkconfiguration\/chartboostappid","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chartboostAppID","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","abstract":[{"type":"text","text":"The Chartboost App ID which should match the value on the Chartboost dashboard."},{"type":"text","text":" "},{"type":"text","text":"After the first successful initialization of Chartboost Core SDK, the "},{"code":"chartboostAppID","type":"codeVoice"},{"type":"text","text":" in subsequent"},{"type":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/initializeSDK(configuration:moduleObserver:)","type":"reference","isActive":true},{"type":"text","text":" calls will be ignored."}],"title":"chartboostAppID","navigatorTitle":[{"text":"chartboostAppID","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/chartboostAppID"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/initializeSDK(configuration:moduleObserver:)":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/initializeSDK(configuration:moduleObserver:)","abstract":[{"text":"Initializes the Core SDK and its modules.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initializeSDKWithConfiguration:moduleObserver:"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/chartboostcore\/initializesdk(configuration:moduleobserver:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initializeSDK"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCSDKConfiguration","text":"SDKConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"moduleObserver","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ModuleObserver","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModuleObserver"},{"kind":"text","text":"?)"}],"title":"initializeSDK(configuration:moduleObserver:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/SDKConfiguration":{"url":"\/documentation\/chartboostcoresdk\/sdkconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDKConfiguration"}],"abstract":[{"type":"text","text":"Configuration with parameters needed by the Chartboost Core SDK on initialization."}],"type":"topic","title":"SDKConfiguration","navigatorTitle":[{"kind":"identifier","text":"SDKConfiguration"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"chartboostAppID"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"chartboostAppID"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"chartboostAppID","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration~1chartboostAppID\/title","op":"replace","value":"chartboostAppID"},{"value":[{"kind":"identifier","text":"chartboostAppID"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration~1chartboostAppID\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1initializeSDK(configuration:moduleObserver:)\/title","value":"initializeSDKWithConfiguration:moduleObserver:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"initializeSDKWithConfiguration:moduleObserver:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1initializeSDK(configuration:moduleObserver:)\/fragments"},{"value":"CBCSDKConfiguration","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration\/title"},{"value":[{"kind":"identifier","text":"CBCSDKConfiguration"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}