{"abstract":[{"type":"text","text":"Initializes a configuration object."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/sdkconfiguration\/init(chartboostappid:modules:skippedmoduleids:)"]},{"paths":["\/documentation\/chartboostcoresdk\/sdkconfiguration\/init(chartboostappid:modules:skippedmoduleids:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"symbolKind":"init","roleHeading":"Initializer","externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCSDKConfiguration(im)initWithChartboostAppID:modules:skippedModuleIDs:","title":"init(chartboostAppID:modules:skippedModuleIDs:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"chartboostAppID","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"modules","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModule","text":"Module","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"skippedModuleIDs","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"role":"symbol","navigatorTitle":[{"text":"initWithChartboostAppID:modules:skippedModuleIDs:","kind":"identifier"}],"modules":[{"name":"ChartboostCoreSDK"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/init(chartboostAppID:modules:skippedModuleIDs:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"chartboostAppID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModule","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module","text":"Module"},{"text":"] = [], ","kind":"text"},{"kind":"externalParam","text":"skippedModuleIDs"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"] = [])","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The Chartboost App ID which should match the value on the Chartboost dashboard."}]}],"name":"chartboostAppID"},{"name":"modules","content":[{"inlineContent":[{"text":"Optional list of modules to be initialized and managed by the Core SDK.","type":"text"}],"type":"paragraph"}]},{"name":"skippedModuleIDs","content":[{"inlineContent":[{"type":"text","text":"Identifiers of modules that should not be initialized along SDK initialization."}],"type":"paragraph"}]}]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/SDKConfiguration":{"url":"\/documentation\/chartboostcoresdk\/sdkconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDKConfiguration"}],"abstract":[{"type":"text","text":"Configuration with parameters needed by the Chartboost Core SDK on initialization."}],"type":"topic","title":"SDKConfiguration","navigatorTitle":[{"kind":"identifier","text":"SDKConfiguration"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Module":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Module","kind":"identifier"}],"kind":"symbol","title":"Module","url":"\/documentation\/chartboostcoresdk\/module","type":"topic","abstract":[{"type":"text","text":"The protocol to which all Chartboost Core modules must conform to."}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module","role":"symbol","navigatorTitle":[{"text":"Module","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/SDKConfiguration/init(chartboostAppID:modules:skippedModuleIDs:)":{"url":"\/documentation\/chartboostcoresdk\/sdkconfiguration\/init(chartboostappid:modules:skippedmoduleids:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"chartboostAppID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModule","text":"Module","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"skippedModuleIDs","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"abstract":[{"type":"text","text":"Initializes a configuration object."}],"type":"topic","title":"init(chartboostAppID:modules:skippedModuleIDs:)","navigatorTitle":[{"text":"initWithChartboostAppID:modules:skippedModuleIDs:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/init(chartboostAppID:modules:skippedModuleIDs:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithChartboostAppID:modules:skippedModuleIDs:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithChartboostAppID:modules:skippedModuleIDs:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithChartboostAppID:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"chartboostAppID"},{"kind":"text","text":" "},{"text":"modules:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<id<CBCModule>>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"modules"},{"kind":"text","text":" "},{"kind":"identifier","text":"skippedModuleIDs:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSString *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"skippedModuleIDs"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration\/title","value":"CBCSDKConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"CBCSDKConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration\/fragments"},{"value":"CBCModule","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/title"},{"op":"replace","value":[{"text":"CBCModule","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/fragments"},{"value":"initWithChartboostAppID:modules:skippedModuleIDs:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration~1init(chartboostAppID:modules:skippedModuleIDs:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration~1init(chartboostAppID:modules:skippedModuleIDs:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithChartboostAppID:modules:skippedModuleIDs:","kind":"identifier"}]}]}]}