{"metadata":{"title":"modules","modules":[{"name":"ChartboostCoreSDK"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"modules"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModule","text":"Module"},{"text":"]","kind":"text"}],"symbolKind":"property","externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCSDKConfiguration(py)modules","role":"symbol"},"abstract":[{"type":"text","text":"Optional list of modules to be initialized and managed by the Core SDK."},{"type":"text","text":" "},{"type":"text","text":"In addition to these "},{"code":"moduels","type":"codeVoice"},{"type":"text","text":", SDK fetches a list of modules to initialize along SDK initialization."},{"text":" ","type":"text"},{"type":"text","text":"Modules already defined on Chartboost Core’s dashboard do not need to be provided here, otherwise"},{"text":" ","type":"text"},{"type":"text","text":"the fetched duplicates are skipped."}],"variants":[{"paths":["\/documentation\/chartboostcoresdk\/sdkconfiguration\/modules"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/sdkconfiguration\/modules"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/modules","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modules"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module","text":"Module","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModule"},{"text":"]","kind":"text"}]}]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/Module":{"role":"symbol","type":"topic","title":"Module","abstract":[{"text":"The protocol to which all Chartboost Core modules must conform to.","type":"text"}],"url":"\/documentation\/chartboostcoresdk\/module","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Module"}],"navigatorTitle":[{"text":"Module","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/Module"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/SDKConfiguration/modules":{"role":"symbol","url":"\/documentation\/chartboostcoresdk\/sdkconfiguration\/modules","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModule","text":"Module","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"modules"}],"type":"topic","title":"modules","abstract":[{"type":"text","text":"Optional list of modules to be initialized and managed by the Core SDK."},{"type":"text","text":" "},{"type":"text","text":"In addition to these "},{"type":"codeVoice","code":"moduels"},{"type":"text","text":", SDK fetches a list of modules to initialize along SDK initialization."},{"type":"text","text":" "},{"type":"text","text":"Modules already defined on Chartboost Core’s dashboard do not need to be provided here, otherwise"},{"type":"text","text":" "},{"text":"the fetched duplicates are skipped.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/modules","kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/SDKConfiguration":{"title":"SDKConfiguration","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration with parameters needed by the Chartboost Core SDK on initialization."}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/sdkconfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDKConfiguration"}],"navigatorTitle":[{"text":"SDKConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"modules","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"modules","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSArray<id<CBCModule>>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"modules"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/title","op":"replace","value":"CBCModule"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/fragments","value":[{"text":"CBCModule","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1Module\/navigatorTitle","value":[{"kind":"identifier","text":"CBCModule"}],"op":"replace"},{"op":"replace","value":"modules","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration~1modules\/title"},{"value":[{"text":"modules","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration~1modules\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration\/title","value":"CBCSDKConfiguration"},{"value":[{"text":"CBCSDKConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration\/navigatorTitle","value":[{"text":"CBCSDKConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}