{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"skippedModuleIDs"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]"}]}]}],"metadata":{"title":"skippedModuleIDs","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"skippedModuleIDs","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"skippedModuleIDs","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"ChartboostCoreSDK"}],"externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCSDKConfiguration(py)skippedModuleIDs","role":"symbol","roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/skippedModuleIDs","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Identifiers of modules that should not be initialized along SDK initialization."},{"text":" ","type":"text"},{"type":"text","text":"Modules are not initialized along SDK initialization if their module IDs are on this list."},{"type":"text","text":" "},{"text":"This is typically used for deferring the initialization of fetched modules defined on Chartboost Core’s","type":"text"},{"type":"text","text":" "},{"type":"text","text":"dashboard, but it’s also effective against the "},{"code":"modules","type":"codeVoice"},{"text":" in this SDK configuration.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Skipped modules do not trigger any "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleObserver"},{"text":" callback.","type":"text"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration"]]},"variants":[{"paths":["\/documentation\/chartboostcoresdk\/sdkconfiguration\/skippedmoduleids"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/sdkconfiguration\/skippedmoduleids"]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/SDKConfiguration":{"url":"\/documentation\/chartboostcoresdk\/sdkconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDKConfiguration"}],"abstract":[{"type":"text","text":"Configuration with parameters needed by the Chartboost Core SDK on initialization."}],"type":"topic","title":"SDKConfiguration","navigatorTitle":[{"kind":"identifier","text":"SDKConfiguration"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ModuleObserver":{"type":"topic","title":"ModuleObserver","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleObserver","abstract":[{"text":"An observer to be notified whenever a Core module finishes initialization.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ModuleObserver"}],"role":"symbol","url":"\/documentation\/chartboostcoresdk\/moduleobserver","navigatorTitle":[{"kind":"identifier","text":"ModuleObserver"}],"kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/SDKConfiguration/skippedModuleIDs":{"type":"topic","navigatorTitle":[{"text":"skippedModuleIDs","kind":"identifier"}],"title":"skippedModuleIDs","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/SDKConfiguration\/skippedModuleIDs","kind":"symbol","abstract":[{"type":"text","text":"Identifiers of modules that should not be initialized along SDK initialization."},{"type":"text","text":" "},{"text":"Modules are not initialized along SDK initialization if their module IDs are on this list.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This is typically used for deferring the initialization of fetched modules defined on Chartboost Core’s"},{"type":"text","text":" "},{"type":"text","text":"dashboard, but it’s also effective against the "},{"code":"modules","type":"codeVoice"},{"type":"text","text":" in this SDK configuration."},{"type":"text","text":" "},{"type":"text","text":"Skipped modules do not trigger any "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ModuleObserver"},{"text":" callback.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"skippedModuleIDs"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"url":"\/documentation\/chartboostcoresdk\/sdkconfiguration\/skippedmoduleids"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"skippedModuleIDs","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"skippedModuleIDs","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"text":" * ","kind":"text"},{"text":"skippedModuleIDs","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"CBCSDKConfiguration","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration\/fragments","value":[{"kind":"identifier","text":"CBCSDKConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleObserver\/title","op":"replace","value":"CBCModuleObserver"},{"value":[{"text":"CBCModuleObserver","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ModuleObserver\/fragments","op":"replace"},{"value":"skippedModuleIDs","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration~1skippedModuleIDs\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1SDKConfiguration~1skippedModuleIDs\/fragments","value":[{"kind":"identifier","text":"skippedModuleIDs"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}