{"abstract":[{"text":"Handle a ","type":"text"},{"type":"codeVoice","code":"LogEntry"},{"type":"text","text":" if the log level is sufficient for the desired output log level."},{"type":"text","text":" "},{"text":"On iOS 12 and later, logging is performed using ","type":"text"},{"code":"os_log","type":"codeVoice"},{"text":", otherwise no logging of any kind occurs.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsoleLogHandler\/handle(_:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"handle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"entry","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogEntry","text":"LogEntry","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCLogEntry"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/chartboostcoresdk\/consoleloghandler\/handle(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/consoleloghandler\/handle(_:)"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"handle(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCLogEntry","text":"LogEntry"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCConsoleLogHandler(im)handle:","role":"symbol","modules":[{"name":"ChartboostCoreSDK"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"handle:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsoleLogHandler"]]},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsoleLogHandler/handle(_:)":{"role":"symbol","navigatorTitle":[{"text":"handle:","kind":"identifier"}],"abstract":[{"type":"text","text":"Handle a "},{"type":"codeVoice","code":"LogEntry"},{"type":"text","text":" if the log level is sufficient for the desired output log level."},{"text":" ","type":"text"},{"type":"text","text":"On iOS 12 and later, logging is performed using "},{"type":"codeVoice","code":"os_log"},{"text":", otherwise no logging of any kind occurs.","type":"text"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/consoleloghandler\/handle(_:)","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsoleLogHandler\/handle(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handle"},{"kind":"text","text":"("},{"text":"LogEntry","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCLogEntry"},{"kind":"text","text":")"}],"type":"topic","title":"handle(_:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsoleLogHandler":{"title":"ConsoleLogHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConsoleLogHandler"}],"abstract":[{"text":"A ","type":"text"},{"code":"LogHandler","type":"codeVoice"},{"text":" that logs to the console.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsoleLogHandler","role":"symbol","navigatorTitle":[{"text":"ConsoleLogHandler","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/consoleloghandler"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogEntry":{"abstract":[{"type":"text","text":"An object containing information about a single log message."}],"navigatorTitle":[{"kind":"identifier","text":"LogEntry"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LogEntry","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/logentry","kind":"symbol","title":"LogEntry","role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogEntry"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"handle:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"handle:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"handle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogEntry","text":"CBCLogEntry","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCLogEntry"},{"text":" *) ","kind":"text"},{"text":"entry","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"handle:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsoleLogHandler~1handle(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"handle:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsoleLogHandler~1handle(_:)\/fragments"},{"value":"CBCConsoleLogHandler","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsoleLogHandler\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsoleLogHandler\/fragments","value":[{"kind":"identifier","text":"CBCConsoleLogHandler"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogEntry\/title","value":"CBCLogEntry","op":"replace"},{"value":[{"text":"CBCLogEntry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogEntry\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}