{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/consoleloghandler\/loglevel"]},{"paths":["\/documentation\/chartboostcoresdk\/consoleloghandler\/loglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsoleLogHandler"]]},"abstract":[{"type":"text","text":"The desired log level."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevel","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LogLevel","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCLogLevel"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"logLevel"}],"title":"logLevel","role":"symbol","externalID":"c:@M@ChartboostCoreSDK@objc(cs)CBCConsoleLogHandler(py)logLevel","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCLogLevel","text":"LogLevel","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"ChartboostCoreSDK"}],"roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsoleLogHandler\/logLevel","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsoleLogHandler/logLevel":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsoleLogHandler\/logLevel","kind":"symbol","navigatorTitle":[{"text":"logLevel","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"logLevel","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCLogLevel","text":"LogLevel","kind":"typeIdentifier"}],"title":"logLevel","url":"\/documentation\/chartboostcoresdk\/consoleloghandler\/loglevel","type":"topic","abstract":[{"text":"The desired log level.","type":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ConsoleLogHandler":{"navigatorTitle":[{"text":"ConsoleLogHandler","kind":"identifier"}],"role":"symbol","title":"ConsoleLogHandler","url":"\/documentation\/chartboostcoresdk\/consoleloghandler","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConsoleLogHandler","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ConsoleLogHandler","abstract":[{"type":"text","text":"A "},{"code":"LogHandler","type":"codeVoice"},{"type":"text","text":" that logs to the console."}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel":{"navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"role":"symbol","title":"LogLevel","url":"\/documentation\/chartboostcoresdk\/loglevel","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogLevel","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel","abstract":[{"text":"Log severity levels for the unified logging subsystem.","type":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"logLevel","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"logLevel","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@E@CBCLogLevel","text":"CBCLogLevel"},{"kind":"text","text":" "},{"text":"logLevel","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsoleLogHandler~1logLevel\/title","op":"replace","value":"logLevel"},{"op":"replace","value":[{"text":"logLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsoleLogHandler~1logLevel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsoleLogHandler\/title","value":"CBCConsoleLogHandler","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsoleLogHandler\/fragments","value":[{"text":"CBCConsoleLogHandler","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"CBCConsoleLogHandler"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ConsoleLogHandler\/navigatorTitle","op":"replace"},{"value":"CBCLogLevel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel\/fragments","value":[{"text":"CBCLogLevel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel\/navigatorTitle","value":[{"text":"CBCLogLevel","kind":"identifier"}],"op":"replace"}]}]}