{"metadata":{"navigatorTitle":[{"text":"appTrackingTransparencyStatus","kind":"identifier"}],"platforms":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"14.0","name":"iPadOS","beta":false,"unavailable":false,"deprecated":false},{"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0","beta":false,"deprecated":false}],"roleHeading":"Instance Property","externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCAdvertisingEnvironment(py)appTrackingTransparencyStatus","modules":[{"name":"ChartboostCoreSDK"}],"symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appTrackingTransparencyStatus","kind":"identifier"},{"kind":"text","text":": "},{"text":"ATTrackingManager","preciseIdentifier":"c:objc(cs)ATTrackingManager","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"AuthorizationStatus","preciseIdentifier":"c:@E@ATTrackingManagerAuthorizationStatus","kind":"typeIdentifier"}],"required":true,"title":"appTrackingTransparencyStatus"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/chartboostcoresdk\/advertisingenvironment\/apptrackingtransparencystatus"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/advertisingenvironment\/apptrackingtransparencystatus"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AdvertisingEnvironment"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"appTrackingTransparencyStatus","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ATTrackingManager","preciseIdentifier":"c:objc(cs)ATTrackingManager"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@ATTrackingManagerAuthorizationStatus","kind":"typeIdentifier","text":"AuthorizationStatus"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"The tracking authorization status, as determined by the system’s AppTrackingTransparency","type":"text"},{"type":"text","text":" "},{"type":"text","text":"framework."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AdvertisingEnvironment\/appTrackingTransparencyStatus"},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AdvertisingEnvironment":{"navigatorTitle":[{"text":"AdvertisingEnvironment","kind":"identifier"}],"abstract":[{"type":"text","text":"An environment that contains information intended solely for advertising purposes."}],"url":"\/documentation\/chartboostcoresdk\/advertisingenvironment","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdvertisingEnvironment"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AdvertisingEnvironment","title":"AdvertisingEnvironment","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AdvertisingEnvironment/appTrackingTransparencyStatus":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AdvertisingEnvironment\/appTrackingTransparencyStatus","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appTrackingTransparencyStatus","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)ATTrackingManager","text":"ATTrackingManager","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"AuthorizationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@ATTrackingManagerAuthorizationStatus"}],"required":true,"abstract":[{"text":"The tracking authorization status, as determined by the system’s AppTrackingTransparency","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"framework."}],"type":"topic","role":"symbol","title":"appTrackingTransparencyStatus","kind":"symbol","url":"\/documentation\/chartboostcoresdk\/advertisingenvironment\/apptrackingtransparencystatus","navigatorTitle":[{"text":"appTrackingTransparencyStatus","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"introducedAt":"14.0","name":"iPadOS","beta":false,"unavailable":false,"deprecated":false},{"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0","beta":false,"deprecated":false}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"appTrackingTransparencyStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"appTrackingTransparencyStatus","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ATTrackingManagerAuthorizationStatus","preciseIdentifier":"c:@E@ATTrackingManagerAuthorizationStatus","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"appTrackingTransparencyStatus","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AdvertisingEnvironment\/title","value":"CBCAdvertisingEnvironment"},{"value":[{"kind":"identifier","text":"CBCAdvertisingEnvironment"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AdvertisingEnvironment\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AdvertisingEnvironment\/navigatorTitle","value":[{"kind":"identifier","text":"CBCAdvertisingEnvironment"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AdvertisingEnvironment~1appTrackingTransparencyStatus\/title","value":"appTrackingTransparencyStatus","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AdvertisingEnvironment~1appTrackingTransparencyStatus\/fragments","value":[{"kind":"identifier","text":"appTrackingTransparencyStatus"}],"op":"replace"}]}]}