{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AdvertisingEnvironment"]]},"sections":[],"abstract":[{"type":"text","text":"The height of the screen in pixels."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"screenHeightPixels","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/chartboostcoresdk\/advertisingenvironment\/screenheightpixels"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostcoresdk\/advertisingenvironment\/screenheightpixels"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AdvertisingEnvironment\/screenHeightPixels"},"metadata":{"title":"screenHeightPixels","required":true,"symbolKind":"property","modules":[{"name":"ChartboostCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"screenHeightPixels"}],"externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCAdvertisingEnvironment(py)screenHeightPixels","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"screenHeightPixels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"role":"symbol","roleHeading":"Instance Property"},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AdvertisingEnvironment":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdvertisingEnvironment"}],"role":"symbol","url":"\/documentation\/chartboostcoresdk\/advertisingenvironment","title":"AdvertisingEnvironment","kind":"symbol","navigatorTitle":[{"text":"AdvertisingEnvironment","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AdvertisingEnvironment","abstract":[{"type":"text","text":"An environment that contains information intended solely for advertising purposes."}],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AdvertisingEnvironment/screenHeightPixels":{"title":"screenHeightPixels","type":"topic","kind":"symbol","required":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AdvertisingEnvironment\/screenHeightPixels","navigatorTitle":[{"text":"screenHeightPixels","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/advertisingenvironment\/screenheightpixels","abstract":[{"text":"The height of the screen in pixels.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"screenHeightPixels"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"screenHeightPixels"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"screenHeightPixels"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"screenHeightPixels","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"CBCAdvertisingEnvironment","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AdvertisingEnvironment\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AdvertisingEnvironment\/fragments","value":[{"kind":"identifier","text":"CBCAdvertisingEnvironment"}]},{"op":"replace","value":"screenHeightPixels","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AdvertisingEnvironment~1screenHeightPixels\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AdvertisingEnvironment~1screenHeightPixels\/fragments","op":"replace","value":[{"text":"screenHeightPixels","kind":"identifier"}]}]}]}