{"metadata":{"title":"appSessionDuration","modules":[{"name":"ChartboostCoreSDK"}],"navigatorTitle":[{"text":"appSessionDuration","kind":"identifier"}],"required":true,"symbolKind":"property","externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCAnalyticsEnvironment(py)appSessionDuration","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"appSessionDuration"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/appSessionDuration"},"abstract":[{"type":"text","text":"The session duration, or "},{"code":"0","type":"codeVoice"},{"text":" if the ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/initializeSDK(configuration:moduleObserver:)","type":"reference","isActive":true},{"text":" ","type":"text"},{"type":"text","text":"method has not been called yet."},{"type":"text","text":" "},{"text":"A session starts the moment ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/initializeSDK(configuration:moduleObserver:)","isActive":true},{"text":" is","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"called for the first time."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/analyticsenvironment\/appsessionduration"]},{"paths":["\/documentation\/chartboostcoresdk\/analyticsenvironment\/appsessionduration"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"appSessionDuration","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment"]]},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment/appSessionDuration":{"url":"\/documentation\/chartboostcoresdk\/analyticsenvironment\/appsessionduration","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/appSessionDuration","kind":"symbol","type":"topic","required":true,"title":"appSessionDuration","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"appSessionDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"role":"symbol","navigatorTitle":[{"text":"appSessionDuration","kind":"identifier"}],"abstract":[{"type":"text","text":"The session duration, or "},{"type":"codeVoice","code":"0"},{"type":"text","text":" if the "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/initializeSDK(configuration:moduleObserver:)","type":"reference"},{"text":" ","type":"text"},{"text":"method has not been called yet.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"A session starts the moment "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/initializeSDK(configuration:moduleObserver:)"},{"text":" is","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"called for the first time."}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/ChartboostCore/initializeSDK(configuration:moduleObserver:)":{"title":"initializeSDK(configuration:moduleObserver:)","navigatorTitle":[{"text":"initializeSDKWithConfiguration:moduleObserver:","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Initializes the Core SDK and its modules.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initializeSDK","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(cs)CBCSDKConfiguration","text":"SDKConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"moduleObserver"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCModuleObserver","kind":"typeIdentifier","text":"ModuleObserver"},{"kind":"text","text":"?)"}],"url":"\/documentation\/chartboostcoresdk\/chartboostcore\/initializesdk(configuration:moduleobserver:)","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/ChartboostCore\/initializeSDK(configuration:moduleObserver:)","kind":"symbol","type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment","navigatorTitle":[{"text":"AnalyticsEnvironment","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"An environment that contains information intended solely for analytics purposes.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnalyticsEnvironment"}],"title":"AnalyticsEnvironment","url":"\/documentation\/chartboostcoresdk\/analyticsenvironment","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"appSessionDuration"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"appSessionDuration"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"appSessionDuration"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1appSessionDuration\/title","value":"appSessionDuration","op":"replace"},{"value":[{"kind":"identifier","text":"appSessionDuration"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1appSessionDuration\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1initializeSDK(configuration:moduleObserver:)\/title","value":"initializeSDKWithConfiguration:moduleObserver:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"initializeSDKWithConfiguration:moduleObserver:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1ChartboostCore~1initializeSDK(configuration:moduleObserver:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment\/title","value":"CBCAnalyticsEnvironment","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment\/fragments","value":[{"kind":"identifier","text":"CBCAnalyticsEnvironment"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment\/navigatorTitle","value":[{"kind":"identifier","text":"CBCAnalyticsEnvironment"}]}]}]}