{"metadata":{"required":true,"navigatorTitle":[{"text":"appTrackingTransparencyStatus","kind":"identifier"}],"platforms":[{"unavailable":false,"name":"iOS","deprecated":false,"beta":false,"introducedAt":"14.0"},{"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false,"beta":false}],"externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCAnalyticsEnvironment(py)appTrackingTransparencyStatus","roleHeading":"Instance Property","modules":[{"name":"ChartboostCoreSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"appTrackingTransparencyStatus","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ATTrackingManager","preciseIdentifier":"c:objc(cs)ATTrackingManager"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@ATTrackingManagerAuthorizationStatus","text":"AuthorizationStatus","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","title":"appTrackingTransparencyStatus"},"variants":[{"paths":["\/documentation\/chartboostcoresdk\/analyticsenvironment\/apptrackingtransparencystatus"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/analyticsenvironment\/apptrackingtransparencystatus"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"appTrackingTransparencyStatus"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)ATTrackingManager","kind":"typeIdentifier","text":"ATTrackingManager"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ATTrackingManagerAuthorizationStatus","text":"AuthorizationStatus"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment"]]},"abstract":[{"type":"text","text":"The tracking authorization status, as determined by the system’s AppTrackingTransparency"},{"text":" ","type":"text"},{"type":"text","text":"framework."}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/appTrackingTransparencyStatus","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment/appTrackingTransparencyStatus":{"abstract":[{"type":"text","text":"The tracking authorization status, as determined by the system’s AppTrackingTransparency"},{"type":"text","text":" "},{"text":"framework.","type":"text"}],"role":"symbol","title":"appTrackingTransparencyStatus","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/appTrackingTransparencyStatus","required":true,"kind":"symbol","navigatorTitle":[{"text":"appTrackingTransparencyStatus","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"appTrackingTransparencyStatus"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ATTrackingManager","text":"ATTrackingManager"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ATTrackingManagerAuthorizationStatus","text":"AuthorizationStatus"}],"url":"\/documentation\/chartboostcoresdk\/analyticsenvironment\/apptrackingtransparencystatus","type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment","navigatorTitle":[{"text":"AnalyticsEnvironment","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"An environment that contains information intended solely for analytics purposes.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnalyticsEnvironment"}],"title":"AnalyticsEnvironment","url":"\/documentation\/chartboostcoresdk\/analyticsenvironment","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"deprecated":false,"introducedAt":"14.0","name":"iOS","unavailable":false,"beta":false},{"deprecated":false,"introducedAt":"14.0","name":"iPadOS","unavailable":false,"beta":false},{"unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false,"introducedAt":"14.0"}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"appTrackingTransparencyStatus","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"appTrackingTransparencyStatus"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ATTrackingManagerAuthorizationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@E@ATTrackingManagerAuthorizationStatus"},{"kind":"text","text":" "},{"text":"appTrackingTransparencyStatus","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"appTrackingTransparencyStatus","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1appTrackingTransparencyStatus\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1appTrackingTransparencyStatus\/fragments","value":[{"text":"appTrackingTransparencyStatus","kind":"identifier"}],"op":"replace"},{"value":"CBCAnalyticsEnvironment","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment\/title","op":"replace"},{"value":[{"text":"CBCAnalyticsEnvironment","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"CBCAnalyticsEnvironment"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}