{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/deviceLocale"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"roleHeading":"Instance Property","title":"deviceLocale","role":"symbol","externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCAnalyticsEnvironment(py)deviceLocale","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deviceLocale"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"deviceLocale"}],"modules":[{"name":"ChartboostCoreSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceLocale"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"abstract":[{"text":"The device locale string, e.g. “en-US”.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/analyticsenvironment\/devicelocale"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/analyticsenvironment\/devicelocale"]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment","navigatorTitle":[{"text":"AnalyticsEnvironment","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"An environment that contains information intended solely for analytics purposes.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnalyticsEnvironment"}],"title":"AnalyticsEnvironment","url":"\/documentation\/chartboostcoresdk\/analyticsenvironment","kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment/deviceLocale":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/deviceLocale","type":"topic","abstract":[{"type":"text","text":"The device locale string, e.g. “en-US”."}],"title":"deviceLocale","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"deviceLocale","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"text":"deviceLocale","kind":"identifier"}],"required":true,"url":"\/documentation\/chartboostcoresdk\/analyticsenvironment\/devicelocale"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"deviceLocale","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"deviceLocale"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"deviceLocale","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"CBCAnalyticsEnvironment","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CBCAnalyticsEnvironment"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment\/navigatorTitle","op":"replace","value":[{"text":"CBCAnalyticsEnvironment","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1deviceLocale\/title","value":"deviceLocale","op":"replace"},{"value":[{"text":"deviceLocale","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1deviceLocale\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}