{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"frameworkVersion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/frameworkVersion","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment"]]},"abstract":[{"type":"text","text":"The framework version set by the publisher through a call to "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/PublisherMetadata\/setFramework(name:version:)","isActive":true},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/chartboostcoresdk\/analyticsenvironment\/frameworkversion"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/analyticsenvironment\/frameworkversion"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"required":true,"roleHeading":"Instance Property","modules":[{"name":"ChartboostCoreSDK"}],"navigatorTitle":[{"text":"frameworkVersion","kind":"identifier"}],"title":"frameworkVersion","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frameworkVersion","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCAnalyticsEnvironment(py)frameworkVersion","symbolKind":"property"},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment","navigatorTitle":[{"text":"AnalyticsEnvironment","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"An environment that contains information intended solely for analytics purposes.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnalyticsEnvironment"}],"title":"AnalyticsEnvironment","url":"\/documentation\/chartboostcoresdk\/analyticsenvironment","kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/PublisherMetadata/setFramework(name:version:)":{"url":"\/documentation\/chartboostcoresdk\/publishermetadata\/setframework(name:version:)","abstract":[{"type":"text","text":"Sets the framework name and version for this app, e.g. (“Unity”, “2022.3”)."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setFramework","kind":"identifier"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"version"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/PublisherMetadata\/setFramework(name:version:)","navigatorTitle":[{"kind":"identifier","text":"setFrameworkWithName:version:"}],"type":"topic","kind":"symbol","title":"setFramework(name:version:)"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment/frameworkVersion":{"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/frameworkVersion","navigatorTitle":[{"text":"frameworkVersion","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/chartboostcoresdk\/analyticsenvironment\/frameworkversion","title":"frameworkVersion","abstract":[{"text":"The framework version set by the publisher through a call to ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/PublisherMetadata\/setFramework(name:version:)"},{"text":".","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameworkVersion"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"required":true,"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"frameworkVersion","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"frameworkVersion","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"frameworkVersion","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment\/title","value":"CBCAnalyticsEnvironment","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment\/fragments","value":[{"text":"CBCAnalyticsEnvironment","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment\/navigatorTitle","value":[{"kind":"identifier","text":"CBCAnalyticsEnvironment"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1PublisherMetadata~1setFramework(name:version:)\/title","value":"setFrameworkWithName:version:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setFrameworkWithName:version:"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1PublisherMetadata~1setFramework(name:version:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1frameworkVersion\/title","value":"frameworkVersion"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1frameworkVersion\/fragments","value":[{"kind":"identifier","text":"frameworkVersion"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}