{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/removeObserver(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment"]]},"abstract":[{"type":"text","text":"Removes a previously-added observer."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/analyticsenvironment\/removeobserver(_:)"]},{"paths":["\/documentation\/chartboostcoresdk\/analyticsenvironment\/removeobserver(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCAnalyticsEnvironment(im)removeObserver:","modules":[{"name":"ChartboostCoreSDK"}],"title":"removeObserver(_:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeObserver"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCEnvironmentObserver","text":"EnvironmentObserver","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"removeObserver:"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeObserver","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"observer","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCEnvironmentObserver","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver","text":"EnvironmentObserver"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment/removeObserver(_:)":{"kind":"symbol","type":"topic","title":"removeObserver(_:)","required":true,"role":"symbol","navigatorTitle":[{"text":"removeObserver:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/removeObserver(_:)","url":"\/documentation\/chartboostcoresdk\/analyticsenvironment\/removeobserver(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeObserver"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ChartboostCoreSDK@objc(pl)CBCEnvironmentObserver","text":"EnvironmentObserver"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Removes a previously-added observer."}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/EnvironmentObserver":{"url":"\/documentation\/chartboostcoresdk\/environmentobserver","kind":"symbol","title":"EnvironmentObserver","abstract":[{"type":"text","text":"An observer that gets notified when the value of some observable environment field changes."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/EnvironmentObserver","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EnvironmentObserver"}],"navigatorTitle":[{"text":"EnvironmentObserver","kind":"identifier"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment":{"navigatorTitle":[{"kind":"identifier","text":"AnalyticsEnvironment"}],"url":"\/documentation\/chartboostcoresdk\/analyticsenvironment","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnalyticsEnvironment"}],"abstract":[{"type":"text","text":"An environment that contains information intended solely for analytics purposes."}],"title":"AnalyticsEnvironment","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"removeObserver:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeObserver:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"removeObserver:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@ChartboostCoreSDK@objc(pl)CBCEnvironmentObserver","kind":"typeIdentifier","text":"id<CBCEnvironmentObserver>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"observer"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"removeObserver:","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1removeObserver(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeObserver:"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1removeObserver(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/title","value":"CBCEnvironmentObserver"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1EnvironmentObserver\/fragments","value":[{"text":"CBCEnvironmentObserver","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment\/title","value":"CBCAnalyticsEnvironment","op":"replace"},{"value":[{"kind":"identifier","text":"CBCAnalyticsEnvironment"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment\/fragments"}]}]}