{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userAgent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"userAgent"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Handler executed at the end of the user agent fetch operation.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"It returns either a valid string value or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the fetch fails."},{"type":"text","text":" "},{"type":"text","text":"If a valid value is already cached, the completion executes immediately."}]}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/chartboostcoresdk\/analyticsenvironment\/useragent(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/chartboostcoresdk\/analyticsenvironment\/useragent(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Obtain the device user agent asynchronously."}],"metadata":{"symbolKind":"method","externalID":"c:@M@ChartboostCoreSDK@objc(pl)CBCAnalyticsEnvironment(im)userAgentWithCompletion:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userAgent"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"userAgent","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"title":"userAgent(completion:)","modules":[{"name":"ChartboostCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"userAgentWithCompletion:"}],"role":"symbol","required":true},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/userAgent(completion:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment/userAgent(completion:)":{"kind":"symbol","type":"topic","title":"userAgent(completion:)","required":true,"role":"symbol","navigatorTitle":[{"text":"userAgentWithCompletion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment\/userAgent(completion:)","url":"\/documentation\/chartboostcoresdk\/analyticsenvironment\/useragent(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"userAgent","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"userAgent","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Obtain the device user agent asynchronously."}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/AnalyticsEnvironment":{"navigatorTitle":[{"kind":"identifier","text":"AnalyticsEnvironment"}],"url":"\/documentation\/chartboostcoresdk\/analyticsenvironment","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnalyticsEnvironment"}],"abstract":[{"type":"text","text":"An environment that contains information intended solely for analytics purposes."}],"title":"AnalyticsEnvironment","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/AnalyticsEnvironment","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"userAgentWithCompletion:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"userAgentWithCompletion:"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"userAgentWithCompletion:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#*$objc(cs)NSString)","text":"void (^)(NSString *)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1userAgent(completion:)\/title","op":"replace","value":"userAgentWithCompletion:"},{"value":[{"text":"- ","kind":"text"},{"text":"userAgentWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment~1userAgent(completion:)\/fragments","op":"replace"},{"value":"CBCAnalyticsEnvironment","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1AnalyticsEnvironment\/fragments","value":[{"text":"CBCAnalyticsEnvironment","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}