{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(from:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"decoder","kind":"internalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP","text":"Decoder"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/init(from:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/chartboostcoresdk\/loglevel\/init(from:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/RawRepresentable-Implementations"]]},"metadata":{"extendedModule":"Swift","title":"init(from:)","externalID":"s:SYsSeRzSi8RawValueSYRtzrlE4fromxs7Decoder_p_tKcfc::SYNTHESIZED::c:@M@ChartboostCoreSDK@E@CBCLogLevel","roleHeading":"Initializer","symbolKind":"init","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Decodable"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" is "},{"code":"Int","type":"codeVoice"},{"text":".","type":"text"}]},"role":"symbol","modules":[{"name":"ChartboostCoreSDK","relatedModules":["Swift"]}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": any "},{"text":"Decoder","kind":"typeIdentifier","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel/RawRepresentable-Implementations":{"kind":"article","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/RawRepresentable-Implementations","url":"\/documentation\/chartboostcoresdk\/loglevel\/rawrepresentable-implementations","role":"collectionGroup","type":"topic","title":"RawRepresentable Implementations","abstract":[]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel":{"navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"role":"symbol","title":"LogLevel","url":"\/documentation\/chartboostcoresdk\/loglevel","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogLevel","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel","abstract":[{"text":"Log severity levels for the unified logging subsystem.","type":"text"}]},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"abstract":[],"kind":"symbol","type":"topic","role":"collection","title":"ChartboostCoreSDK","url":"\/documentation\/chartboostcoresdk","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel/init(from:)":{"conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Decodable","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" is ","type":"text"},{"type":"codeVoice","code":"Int"},{"type":"text","text":"."}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"url":"\/documentation\/chartboostcoresdk\/loglevel\/init(from:)","role":"symbol","title":"init(from:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s7DecoderP","text":"Decoder","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/init(from:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"CBCLogLevel","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel\/fragments","value":[{"text":"CBCLogLevel","kind":"identifier"}]},{"value":[{"text":"CBCLogLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel\/navigatorTitle"}]}]}