{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/verbose","interfaceLanguage":"swift"},"abstract":[{"text":"Log very low level and\/or noisy information that may be useful during development or troubleshooting.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verbose"}]}]}],"variants":[{"paths":["\/documentation\/chartboostcoresdk\/loglevel\/verbose"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/chartboostcoresdk\/loglevel\/verbose"]}],"metadata":{"symbolKind":"case","externalID":"c:@M@ChartboostCoreSDK@E@CBCLogLevel@CBCLogLevelVerbose","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"verbose"}],"title":"LogLevel.verbose","modules":[{"name":"ChartboostCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"CBCLogLevelVerbose"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel"]]},"references":{"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel":{"navigatorTitle":[{"text":"LogLevel","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"kind":"symbol","abstract":[{"text":"Log severity levels for the unified logging subsystem.","type":"text"}],"url":"\/documentation\/chartboostcoresdk\/loglevel","title":"LogLevel","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel","role":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK/LogLevel/verbose":{"navigatorTitle":[{"text":"CBCLogLevelVerbose","kind":"identifier"}],"url":"\/documentation\/chartboostcoresdk\/loglevel\/verbose","type":"topic","role":"symbol","abstract":[{"text":"Log very low level and\/or noisy information that may be useful during development or troubleshooting.","type":"text"}],"title":"LogLevel.verbose","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"verbose","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK\/LogLevel\/verbose","kind":"symbol"},"doc://org.cocoapods.ChartboostCoreSDK/documentation/ChartboostCoreSDK":{"role":"collection","url":"\/documentation\/chartboostcoresdk","title":"ChartboostCoreSDK","kind":"symbol","identifier":"doc:\/\/org.cocoapods.ChartboostCoreSDK\/documentation\/ChartboostCoreSDK","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"CBCLogLevelVerbose","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"CBCLogLevelVerbose","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"CBCLogLevelVerbose"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"CBCLogLevel","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"CBCLogLevel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel~1verbose\/title","value":"CBCLogLevelVerbose"},{"value":[{"text":"CBCLogLevelVerbose","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.ChartboostCoreSDK~1documentation~1ChartboostCoreSDK~1LogLevel~1verbose\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}